ngageoint/opensphere

src/os/user/settings/favoritemanager.js

Initial work on cleanup up the warnings that are making it hard to see if there are real problems.

Remove unused managerlink_ member.

---

scss/os/partials/_navbar.scss
scss/ui/partials/ui/onboarding/_ngonboarding.scss
scss/ui/vendor/_nganimate.scss

First cut, so we can start to see if there are really any issues in that linter output.

Fix some minor CSS format issues causing linter noise.

---

.travis.yml

See https://github.com/travis-ci/travis-ci/issues/1066

Fail build on first failed script

---

src/os/feature/measurefeature.js
src/os/interaction/measureinteraction.js

fix(measure): Use three decimal places for bearing.

---

src/os/ui/measurebutton.js

Replaces deprecated Action / ActionManager implementation.

refactor(measure): Update measure tool UI implementation.

---

DEVELOPING.md
README.md

See [README.md](https://github.com/schmidtk/opensphere/blob/yarn-docs/README.md) and [DEVELOPING.md](https://github.com/schmidtk/opensphere/blob/yarn-docs/DEVELOPING.md) for rendered markdown with these changes.

Add documentation for yarn.

---

src/os/ui/datetime/wheeldate.js

Resolves #46 to use ISO-8601 (not browser / server locale).

fix(wheeldate): Make wheeldate use ISO-8601 date format.

---

PLUGIN_DEVELOPMENT.md

Also added a section pointing over to the external plugin example.

docs(plugin): links galore!

---

docs/guides/plugin_file_type_guide/test/plugin/georss/georsstypemethod.test.js

Add missing UUT

---

config/settings.json

Fixes format dependency on tab spacing, makes file consistent throughout.

chore(settings): Replace tabs with spaces.

---

views/plugin/geonames/geonamesresultcard.html

fix(geonames): clean up left-over view for geonames.

---

docs/guides/app_code_guide/index.rst
docs/guides/app_guide.rst
docs/guides/app_index_guide/index.rst
docs/guides/app_package_guide/index.rst
docs/guides/app_package_guide/package/build.json
docs/guides/app_package_guide/package/directories.json

Add initial application guide.

---

scss/ui/partials/_popover.scss
scss/ui/vendor/_nganimate.scss

Resolves #110  (in conjunction with part of #109).

chore(sass-lint): Suppress warnings for external mixins.

---

.sass-lint.yml
scss/os/overrides/_bootstrap.scss
scss/os/overrides/_openlayers.scss
scss/os/overrides/_select2.scss
scss/os/partials/_datetime.scss
scss/os/partials/_main.scss
scss/os/partials/_navbar.scss
scss/os/partials/_servers.scss
scss/os/partials/_tree.scss
scss/os/partials/_window.scss
scss/ui/modules/_mixins.scss
scss/ui/partials/_form.scss
scss/ui/partials/_misc.scss
scss/ui/partials/_tristate.scss
scss/ui/partials/ui/datetime/_datetime.scss
scss/ui/partials/ui/onboarding/_ngonboarding.scss
scss/ui/partials/ui/wiz/_importwizard.scss

fix(sass): Fix remaining sass-lint warnings and upgrade configuration.

---

src/os/ui/geo/position.js
test/os/ui/geo/positionctrl.test.js

Also switch from just blindly appending N and E to using appropriate hemisphere.
Resolves #119.
8 decimal places is mm scale (12 is 100s of nanometres). Even 8 seems like a lot - a single pixel is two orders of magnitude larger at zoom level 20.

fix(ui): Reduce precision to mm scale.

---

src/os/ui/ol/interaction/dragboxinteraction.js

fix(dragbox): Don't update if start/end coord are missing.

---

CONTRIBUTING.md
README.md
docs/contributing.rst
docs/index.rst

Resolves #123
I suppose most projects have a real-time chat solution as well. How do we feel about Slack?

docs(forum): move contributing to docs and mention forum

---

config/settings.json
docs/guides/settings_guide.rst
docs/index.rst

docs(settings): added settings guide

---

src/os/ui/header/scrollheader.js
src/os/ui/ol/control/layerswitcher.js
src/os/ui/ol/draw/drawcontrols.js
src/os/ui/ol/olmap.js

This fixes compile errors found while building an external library depending on OpenSphere.

Fix GCC type and conformance errors.

---

src/os/unit/metricunits.js
test/os/unit/metricunits.test.js

fix(units): correct metric units for 1e-6 and 1e-9.

---

src/os/source/vectorsource.js

Fixes style shapes that change geometry (ellipse and LOB). Previously they would not display in the OpenLayers view if the original (point) geometry was off the viewport. This is done by updating the spatial index with the combined extent of the new geometry with the original for each feature.
When the style is turned off, the index reverts to only the original geometry extent.
Resolves #107 
@welchyd

Index ellipse and lob shapes in the r-tree

---

src/plugin/file/kml/kmlparser.js
test/plugin/file/kml/kmlparser.test.js
test/plugin/file/kml/schema_noname_test.xml

fix(kml): Handle KML file that has Schema without name attribute

---

src/os/main.js

This was only occuring on very slow networks and did not have much of an impact other than a couple of errors in the console. Subsequent calls to the function worked fine after the load completed.

fix(main): fix race condition on osasm load

---

src/os/interaction/interaction.js
src/os/ui/ol/interaction/mousewheelzoominteraction.js

Allow pinch zoom on trackpads.

---

src/os/interaction/pinchzoominteraction.js
src/os/map/mapinteractions.js
test/os/interaction/pinchzoominteraction.test.js

feature(map): Add pinch-zoom interaction for 2D map.

---

src/os/data/basedescriptor.js
src/os/data/idatadescriptor.js
src/os/ui/data/adddatactrl.js
src/os/ui/menu/layermenu.js
test/os/data/basedescriptor.test.js

feature(layer): allow override of the layer description.

---

src/os/state/jsonstatetypemethod.js
src/os/ui/datetime/duration.js
src/os/ui/featureedit.js
src/os/ui/help/supportmsg.js
src/os/ui/ol/control/layerswitcher.js
src/os/ui/query/areatreesearch.js
src/os/ui/state/abstractstatedescriptor.js

Fix warnings from the Closure Compiler.

---

src/os/filter/impl/ecql/areaformatter.js
src/os/filter/impl/ecql/exclusionformatter.js
src/os/filter/impl/ecql/filterformatter.js
src/os/query/ecqlqueryhandler.js
test/os/filter/impl/ecql/areaformatter.test.js
test/os/filter/impl/ecql/exclusionformatter.test.js
test/os/filter/impl/ecql/filterformatter.test.js

Adds support for ECQL filter format. See http://docs.geoserver.org/stable/en/user/filter/ecql_reference.html for more details.

Add ECQL support

---

src/os/geom/ellipse.js

chore(geom): Update jsdoc for os.geom.Ellipse.

---

src/os/mixin/urltilemixin.js

The loading logic should depend on the changes in tile state rather than the underlying image state. This allows it to still work properly with special tile classes or tile load functions that use something other than image tags.

fix(urltile): use tile state rather than image state

---

externs/modernizr.externs.js
externs/platform.externs.js

chore(externs) add externs for platform js

---

src/os/capture/capture.js
src/os/ui/capture/canvasrenderer.js
src/os/ui/capture/svgrenderer.js
src/os/ui/capture/timelinerenderer.js
src/plugin/capture/captureplugin.js
src/plugin/capture/legendrenderer.js
src/plugin/capture/mapoverlayrenderer.js
src/plugin/capture/maprenderer.js

fix(capture): Scale renderers to match map DPI.

---

src/os/storage/idbstorage.js
test/os/storage/asyncstoragewrapper.test.js
test/os/storage/idbstorage.test.js
test/os/storage/storage.mock.js

fix(idb): Don't create object store if it already exists.

---

docs/guides/deployment_guide.rst
docs/guides/settings_guide.rst
docs/index.rst

docs(rtd): add deployment guide

---

externs/Cesium.externs.js
src/plugin/cesium/sync/featureconverter.js

This fixes polygon outline geos not working in debug mode.

fix(cesium): Fixed Cesium dev error on line width value

---

src/os/mainctrl.js

Open File/URL import for filters was working, but not the Filters > Import path.

fix(filter): Filter > Import needs proper type constant

---

src/os/ui/featureedit.js
src/plugin/places/places.js
views/windows/featureedit.html

Add altitude to saved places.

---

src/plugin/area/areaplugin.js
src/plugin/area/geojsonareaimport.js
src/plugin/area/geojsonareaimportui.js

Resolves #256. GeoJSON files can now be imported into areas.

Issue256 GeoJSON import

---

package.json
src/plugin/file/csv/csvexporter.js
test/plugin/file/csv/csvexporter.test.js

Fixed bug where you cannot export csv data that has no geometry data.

Export CSV with no geometry data.

---

scss/os/_alertpopup.scss
scss/os/_utils.scss
src/os/ui/alert/alertpopup.js
views/alert/alertpopup.html

AlertPopup now selectable and urls have hyperlinks

---

src/os/config/displaysettings.js
src/os/ui/menu/mapmenu.js
src/os/webgl/abstractwebglrenderer.js
src/plugin/cesium/cesium.js
src/plugin/cesium/cesiumrenderer.js
views/config/displaysettings.html

feat(cesium): Add sky support to Cesium.

---

src/os/olm/render/baseshape.js

Uses some inspiration from `ol/interaction/draw.js` to solve the wrapped drawing feature issue.
resolves #342

fix(draw): Fix drawing in wrapped extents

---

src/os/interaction/drawlineinteraction.js
src/os/ui/ol/interaction/drawpolygoninteraction.js

Allows drag-pan while drawing polygons, drawing lines, or drawing measure lines.

feat(draw): Allow drag pan during click interactions

---

src/os/ui/menu/layermenu.js

Fixes error with window ready event not firing and removes unnecessary code.

Open Layer Description with confirm.

---

src/os/storage/storage.js

This helps eliminate arbitrary sleeps in test code.
Fixes #371

fix(storage): cls test helper should return promise

---

src/os/ui/ogc/iogcdescriptor.js
src/os/ui/ogc/ogcdescriptor.js
src/os/ui/ogc/ogcserver.js
src/plugin/ogc/ogclayerdescriptor.js

The custom WFS params set on the server were not being passed through to the GetFeature request.

fix(wfs): pass custom WFS params in GetFeature requests

---

src/os/ui/timeline/currenttimemarker.js

Move live counter to right of current time line
Make future time shade visible in Firefox
Include zulu offset in current time display

feat(timeline): Timeline Live Display Improvements

---

src/os/ui/layers.js
src/os/ui/menu/menubutton.js
src/os/ui/menu/windowsmenu.js
src/os/ui/menubutton.js

Toggle Add Data/Layers windows

---

src/plugin/file/kml/kmlsource.js
src/plugin/file/kml/ui/kmlnode.js

fix(Annotations): Annotations obey the time on the timeline.

---

src/os/ui/adddata.js
src/os/ui/layers.js

fix(groupby): do not show defunct group bys in view list

---

src/os/proj/projswitch.js
src/os/query/query.js
src/plugin/cesium/sync/featureconverter.js
test/os/query/query.test.js

fix(cesium): avoid showing full world areas

---

src/plugin/places/kmlplacesimportui.js

fix(ImportPlaces): Saved Places imports kml files successfully.

---

src/os/interaction/hoverinteraction.js

Fixes feature sticking when the geometry changes, or remaining highlighted when no longer under the cursor.
These were only issues in 2D mode, where we use a feature overlay to ensure the highlighted feature is always on top of all others.

Update highlighted feature when geometry changes.

---

cypress/integration/smoke-tests/toolbar-center.spec.js
cypress/integration/smoke-tests/toolbar-right.spec.js

#385 
These lines are no longer needed now that the underlying issue with OS has been resolved.

test(cypress): Removes triple click workaround

---

externs/osasm.externs.js

Reflects changes made in https://github.com/ngageoint/opensphere-asm/pull/1.

Update osasm extern documentation.

---

.travis.yml

build(travis): Corrections to fix build errors

---

src/os/histo/datebinmethod.js
test/os/histo/datebinmethod.test.js

Add 'Month of Year' as a new bin method.

feat(datebinmethod): Add Month of Year

---

views/plugin/suncalc/suncalc.html

fix(suncalc): Typo fix for Azimuth tooltip.

---

src/plugin/file/kml/ui/kmltreeexportui.js
views/plugin/kml/kmlexport.html
views/plugin/kml/kmltreeexport.html

fix(KMLExport): Unused options are removed from the export places.

---

src/os/style/label.js

refactor(label.js): Changed max label size to 48px

---

cypress/support/selectors.js
src/os/data/areanode.js
src/os/query/basequerymanager.js
src/os/query/query.js
src/os/ui/layers.js
src/os/ui/menu/spatialmenu.js
test/os/ui/query/basequerymanager.test.js
views/windows/layers.html

Add active area/filter counts to Layers window tabs

---

src/os/interaction/hoverinteraction.js

Handles cases where the highlight change came through the source, instead of the interaction.
This prevents the highlighted feature (in the overlay) from sticking to the map, while the original on the source moves.

fix(hover): Update highlight overlay when geometry changes.

---

src/os/structs/structs.js
src/plugin/file/kml/ui/kmlui.js
src/plugin/file/kml/ui/placemarkedit.js
test/plugin/file/kml/ui/placemarkededit.test.js
views/windows/featureedit.html

feat(places): Add option to choose folder in places add/edit menu

---

src/plugin/file/kml/ui/kmlui.js

click of edit btn created multiple windows. now only one window.
fix #506

fix: Many windows

---

src/os/data/idataprovider.js
src/os/ui/data/adddatactrl.js
src/os/ui/data/baseprovider.js
src/os/ui/ogc/ogcserver.js
src/os/ui/server/abstractloadingserver.js
src/plugin/arc/arcserver.js
src/plugin/basemap/basemapprovider.js
src/plugin/config/configprovider.js
src/plugin/ogc/geoserver.js
src/plugin/wmts/wmtsserver.js

The AddDataCtrl is extended in the metrics control, and we aren't always passing
in IDataProvider nodes.

fix(metrics): Fix display of metrics UI nodes in debug.

---

dossier.conf.json
externs/angular-1.5-os.js
package.json

I split this into two commits to update to the original externs, and separately apply our changes. Our externs changes resolve compiler issues between `jQuery` and `angular.JQLite`. Verified via `git diff ../../node_modules/google-closure-compiler/contrib/externs/angular-1.4.js externs/angular-1.4-os.js` that we didn't have further changes to the original externs.

Update Angular externs to 1.5.

---

scss/os/_overrides_bootstrap.scss
scss/standard/_variables.scss
src/os/ui/menu/menuitem.js

Also fixes a bug where CSS classes in menu items were joined with `, ` instead of a space.

Style dropdown headers similar to card headers

---

src/os/mainctrl.js
src/plugin/places/placeshidecmd.js
src/plugin/places/placesplugin.js

feat(ClearPlaces): The clear menu now can hide places and annotations.

---

src/os/geo/geo.js
test/os/geo/geo.test.js

fix(geo): Avoid DDM and DMS display of "60"

---

package.json
src/os/state/v4/timestate.js
test/os/state/v4/timestate.test.js

THIN-13358
Resolves #597 
This requires ngageoint/opensphere-state-schema#11 to work

feat(states): Add timeline lock to states

---

src/plugin/wmts/wmtsserver.js

Just stuff noted while looking for something else....

docs(wmts): Trivial cleanup on WMTS apidoc.

---

index.js
package.json

Removed unused `styles/icons` resource.

chore(resolver): Upgrade resolver to 6.0.0.

---

docs/contributing.rst
docs/getting_started.rst
docs/guides/cypress_artifacts.rst

Also fix link from contributing page, and warning about page not in toctree.
Resolves #707 and #666

docs: Add git commit notes.

---

conformance_config.textproto
src/os/ui/sourcegrid.js
src/os/ui/text/tuieditor.js

Update two users.
Also add violation for unused `goog.isNull()` and `goog.isDefAndNotNull()`.
Resolves #165

chore(conformance): Add conformance violation for goog.isDef()

---

commitlint.config.js
package.json

chore: switch to commitlint

---

cypress/support/selectors/layers.js

Reflects change in https://github.com/ngageoint/opensphere/commit/e6ede62b28d47d7c98b16975c55632cc12141b45

test(cypress): correct Add Places selector

---

src/plugin/cesium/sync/featureconverter.js

fix(cesium): fix altitude mode change for collections

---

package.json
tasks/xt/gcc-args.json

Update ES Version

---

src/os/ui/filter/filter.js
src/os/ui/filter/op/isfalseop.js
src/os/ui/filter/op/istrueop.js
test/os/ui/filter/op/isfalseop.test.js
test/os/ui/filter/op/istrueop.test.js

Add boolean filters

---

scss/os/_overrides_tuieditor.scss

fix tuieditior zindex

---

cypress/integration/smoke-tests/load-state-file-url-kml.spec.js

Referenced ticket has since been closed.  Images look correct (no push pin). Just removed comment.

test(cypress): removes obe comment

---

docs/guides/plugin_server_guide/parsing.rst
docs/guides/plugin_server_guide/plugin.rst
docs/guides/plugin_server_guide/provider.rst
docs/guides/plugin_server_guide/server_ui.rst
docs/guides/plugin_server_guide/src/plugin/tileserver/mime.js
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserver.js-parsing
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserver.js-provider
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverconstants.js
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverimport.js-server_ui
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverplugin.js-parsing
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverplugin.js-plugin
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverplugin.js-provider
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverplugin.js-server_ui-1
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserverplugin.js-server_ui-2

ID should be defined in a separate file so it can be used by `mime.js`.

docs(rtd): fix undefined ID in mime.js

---

src/os/ui/feature/multifeatureinfo.js
src/os/ui/sourcegrid.js

Switch from private to protected for extensibility

feat(grid): change getValueFromFeature to protected

---

docs/guides/plugin_file_type_guide/src/plugin/georss/georssdescriptor.js

docs(rtd): fix build errors in createFromConfig()

---

src/os/ui/text/tuieditor.js

tuieditor.js had an issue whereby the editor box would not load properly in certain situations. It appears to be speed-sensitive. This may be due to a change in Codemirror. Issue required a one-line fix.

fix(tuieditor): speed-sensitive loading bug

---

scss/os/_utils.scss

Trivial fix from stylelint work - see #840

style(css): remove stray semicolon

---

src/os/config/displaysettings.js
views/config/displaysettings.html

Addition to fog display settings to hide the menu items if fog is unsupported

feat(fog): fog menu items can be hidden via support setting

---

docs/cookbook/overview.rst
docs/cookbook/pluginindex/index.rst

This tries to capture some very useful advice provided by Kevin Schmidt.

docs: add cookbook example for external scripts

---

src/os/action/eventtype.js
src/os/data/histo/colormodel.js
src/os/data/histo/histogramutils.js
src/os/data/histo/sourcehistogram.js
src/os/feature/feature.js
src/os/metrics/metricskeys.js
src/os/source/vectorsource.js
src/os/ui/menu/featuremenu.js
src/os/ui/menu/listmenu.js
src/plugin/track/trackmenu.js

Supporting code for "Color Selected" and "Color Selected Bins" features

feat: Color Selected

---

externs/pluralize.externs.js
index.js
package.json
src/os/search/abstractsearch.js
src/os/search/isubsearch.js
src/os/search/search.js
src/os/search/searchfacetdepartment.js
src/os/search/subsearchutils.js
src/os/string/pluralize.js
src/os/ui/search/searchbox.js
test/os/search/subsearchtutils.test.js

Add support for search sub-categories and pluralize directive
UUOM-627

WIP: feat(search): make sub search more generic

---

src/os/state/basestatemanager.js
src/os/ui/dragdrop/urldragdrop.js
src/os/ui/file/exportmanager.js
test/os/ui/file/exportmanager.test.js

Export of different state types and which persistence methods are
available can be controlled via a setting.

feat(export): adds settings to control enabled export features

---

scss/os/_utils.scss

Adds border color on hover
Creates a new class u-bg-body-inset. This is to be used when an item needs to appear farther back in the page

style(utils): updates u-bg-body-offset to a new color scheme

---

src/os/query/basequerymanager.js
src/os/ui/query/queryhandler.js
src/plugin/arc/query/arcqueryhandler.js

~~BREAKING CHANGE: added a param to queryhandler's createfilter function~~
Worked around the part that was breaking

feat: allow custom wfs queries to be built from an existing request

---

src/os/layer/vector.js
src/os/source/vectorsource.js
src/os/ui/menu/listmenu.js
test/os/source/vectorsource.test.js

Added support for manual coloring and resetting for Layer, and List tools

feat(colors): increased support for manual coloring

---

src/os/net/request.js

feat(request): add status code enum to aid error handling

---

src/os/source/vectorsource.js
src/plugin/cesium/sync/vectorsynchronizer.js

Testing: animate items in 3D mode

perf(vector): use the arrays directly, since that is faster

---

config/settings.json
src/os/config/displaysettings.js
src/os/ogc/ogc.js
src/os/webgl/abstractwebglrenderer.js
src/os/webgl/iwebglrenderer.js
src/plugin/cesium/cesiumrenderer.js
src/plugin/ogc/ogcplugin.js
test/os/source/vectorsource.test.js
views/config/displaysettings.html

BREAKING CHANGE: adds methods to IWebGLRenderer to support getting and
setting the max feature count for that renderer.

feat(feature-limit): adds settings UI for changing max feature counts

---

src/os/geom/ellipse.js
src/plugin/cesium/sync/featureconverter.js

Adds a constant for referring to geometry type 'ellipse'

feat(ellipse): add const string for ellipse geom type

---

package.json

locked to 3.4.1 while we investigate what's wrong with 3.5.0

fix(jquery): 3.4.1 lock

---

src/plugin/config/configprovider.js

chore: minor code cleanups on config Provider

---

src/os/query/basequerymanager.js
src/os/time/timelinecontroller.js

This keeps a couple specific functions on the prototype during compilation

feat(timeline): keep timeline function call on the prototype

---

src/os/interaction/dragboxinteraction.js
src/os/olm/render/box.js
src/os/state/v4/queryareastate.js
src/os/ui/ol/interaction/dragboxinteraction.js
src/os/ui/ol/interaction/drawpolygoninteraction.js
src/os/ui/query/abstractqueryreader.js
src/os/ui/query/area/userarea.js
src/plugin/cesium/interaction/cesiumdragboxinteraction.js
src/plugin/ogc/query/ogcspatialformatter.js
src/plugin/places/placessource.js
views/geo/position.html
views/query/area/userarea.html

Adds support for boxes that wrap the earth in both 2D and 3D mode. This updates the drawing control to allow it, and also fixes some issues with queries/geometries that cross the antimeridian. A future PR will update the Enter Coordinates dialog.

Feat wrapping boxes

---

src/os/ui/draw/basedrawcontrols.js
views/im/basicinfo.html

feat(cleanup): fix tooltip and extra scrollbar

---

src/os/alert/alertevent.js
src/os/alert/alertmanager.js
src/os/ui/alert/alertbadge.js
src/os/ui/alert/alertpopup.js
src/os/ui/alerts.js
test/os/alert/alertevent.test.js
test/os/alert/alertmanager.test.js
test/os/search/searchmanager.test.js
views/alert/alertpopup.html
views/windows/alerts.html

feat(alerts): throttle duplicated alerts

---

views/config/settingswindow.html

feat(reset): update Reset button nameA

---

src/os/alert/alertmanager.js

Fixes error introduced in #971.

fix(alert): fix error when calling sendAlertOnce

---

scss/os/_mixins.scss
scss/os/_utils.scss
scss/standard/_bootswatch.scss
src/os/ui/alert/alertlinkfilter.js

Converted div/span/a tags that used "u-link-style" to button tags that use "btn btn-link".

improvement(u-link-style): converted u-link-style tags to btn btn-link

---

config/settings.json
src/plugin/storage/persistplugin.js

Added config to show a link in the persistent storage alert pop-ups.

chore(storage): show help link in persistent storage warnings

---

src/os/config/displaysettings.js
src/os/mapcontainer.js

Settings cleanup, there is no needs to JSON-ify settings to save them, that should be done internal to each storage mechanism if necessary. I verified that state files save and load correctly.

fix(settings): no need to JSON stringify settings

---

src/os/state/basestatemanager.js
src/os/state/v2/layerstate.js
src/os/state/v3/layerstate.js
src/os/state/v4/baselayerstate.js

Improved logging of error conditions. Created utility function for boolean switch on isPersistable(); Updated logic in getPersistable() to log and failover in the recoverable state and log for non-recoverable state

feat(statemanager): handle nulls, non-constructables

---

externs/os.externs.js
externs/plugin.externs.js
src/os/data/registry.js
src/os/data/registryproperychange.js
src/os/mainctrl.js
src/os/metrics/metricskeys.js
src/os/ogc/ogcservice.js
src/os/ogc/query/ogcquery.js
src/os/ogc/registry.js
src/os/ogc/services.js
src/os/query/query.js
src/os/ui/draw/basedrawcontrols.js
src/os/ui/draw/drawevent.js
src/os/ui/draw/drawpicker.js
src/os/ui/menu/drawmenu.js
src/os/ui/ogc/ogclistui.js
src/os/ui/ogc/ogcserver.js
src/plugin/areadata/areadata.js
src/plugin/areadata/areadataplugin.js
test/os/data/registry.test.js
test/os/ogc/ogcservice.test.js
test/os/ogc/query/ogcquery.test.js
views/ogc/ogclist.html

Created a Registry and the base classes for dynamically configuring and using any number of OGC Feature Layers. Default UI is a pop-up dialog with a dropdown and look-ahead text filter.
Testing Steps:
This cannot be tested with OS default configs.

feat(areas): Created generics for handling any OGC FeatureLayer

---

externs/d3-3.4.1.js
externs/moment.js
test/os/net/requesthandlerfactory.test.js

The moment externs had a couple functions that needed optional params
I disabled some linter errors and cleaned up some urls while I was in there

Externs cleanup for moment, D3

---

src/os/state/abstractstate.js
src/os/state/basestatemanager.js
src/os/state/istate.js
src/os/state/state.js
src/os/state/statemanager.js
src/os/ui/state/abstractstateform.js
src/os/ui/state/stateexport.js
src/os/ui/state/stateimport.js
views/window/stateimportexport.html

refactor(import/export): added tip for unsupported features

refactor(import/export): changes the ui to show unsupported states

---

src/os/source/vectorsource.js

Reverts ngageoint/opensphere#1025

Revert "feat(vector): speed up processing of feature removal"

---

src/os/layer/preset/layerpresetmanager.js

Presets support a `default` option to automatically apply that preset when loaded. That isn't currently exposed in a convenient way, so this PR adds a `applyDefaultPresets` option that can be provided in layer config. As layers are added to the map, default presets will be applied if this flag is set in the layer options.

feat(preset): configure layers to automatically apply default presets

---

.jscodeshift.json

Added some more globals to the jscodeshift file based on issues I ran into while converting plugin code.

chore(es6): added more globals to be used when running jscodeshift

---

src/os/layer/preset/abstractpresetservice.js
src/os/layer/preset/ipresetservice.js
src/os/layer/preset/layerpresetmanager.js
src/os/layer/preset/preset.js
src/os/layer/preset/presetmenubutton.js
src/os/layer/preset/settingspresetservice.js
src/os/ui/layer/vectorlayerui.js

Improved UX. Integrated calls to PresetServices to Publish/Make Default/Delete.

feat(presets): Implement Publish/Make Default/Delete

---

src/os/ogc/filter/ogcspatialformatter.js
src/os/ogc/spatial.js
src/os/ui/query/basicqueryreader.js
test/os/ui/query/basicquery.xml
test/os/ui/query/basicqueryreader.test.js

feat(areas): save the id on the area so they can be ordered consistently

---

src/os/ol/control/mousepositioncontrol.js

Code that shows the terrain elevation under mouse cursor.

Mouse elevation

---

package.json

Removes references to the packages

test(cypress): disables cypress

---

src/os/ui/filter/op/equaltoop.js
src/os/ui/filter/op/inlistop.js
src/os/ui/filter/op/islikeop.js
src/os/ui/filter/op/likelistop.js
src/os/ui/filter/op/notequaltoop.js
src/os/ui/filter/op/notop.js
src/os/ui/filter/op/op.js
views/filter/expression.html

Added popovers and placeholders to text-based Filters to improve understanding which which Filter types have case-sensitivity and wildcard support.

feat(filters): improve help text

---

src/os/ui/slick/slickgrid.js

chore: remove dead code in slickgrid

---

externs/tui-editor.externs.js
index.js
package.json
scss/os/_overrides_tuieditor.scss
src/os/ui/text/tuieditor.js
src/os/ui/text/tuieditorlang.js
vendor-min.js

Upgrade Toast UI from v1.4.6 to v2.5.X and make necessary changes to how we alter the settings and extract values out of the Toast Editor.

feat(toastui): upgrade toast ui and integration

---

src/os/ex/export.js
src/os/mainctrl.js
src/os/ui/areas.js
src/os/ui/ex/addexportoptionsui.js
src/os/ui/ex/areaexportdialog.js
src/os/ui/file/exportdialog.js
src/plugin/file/kml/ui/kmltreeexportui.js
src/plugin/places/ui/placesui.js
views/areas.html
views/file/addexportoptions.html
views/file/exportdialog.html
views/plugin/kml/kmltreeexport.html

Creates an optional dialog for additional export options for both export dialog and kml tree export. Allows the user to export all, selected, or active data.

fix(export): add options for area and places

---

externs/tui-editor.externs.js
src/os/ui/text/tuieditor.js

Using this as a starting point:
https://nhn.github.io/tui.editor/latest/tutorial-example10-editor-with-color-syntax-plugin

feat(toastui): add support for optional plugins

---

addlayer.js

@schmidtk 
Per our email exchange regarding parameter for addlayer.

feat: added optional parameter to addlayer

---

addlayer.js

Cherry-pick from 8724bb366b7a3b9889539717aaa87a9c7be11b6e into /release

fix(addlayer): added optional parameter to addlayer

---

src/os/ex/export.js
src/os/ui/ex/addexportoptionsui.js
src/os/ui/file/exportdialog.js

Fixes Export and Export Places errors reported in [this comment](https://github.com/ngageoint/opensphere/pull/1121#issuecomment-765393158). There should be no console errors when launching these UI's, and Export should work again.

fix(export): fix errors in export UI's

---

scss/os/_overrides_tuieditor.scss

Fix a color issue with table text, primarily in dark mode.

fix(toastui): table text colors get theme colors

---

src/os/annotation/abstractannotationctrl.js

Annotation box on places had icons wrapped around internal elements.

fix(annotation): close i tags

---

views/capture/recordingui.html

This is a new rule added by `html-validate` in a [recent release](https://html-validate.org/changelog/index.html).

fix(capture): fix attr-spacing lint error

---

scss/os/_overrides_tuieditor.scss

Fix a minor z-index problem introduced by the recent toastui version upgrade.

fix(toastui): css fix

---

src/os/ui/ogc/ogcserver.js

This now resolves any relative service URLs provided for `GetMap`, `GetFeature`, etc. against the original URI for the `GetCapabilities` document. As far as I can tell, this behavior is not documented by any of the specs. However, this seems to me to be the most sensible default.
Previously, if a `GetCapabilities` document had a service with an operation like the following:
```xml
<ows:Operation name="GetFeature">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="/geoserver/wfs"/>
<ows:Post xlink:href="/geoserver/wfs"/>
</ows:HTTP>
...
```
Then we would request `${opensphereDomain}/geoserver/wfs`, which will generally fail.

fix: resolve relative service URLs properly

---

views/window/dockedwindow.html

cherry-pick 58ff57358ad0add04dab99ccf45809f184968e91 onto release

fix(window): add button role to indicate the element is interactive

---

src/plugin/capture/captureplugin.js

Adds a missing provide to the capture plugin.

fix(capture): add missing provide

---

karma.conf.js
test/os/ui/text/text.test.js
test/os/ui/text/tuieditor.test.js
test/os/ui/text/tuieditorlang.test.js

Add some quick tests for the upgraded tuieditor.

test(tuieditor): beginning test coverage

---

views/layers.html

This was causing the tree to fail to update in some cases, like when adding/removing a Place.

fix(layers): removes unnecessary no-root tag from layertree

---

src/os/ui/menu/unitmenu.js
src/os/ui/scaleline.js

Change for better ES6 module compatibility.

refactor: add menu.unit.MENU; deprecate menu.UNIT

---

src/os/ui/layer/vectorlayerui.js
src/plugin/file/kml/kmlnodelayerui.js
views/layer/labelcontrols.html
views/plugin/kml/kmlnodelayerui.html

Track labels' font size, font color, and show/hide enabled for editing multiples at once
GEOVIZ-526

feat(tracks): edit multiple track labels simultaneously

---

src/os/im/action/importactionmanager.js

This will force feature actions to do what we would usually expect them to be doing by default, by explicitly unprocessing items before processing the new ones.

Clear Layer Feature Actions before Applying a Preset

---

externs/jschardet.externs.js
index.js
package.json
src/os/ui/abstractmainctrl.js
src/polyfill/chardetng.js

This fixes file import in environments without Web Assembly.

fix: polyfill chardetng-wasm with jschardet

---

src/os/ui/ol/interaction/contextmenuinteraction.js
src/plugin/track/trackinteraction.js
src/plugin/track/trackmanager.js
src/plugin/track/trackmenu.js

begin the TrackInteraction as soon as user clicks the MenuItem

feat(trackpredict): initiate TrackInteraction automatically

---

src/os/capture/abstractrecorder.js
src/os/capture/abstractvideoencoder.js
src/os/capture/capture.js
src/os/capture/captureeventtype.js
src/os/capture/contenttype.js
src/os/capture/gifcapture.js
src/os/capture/gifencoder.js
src/os/capture/gifeventtype.js
src/os/capture/irecorder.js
src/os/capture/ivideoencoder.js
src/os/capture/timelinerecorder.js
src/os/ui/capture/abstractcaptureplugin.js
src/os/ui/capture/canvasrenderer.js
src/os/ui/capture/elementrenderer.js
src/os/ui/capture/htmlrenderer.js
src/os/ui/capture/recordingui.js
src/os/ui/capture/svgrenderer.js
src/os/ui/capture/timelinerenderer.js
src/os/ui/menu/savemenu.js
src/plugin/capture/annotationtailrenderer.js
src/plugin/capture/capture.js
src/plugin/capture/captureplugin.js
src/plugin/capture/legendrenderer.js
src/plugin/capture/mapoverlayrenderer.js
src/plugin/capture/mapoverviewrenderer.js
src/plugin/capture/maprenderer.js
src/plugin/capture/timelinerecorder.js

Transforms the capture plugin and the OS capture stack (`os.capture` and `os.ui.capture`) to use `goog.module`.

Transform capture stack to goog.module

---

scss/os/_overrides_bootstrap.scss
scss/os/_overrides_jqueryui.scss
scss/os/_slicktree.scss
src/os/ui/search/searchbox.js
views/search/searchbox.html

Fixing bugs with checkbox icon in other repos, updating checkbox to use proper new modifier and for consistency sake.

chore(fa): updates to checkbox icon after fa5 upgrade

---

package.json

Temporary fix only for release builds

build(linthtml): disable html linting for release branch

---

views/layers.html
views/plugin/places/places.html

Update the color of "Add Folder" buttons in opensphere to be `btn-primary` instead of `btn-success`

fix(addfolder): update button color

---

config/settings.json
src/os/im/mapping/bearingmapping.js
src/os/im/mapping/orientationmapping.js
src/os/im/mapping/radiusmapping.js
src/os/im/mapping/renamemapping.js
src/os/im/mapping/semimajormapping.js
src/os/im/mapping/semiminormapping.js
src/os/ui/layer/columnsuggestionselect.js
src/os/ui/layer/ellipsecolumns.js
src/os/ui/layer/vectorstylecontrols.js
views/layer/ellipsecolumns.html
views/layer/vectorstylecontrols.html

- feat: "Suggested Columns" optgroup for ellipse column selections (csv import, etc.)
- feat: created a directive to help with suggested columns / other situations that call for dynamic optgroups from separate lists
- fix: resolve logic / naming issues in ellipse column directive
- refactor: goog.module conversions for some import mapping types

feat: test ellipse configuration columns for config-based suggestions

---

src/os/style/circlereader.js

The Cesium synchronizer reads point feature opacity off of the associated circle style directly with `getOpacity()`, but the opacity was never being set on the style. This sets that opacity directly so it can be used by the synchronizer and anything else that might want it.

fix(style): sets opacity properly on circle styles

---

views/layer/labelcontrols.html

Fixes vector labels not being sortable.

fix(labels): fix sortable initialization

---

src/os/data/drawinglayernode.js
src/os/layer/vector.js

Fixes a bad type check for the source on the drawing layer and an incorrect class registration for the layer node.

fix(menu): fixes drawing layer/node menu bugs

---

src/os/ui/ol/interaction/drawpolygoninteraction.js

Addresses a few remaining quirks with polygon draw such that:
- Shift+click+drag always draws, whether starting a new polygon or continuing an existing one.
- Click+drag always pans the map/globe, whether currently drawing or not (ie, when the draw was activated by clicking the button).
- Shift+click always adds a coordinate, whether starting a new polygon or continuing an existing one.
- Click always adds a coordinate if the drawing has been started.

fix(draw): clean up draw polygon behavior

---

src/os/ui/draw/basedrawcontrols.js
src/os/ui/draw/drawcontrols.js
src/os/ui/ol/interaction/abstractdraginteraction.js

fix: only one draw/measure interaction will be active at a time

---

.github/workflows/build.yml

build(github): build within recommended yarn workspace

---

package.json

This changed in cleancss 5.x, which was recently upgraded.

fix(css): use cleancss --with-rebase to rewrite urls again
