ngageoint/opensphere

src/os/metrics/metrics.js
src/os/net/parammodifier.js
src/os/olcs/sync/featureconverter.js
src/os/query/temporalquerymanager.js
src/os/search/favorite.js
src/os/source/source.js
src/os/source/vectorsource.js
src/os/state/v2/layerstate.js
src/os/state/v3/layerstate.js
src/os/state/v4/baselayerstate.js
src/os/string/string.js
src/os/style/label.js
src/os/ui/descriptioninfo.js
src/os/ui/featureinfo.js
src/os/ui/file/kml/abstractkmlexporter.js
src/os/ui/filter/filter.js
src/os/ui/query/queryhandler.js
src/os/ui/text/text.js
src/os/xml.js
src/plugin/file/csv/csvparser.js
src/plugin/file/shp/shpexporter.js

Straight substitution of equivalent code, per https://github.com/google/closure-library/blob/master/closure/goog/string/string.js#L182

refactor(src): Remove deprecated goog.string.isEmpty/isEmptySafe.

---

package.json

Disable the `missingOverride` compiler check until #32 is worked.

Disable missingOverride warning until warnings are handled.

---

scss/os/partials/_tree.scss
scss/ui/partials/_tristate.scss

These seemed reasonably well justified, and the change is only to match previous scss-lint suppressions.

Suppress sass-lint warnings, as for scss-lint

---

karma.conf.js
package.json
test/os/histo/datebinmethod.test.js
test/os/state/v2/timestate.test.js
test/os/state/v4/timestate.test.js

Update moment to resolve CVE-2016-4055 vulnerability. The update broke some tests due to the strict flag being enforced more carefully. Date values in the tests were previously invalid but still passed due to the looser format validation, and have been corrected.
The Karma config change fixes filtering of test files, so developers can once again change which files are included while debugging tests.
Fixes #43.

Update moment to 2.20.1.

---

src/os/data/columndefinition.js
src/os/parse/baseparserconfig.js
src/os/parse/icolumndefinition.js
src/os/source/source.js
src/os/ui/column/columnmanager.js

There was an inferred union type here `{Array<!(ColumnDefinition\|FeatureTypeColumn)>}` that the compiler is not detecting as a mismatch with the declared type. I opened https://github.com/google/closure-compiler/issues/2783 with the compiler. This issue was causing filters programmatically created from histogram bins to fail.
I also removed a superfluous, empty interface.

fix(source): fix mismatched return type

---

src/os/command/transformvectorscmd.js
src/os/geo/jsts.js
src/os/query/query.js
src/os/ui/buffer/bufferform.js

`os.geo.jsts.getSplitOffset` only needed the geometry's extent. Extents are much cheaper to transform (and aren't done in-place), so I changed the first parameter to that. This made testing buffer form parameters work in other projections at little computational expense.
Found/fixed a second problem while testing buffering in projections other than EPSG:4326. `os.query.isWorldQuery` does not work in other projections because the whole world geometry is always in 4326. In 3857, basically every geometry returns true from that function and the coordinates are changed in the geometry. Fixed the function to test geometry area in the correct projection. 
Third bug fixed here is that any features with the same geometry/original geometry (those that aren't interpolated, like the whole world area) …

Fix inner buffer and world query in non-EPSG:4326 projections

---

src/os/config/namespace.js
src/os/config/settings.js
src/os/xt/peer.js

Closure deprecated `goog.structs.Set`, so we should replace it to fix those warnings. The two places using it are not expected to be called often or with large sets, so an Array with `goog.array.insert` to de-duplicate values should be fine.

Replace deprecated goog.structs.Set.

---

index.js
src/electron/electronvendorpost.js
src/electron/electronvendorpre.js

This adds scripts that run before/after vendor library loading to fix a few issues running inside an Electron container:
- jQuery cannot load because Electron registers `window.module`.
- The Fetch API cannot be used with the `file` protocol by default.

Support Electron

---

src/os/ui/featureedit.js

When editing a place, the original geometry was being translated to lon/lat. If the edit was cancelled, the original geometry was restored to the feature without transforming it back. This moved the geometry in projections other than EPSG:4326.

Don't change the original feature geometry.

---

docs/guides/plugin_server_guide/parsing.rst
docs/guides/plugin_server_guide/provider.rst
docs/guides/plugin_server_guide/src/plugin/tileserver/tileserver.js-provider

The guides are important (so want to be close to the top), but they need more introduction. 
The `json` -> `layers` change is just so you don't have to change that line later to match.

docs(rtd): Minor guide cleanups.

---

src/os/mixin/layerbasemixin.js

This fixes attributions not showing in 3D mode.

fix(layer): override visibleAtResolution to work when Cesium is up

---

.travis.yml

This is an attempt to speed up dependency install and bypass the inexplicable `npm ls` errors in Travis.

ci(travis): use yarn in build

---

docs/cookbook/osm/index.rst
src/os/layer/config/abstracttilelayerconfig.js
test/os/layer/config/abstractlayerconfig.test.js
test/os/layer/config/abstracttilelayerconfig.test.js
test/os/layer/layer.mock.js
test/plugin/ogc/xyz/xyzlayerconfig.test.js

Includes updates to OSM cookbook docs.
Resolves #86.

fix(xyz): Add support for URLs containing server ranges.

---

src/plugin/featureaction/ui/editfeatureaction.js

Also rename the handler method to reflect the actual change we're listening for.
Resolves #105

fix(build): Add missing @this annotation to silence build warnings.

---

scss/ui/partials/ui/onboarding/_ngonboarding.scss

Fix some of the sass-lint noise about colour formats.
I personally would have preferred long format, but most of OS uses short formats (switching requires ~335 changes, vs the ~10 changes here).

chore(sass): Replace long form colours with short form where possible.

---

scss/os/overrides/_bootstrap.scss
scss/ui/partials/_misc.scss

This includes some minor cleanups to make the animations more readable, which unfortunately increases the complaints about `translateY` casing (`Mixin 'translateY' should be written in lowercase with hyphens  mixin-name-format`).

chore(sass-lint): Fix selectors single-line warnings.

---

src/os/control/attribution.js
src/os/mixin/layerbasemixin.js

This prevents rendering 2D vector canvases while 3D mode is active.
Fixes #129.

fix(attributions): Show attributions in 3D mode.

---

src/os/geo/geo.js

We should also consider deprecating `os.geo.interpolateCircle` as anything using that should be using `os.geo.interpolateEllipse` instead.

docs(geo): fix incorrect docs

---

test/os/geo/geo.test.js

I originally wrote these for my own normalisation function, before discovering the one in [os.geo](https://github.com/ngageoint/opensphere/blob/master/src/os/geo/geo.js#L1791).

chore(tests): Add tests for os.geo.normalizeLongitude_().

---

test/os/state/v2/queryentriesstate.test.js

This is a blind fix, trying to overcome occasional 2 != 3 results.

fix(test): Try to make QueryEntriesState test more robust.

---

src/plugin/capture/mapoverlayrenderer.js

The `MapOverlayRenderer` was not properly sizing and positioning on high DPI displays such as Apple Retina devices. The pixel ratio is now calculated from the canvas and its bounding client rect and used in those calculations.
Resolves #124

fix(capture): fixed position/size errors on high DPI displays

---

package.json

Jasmine comes bundled with [karma-jasmine](https://github.com/karma-runner/karma-jasmine) 0.1.0, and our dependency on `jasmine-core` is both unused and misleading (we're not using Jasmine 2). Removing it.

chore(deps): Remove unused dependency on jasmine-core.

---

externs/closure-compiler.js
src/os/file/file.js
src/os/mainctrl.js
src/os/map/mapinteractions.js
src/os/net/extdomainhandler.js
src/os/net/localfilehandler.js
src/os/net/samedomainhandler.js
src/os/state/v4/baselayerstate.js
src/os/ui/abstractmainctrl.js
src/os/ui/file/fileimport.js
src/os/ui/file/filexthandler.js
src/os/ui/file/importdialog.js
src/os/ui/im/audioimportui.js
src/plugin/params/params.js
test/os/file/file.test.js

Electron [adds a `path` property](https://electronjs.org/docs/api/file-object) to the File API to expose the file system path. This PR detects that and loads the file directly from the file system. The file is treated as a remote URL so it will not be added to file storage. Support for `file://` URL's is disabled by default, and can be enabled by setting `fileUrls` to `true` in the app configuration.
Layers with `file://` URL's will always be ignored when creating state files and by request URL parameter edit. They _can_ be imported into the audio manager.

feat(electron): Support file:// URL's in Electron.

---

conformance_config.textproto
src/os/tag/tag.js
src/os/ui/filter/filter.js
src/os/ui/filter/filterfn.js
src/os/ui/text/simplemde.js
src/os/xml.js
src/plugin/arc/state/v2/arcstate.js
src/plugin/file/kml/kmlparser.js

The Closure functions fail when parsing multi-line XML with CDATA to denote the value. For example, the following would be parsed as whitespace:
```
<name>
<![CDATA[Some Value]]>
</name>
```
This caused problems reading values from formatted KML files, but these are resolved by using `ol.xml.getAllTextContent` instead. This function is also guaranteed to return a string, so I streamlined some following `trim` calls as well.

Stop using goog.dom.getTextContent and getRawTextContent.

---

src/os/unit/baseunit.js
test/os/unit/unitmanager.test.js

For example, 0 in metres is 0.00 m, not 0.00 cm
Resolves #173.

fix(units): Show 0 in base units

---

test/plugin/file/kml/tour/tour.test.js

Fixes an occasional error in the tour test if the `waitsFor` runs between the index increment and starting the next item.

Fix race condition in tour test.

---

src/os/feature/feature.js
src/os/source/vectorsource.js
src/os/ui/file/kml/abstractkmlexporter.js
src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlparser.js
src/plugin/track/track.js
src/plugin/track/trackmenu.js
test/plugin/file/kml/kml.test.js

This adds support for parsing both KML 2.2 and 2.3 Track and MultiTrack elements into a `os.feature.DynamicFeature` that can be animated via the timeline.
Other changes:
* `plugin.track.createTrack` API was changed to take an options argument, instead of the old parameter train. Choo choo!
* `plugin.track.addToTrack` was renamed to `plugin.track.addFeaturesToTrack` for clarity.
* Tracks will now use `ol.geom.LineString` if possible (not a multi-track, and doesn't cross the date line) as a performance enhancement. This is particularly useful for 3D mode, since our feature converter recreates all line primitives representing a multi-line on each update. #135 will address the greater issue.

Add KML track support

---

src/os/feature/feature.js

I came across `goog.reflect.objectProperty` today, which returns the actual property name for an object property. In debug mode, the function just returns the provided property string. The compiler will replace the function call with a static string for the compiled property name. This replaces the hack used to find the `ol.Feature#values_` property for client-side filter creation.

Replace hack to get compiled values_ property

---

src/os/control/mapmodecontrol.js
src/os/map/map.js
src/os/mapcontainer.js
src/os/olcs/olcs.js

I noticed two problems with the async Cesium load:
- On slow connections or in debug mode when loading unminified Cesium, the 5 second timeout for `goog.net.jsloader` can be reached.
- It's unclear to the user that something is happening, other than the map going black.
To resolve these, I made the following changes:
- Show a loading spinner with updated tooltip on the map mode control while Cesium is being loaded/initialized.
- Hide the Openlayers canvas when initializing 3D mode on app startup. It seemed odd to show the 2D map then switch to 3D when the user hadn't done anything yet.
- Don't hide the Openlayers canvas during initialization if user toggled. The loading spinner provides feedback that their button click did something and we're working on it, and avoids displaying a blank …

Inform the user when WebGL is being initialized.

---

scss/ui/partials/ui/onboarding/_ngonboarding.scss

Chrome 35 is a supported browser, and `translate` isn't available (without prefix) until 36, so that stays for now.
Part of the work for #141

chore(css): Remove vendor prefix for translate and transition.

---

src/plugin/ogc/wms/wmslayerconfig.js

I was working with a provider who uses all caps in WMS spec params (`SERVICE`, `VERSION`, etc.) and all lower case in non-spec proprietary params (`provider`, `query`, etc.). So I added a `caseSensitive` option that prevents the WMS layer config from assuming that all the parameters can be upper-cased.
EDIT:
I should probably note that this is a little janky. The underlying `ol.source.TileWMS` class will still attempt to bake in the default parameters in upper case. So you can't add case-sensitive parameters for `SERVICE`, `VERSION`, `REQUEST`, `FORMAT`, `TRANSPARENT`, `WIDTH`, `HEIGHT`, `STYLES`, `CRS` (`SRS` for 1.1.1), or `BBOX`. However, anything else will be preserved as sent in the param options.

feat(wms): Added caseSensitive option for params

---

src/os/ui/menu/menu.js

The new menu API does not have a way to update the menu if items in it would change. This adds a simple `reopen` call that will close and open the menu in the same position, which will call `beforeRender` again to update each menu item.

Allow reopening a menu to re-render items.

---

src/os/layer/config/abstracttilelayerconfig.js
src/os/proj/proj.js
test/os/proj/proj.test.js

Also added tests and fixed an issue where we would just give up with the application projection if no supported projection was found rather than throwing an error.

feat(proj): moved best projection detection logic to public place

---

src/os/ui/menu/menu.js
src/os/ui/menu/menuitem.js

Other changes:
- Prevent firing open/close events when reopening a menu to refresh the content.
- Clean up `goog.isDef` in support of #165.

Allow leaving the menu open when an item is selected.

---

src/os/layer/config/abstracttilelayerconfig.js
src/os/mixin/tileimagemixin.js
src/os/tileclass.js
src/plugin/arc/layer/arctilelayerconfig.js
src/plugin/basemap/basemapconfig.js
src/plugin/ogc/wms/wmslayerconfig.js

Moved the misnamed `tileClass` to `layerClass` and added `tileClass` for actually setting the tile class on the source.
BREAKING CHANGE: `confg['tileClass']` -> `config['layerClass']`

feat(tilelayer): added support for setting the tile class

---

scss/os/overrides/_bootstrap.scss
scss/os/partials/_main.scss
scss/ui/overrides/_slickgrid.scss
scss/ui/partials/_misc.scss
scss/ui/partials/ui/_colorpalette.scss
scss/ui/partials/ui/_filter.scss
scss/ui/partials/ui/column/_columnmanager.scss
scss/ui/partials/ui/help/_control.scss
scss/ui/partials/ui/onboarding/_ngonboarding.scss

We used them in many places, but not all.
To check this, I compared resulting `combined.css` build results, with the following diff:
```
@@ -9515,12 +9515,14 @@
}
.slick-grid.editable .slick-cell.editable input.editor-text {
+  -webkit-box-shadow: none;
+  -moz-box-shadow: none;
+  box-shadow: none;
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
box-sizing: border-box;
background: transparent;
border: 0;
-  box-shadow: none;
height: 100%;
width: 100%;
}
@@ -10969,8 +10971,10 @@
-moz-transition: border 500ms ease;
-o-transition: border 500ms ease;
transition: border 500ms ease;
-  border-color: #72b2ff;
+  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);
+  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, …
```

chore(css): Switch box-shadow to use compass mixins.

---

src/os/source/vectorsource.js
test/os/source/vectorsource.test.js

Features without an id will run into a few issues, namely that they won't be converted/rendered to Cesium. This ensures all features added to an OS vector source have an id.

Ensure features in os.source.Vector have an id.

---

externs/Cesium.externs.js
src/os/mixin/cesiummixin.js

Note that this does not fully replace Cesium's request stack, but merely only the portions that we are using. We already have a replacement for image loads such as tiles and icons. This allows terrain (loaded as JSON) to follow a similar path.
Pros:
- Terrain requests and other local JSON loads from Cesium no longer need to do the extra one-off of adding third party domains to the `TrustedServers` class in Cesium, as that will be taken care of by the crossOrigin registry in `os.net`.
- Custom request handlers added by plugins will no longer be bypassed by requests originating from Cesium
Cons (maybe?):
- Not a full implementation of Cesium's request stack (most notably we are not doing anything with `options.request` and `RequestScheduler`)

feat(olcs): Cesium now uses our request stack

---

src/plugin/file/kml/ui/kmlnode.js

This fixes the node state if the visibility change comes from outside the node itself (such as the raster/vector toggle buttons)
resolves #241

fix(kml): Ground Overlay nodes should update on layer visibility change

---

src/os/ui/capture/canvasrenderer.js

I missed verifying the canvas was defined before making sure it was scaled correctly. This fixes capture when the legend/overview are closed.

fix(capture): Don't throw an exception when the canvas is null.

---

externs/os.externs.js
src/os/ui/ex/exportoptions.js
src/os/ui/state/statelist.js

This is more accurate, and allows removing some type casts.
These type casts hit a bug in [`recast`](https://github.com/benjamn/recast), which affects the Closure Library refactor. They're the only two lines that hit it, so I'm fixing them to avoid the problem.

Use a typedef instead of a class for osx.ChecklistItem

---

src/electron/electronvendorpre.js

Moved to support disabling `nodeIntegration` in the main BrowserWindow in Electron, per guidance in the [Electron security tutorial](https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content).
More details in ngageoint/opensphere-electron#2.

Move require to a preload script in opensphere-electron.

---

externs/os.externs.js

Fixes errors when building with external plugins that use `statelist.js`.

fix(externs): Allow osx.ChecklistItem values to be null.

---

docs/_static/css/overrides.css
docs/conf.py

The most recent updates to the Sphinx RTD Theme have an issue where the line highlight does not show up well against the code background.
This adds an `overrides.css` file that we can use for fixing that and other minor things like it.

docs(rtd): make line highlight show up better

---

src/os/mapcontainer.js

This was only occurring on Timeline close as far as I could tell. Browser resize and Timeline open were both redrawing correctly.

fix(cesium): Cesium was not redrawing on map resize

---

externs/Cesium.externs.js
src/plugin/cesium/mixin/cesiummixin.js

Cesium extensions to `Resource` tend to override `_makeRequest` rather than `fetch`. This move allows those items (like `IonResource`) to still have their extension logic run before the request is made, rather than being completely bypassed by mixing in at `fetch`.
You can test this with STK Terrain in Cesium.

fix(cesium): move override lower in Cesium stack

---

src/os/layer/tile.js

Go To is now enabled for Tile layers which have a reduceable extent which is contained by the overall projection extent and is less than 80% of the overall projection extent area.
... and it just occurred to me that this probably fails for extents crossing the anti-meridan.

feat(layer): GOTO is now supported for tile layers

---

src/os/layer/tile.js

Layers which have TileGrids with custom extents should use the TileGrid for the min/max resolution calculation so that everything matches up properly. Remember that the overall target in OpenLayers is `resolution` (projection units per pixel) rather than `zoom` (unit-less and nearly useless too).
GeoPackage and WMTS are both capable of setting the extent/origins like this.

fix(layer): calculate min/max resolution from tilegrid

---

src/plugin/cesium/tilegridtilingscheme.js

Cesium assumes that all levels (0 to maxZoom) exist. Therefore, if the TileGrid detected a zoom factor, attempt to extrapolate the correct value for num x/y tiles from the corresponding value from the minZoom via the zoom factor.
Potential layer types with discrete tile sets include GeoPackage and WMTS.
This ends up allowing Cesium to tile the level, but the checks that already exist in `plugin.cesium.ImageryProvider` ensure that it just uses a blank tile.

fix(cesium): fix for layers with discrete tile sets

---

src/os/data/layersyncdescriptor.js

This fixes descriptors not showing as enabled for layers automatically added during a projection switch (or any other process which relies on the descriptor enabling itself through layer listeners).

fix(data): keep layerIds populated permanently

---

src/os/ui/wiz/step/abstractwizardstep.js
src/os/ui/wiz/wizard.js

I think that all that was needed for this was just to check if config is null in the destroy function.
Resolves #263

fix(wizard): Checked for null case in destroy function

---

src/plugin/places/placesmanager.js

Prevents saving on feature visibility events fired from timeline changes.

fix(places): Only save places when features have changed.

---

src/os/file/file.js
test/os/file/file.test.js

Fixes drag and drop in Windows when running in Electron.

fix(file): Form file URI's correctly in Windows.

---

config/settings.json
docs/guides/settings_guide.rst
externs/Cesium.externs.js
src/os/config/displaysettings.js
src/os/webgl/abstractwebglrenderer.js
src/plugin/basemap/basemapprovider.js
src/plugin/cesium/cesium.js
src/plugin/cesium/cesiumrenderer.js

Removes default terrain config, instead providing instructions on configuring terrain in RTD.
Resolves #229.

feat(terrain): Support Cesium Ion terrain.

---

src/os/audio/audiomanager.js

BREAKING CHANGE: Code relying on the 'None' option from the audio manager will have to maintain that option locally.

refactor(audio): Remove 'None' from audio manager.

---

index.js

Fixes builds that do not use a Yarn workspace and can't resolve opensphere as a module.

build(index): Use local path instead of resolving self.

---

src/plugin/cesium/sync/imagesynchronizer.js
src/plugin/file/kml/kmlmenu.js
src/plugin/file/kml/kmlparser.js
src/plugin/file/kml/ui/kmlnode.js

This fixes a couple of bugs:
- Loading KMLs in 3D containing `GroundOverlay` was failing due to the `ImageSynchronizer` looking for the extent in the wrong place.
- Solution: don't fail on missing extent, and also get the extent from the correct location.
- A similar solution was added to `KMLNode.prototype.getExtent` when reading image layers so that Go To works properly for `GroundOverlay` items
- When parsing `GroundOverlay`, reproject the extent from `EPSG:4326` to the application extent so that we at least make an attempt at going to the correct location and showing the image. Note that this probably needs some follow-on work to make it obey the more strict reprojection rules we have in place for other layers.

fix(kml): miscellaneous ground overlay fixes

---

src/os/ui/spinner.js
src/plugin/basemap/ui/basemaplayerui.js

This fixes #302. You can now type a value into either spinner box to set the min/max zoom for the current layer(s). The change takes effect once the field looses focus. Values are clamped to the min and max for the field and non-numerical input is ignored.
Issues:
* "Current" buttons still set the layer zoom boundaries correctly but don't update the spinner's value anymore. This will need to be fixed but I'm not sure where I broke this binding.

fix(layerZoomSpinner): Fixed typing a value into a spinner's input

---

src/os/ui/help/controls.js
views/help/controls.html

Referencing #184 fixed some of the issues regarding the Controls UI returning empty strings for the mac  Meta key. Added .modal-body to the root element so the background is no longer transparent.

Fix Controls UI background and Missing Key Text

---

src/plugin/basemap/ui/basemaplayerui.js
views/plugin/basemap/basemaplayerui.html

* Replaced the hard coded min and max to use the constant already defined elsewhere
* Added extra `goog.require`s for extra needed requirements

fix(zoom): Replace hard coded map max/min with JS constant for zoom spinners

---

src/plugin/cesium/cesiumcamera.js

The Cesium camera `setHeading` call was ignoring the `heading` param, always setting heading to 0.

fix(cesium): Use provided heading in Cesium camera's setHeading.

---

externs/Cesium.externs.js
src/plugin/cesium/mixin/cesiummixin.js
src/plugin/cesium/mixin/renderloopmixin.js

The old ol-cesium render loop fired rendering when Cesium's request stack finished a request. This has been restored. Additionally, when the render loop is fired via a GL_REPAINT event, the loop continuously renders for a whole second at the target framerate rather than simply rendering once. This covers the async load of an icon and asynchronously loading it to the GPU.
This would be "less hacky" if there was an event when `BillBoard`s or other classes from cesium fired an event when their `ready` flag flips to `true`. I figured pulling back in some logic similar to the older `AutoRenderLoop` class from `ol-cesium` was preferable to polling that flag.

fix(cesium): fix some bugs in Cesium's explicit rendering

---

src/os/ui/query/ui/modifyarea.js
src/os/ui/window.js
src/plugin/file/kml/ui/kmlui.js

This causes saved windows with the same `id` to be cascaded. The cascade behavior was designed to mimic macOS:
- Find top-most like window and add x/y offset to that position.
- If the new window hits the right edge of the screen, change x position of new window to 0.
- If it hits the bottom edge of the screen, change y position of the new window to 0 (under the top bar).
In OpenSphere, this results in windows being positioned on top of the top nav because the window container contains the navs. This feels a little odd, but the best way to resolve that would be changing the window container to the map container. That seemed like a potentially unwanted change, and perhaps not fit for this PR.

Cascade windows with the same id

---

src/os/ui/query/cmd/areamodifycmd.js

If the original geometry is not removed, the interpolation will work off of that and overwrite the
new geometry.
I gave some thought to potentially making the JSTS operations work off the original geometry so that the resulting polygons could be simpler, but I believe that may affect its accuracy in some situations so I left it out.

fix(area): modify area command should remove original geometry

---

src/os/ui/slick/abstractgroupbytreesearchctrl.js

A fallback location is provided to grab the settings out of the old location if possible.
Fixes #312

fix(slick): Group Bys now save to a prefixed location

---

src/os/ui/ogc/ogcserver.js

Unless they are already defined on the config.
fixes #325
You can use https://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/mars/mars_simp_cyl.map&service=WMS&request=GetCapabilities for testing

fix(ogc): Get WMS/WFS custom params from the URL

---

src/os/layer/animatedtile.js
src/os/mainctrl.js
src/os/proj/proj.js
src/os/proj/projswitch.js
src/plugin/arc/layer/animatedarctilelayer.js
src/plugin/cesium/cesium.js
src/plugin/cesium/sync/tilesynchronizer.js
src/plugin/ogc/wms/wmslayerconfig.js
src/plugin/wmts/mime.js
src/plugin/wmts/wmts.js
src/plugin/wmts/wmtsimport.js
src/plugin/wmts/wmtslayerconfig.js
src/plugin/wmts/wmtsplugin.js
src/plugin/wmts/wmtsserver.js
test/os/layer/animatedtile.test.js

Adds support for WMTS servers, such as [NASA GIBS](https://earthdata.nasa.gov/about/science-system-description/eosdis-components/global-imagery-browse-services-gibs). Time dimensions are supported.
This also fixes a couple of issues with projection switching. When choosing the best projection for a layer, it must choose one enumerated for support by the server. This means that the layer can choose something like `urn:ogc:def:crs:OGC:1.3:CRS84`. However, the projection switch should change the overall map projection to `EPSG:4326`, since things like default map layers are done by string codes in settings.
-----------
Config:
```
"wmts-test": {
"type": "wmts",
"label": "NASA GIBS WMTS",
"url": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi"
}
```
For user added URLs, [use …

Add WMTS server support

---

src/os/ui/timeline/timeline.js

Accomodate UI's that dynamically resize the timeline, instead of only resizing on viewport change.
This also adds checks to ensure the timeline hasn't been destroyed, to avoid a (costly) try/catch statement during resize.

refactor(timeline): Resize on element size change.

---

src/plugin/cesium/sync/featureconverter.js

We previously used a label geometry field on features to indicate where to find the geometry used for label positioning, and would only show one label per feature. This does not work for measure lines, and also doesn't sync with how OpenLayers displays labels.
This PR changes the Cesium feature converter to sync all labels that would be rendered by OpenLayers, by retrieving the geometry from the style and rendering a label if the style has a text component.

Sync all label styles to Cesium.

---

src/os/extent.js
src/os/source/vectorsource.js

Load this as a file:
```
{
"type": "MultiPoint",
"coordinates": [[179, 0], [-179, 0]]
}
```
It should display properly. Now right-click the layer and select "Go To". It should behave sensibly.

fix(vector): RBush extents should not use assumptions for extent zoom

---

scss/os/_searchresults.scss
views/main.html

Search results should always occupy the full height of the map container, and scroll if they exceed the map container height.
Fixed with `top/bottom: 0` on the results panel, and an explicit `position: relative` on the map container.

Constrain search results within map container.

---

src/plugin/cesium/sync/featureconverter.js

Fixes an issue where label styles applied to a styled geometry were overriding the correct geometry color.

Assume text styles are only for rendering labels.

---

src/os/ui/menu/layermenu.js

Tooltip for Export was a copy/paste mistake for Go To. Fixed.

fix(layermenu): Updates tooltip to the correct text

---

src/os/ogc/wfs/describefeatureloader.js

This passes custom params set on the WFS server to the `DescribeFeatureType` call.

fix(wfs): use custom params in DescribeFeatureLoader

---

src/plugin/wmts/wmtsserver.js

OpenLayers throws an error if we pass it a matrix set whose projection is not defined in the
application. Therefore, prune the matrix sets down to just the projections that are supported.
Also fixed an issue where we were just using the first `Format` listed rather than preferring `image/png` when available.

fix(wmts): prune unsupported projections

---

src/os/file/mime/zip.js
src/os/parse/asynczipparser.js
src/plugin/area/kmlareaparser.js
src/plugin/file/kml/kmlparser.js
src/plugin/file/shp/shpparser.js
src/plugin/file/shp/ui/zipshpimportui.js

This fixes leaking zip workers each time they are used.
For each of these, you're going to open dev tools and watch the "Threads" count to ensure that zip workers are not leaked in addition to ensuring that the feature you're using is working properly.
* Mime stack
* Load zip files that are not supported layer types (not KMZ or zipped SHP)
* KMZ
* Load KMZ files
* Load KMZ files with external stylesheets in the zip
* Load KMZ files with external stylesheets that load as a KMZ
* Load KMZ files with network links that are KMZ files
* Import KMZ areas into the Areas tab
* SHP
* Load zipped SHP files
fixes #373

fix(zip): call close on all zip readers

---

src/os/geo/geo.js
src/os/im/mapping/radiusmapping.js
src/os/math/units.js
src/os/ui/wiz/geometrystep.js
src/os/unit/unitmanager.js
test/os/im/mapping/radiusmapping.test.js

When you import a csv file and set the ellipse geometry to have a radius, the unit conversion is a bit strange, this should fix it.
I also noticed that the radius conversion for yards was missing, so I added (affects altitude also)

fix(csv_import): Fix csv import ellipse radius incorrect units

---

src/os/data/configdescriptor.js
src/os/layer/animatedtile.js
src/os/layer/tile.js
src/os/mainctrl.js
src/os/string/string.js
src/os/ui/data/descriptorprovider.js
src/os/ui/ogc/ogcdescriptor.js
src/plugin/config/config.js
src/plugin/config/configplugin.js
src/plugin/config/configprovider.js
src/plugin/ogc/wfs/wfslayerconfig.js
test/os/data/configdescriptor.test.js
test/os/string/string.test.js

This allows admins to configure a provider and its layers completely through config.
Sample Config (For Electron. The KMLs do not support CORS well. Download and translate to local URLs to avoid that and test in a browser.)
```
{
"admin": {
"providers": {
"config-test-1": {
"type": "config",
"label": "Test Provider",
"description": "This is a test of the config provider PR",
"layers": {
"single-layer-test": {
"id": "features",
"type": "KML",
"title": "Single Layer Test",
"description": "Tests single layer configs by using the Google KML Samples file",
"url": "https://developers.google.com/kml/documentation/KML_Samples.kml",
"layerType": "Feature Layers"
},
"multi-layer-test": [{
"id": "tiles",
"type": "XYZ",
"title": "Layer Group Test",
"url": …
```

Add custom providers through config

---

src/os/ui/savedwindow.js
src/os/ui/window.js

Avoids unnecessary DOM queries that may happen very frequently. This was very apparent when looking at an animation CPU trace, where these window lookups were responsible for ~8% of the CPU usage. Fixed by maintaining a map of open windows by id (or key, for saved windows). Improves performance for both `os.ui.window.exists` and `os.ui.window.getById` without impacting the API.

Improve window lookup performance

---

src/os/ui/data/baseprovider.js

`StateProvider` and a few others were manually setting a label, then calling the parent `configure`. This would wipe out the label in `BaseProvider` if it wasn't set in config.

Only set label if defined in config.

---

src/plugin/file/kml/kmlsource.js

`KMLSource` keeps a map of node IDs to nodes. In the event that the KML is refreshed (or a portion of the tree is refreshed via a network link), nodes that were left out of the resulting merge by the `KMLParser` were already disposed but were still being added back into the map here, causing a leak.

fix(kml): fix leak of disposed KML nodes

---

src/os/ui/filters.js
src/plugin/arc/arc.js
src/plugin/arc/layer/arcfeaturelayerconfig.js
src/plugin/arc/layer/arclayerdescriptor.js

This loads the Arc layer metadata and creates a feature type in the layer config, if one isn't already provided in the layer options (via the descriptor).
The filters tab will also display a warning to the user if they try editing and columns are unavailable, instead of doing nothing.
Fixes #382.

Ensure feature type gets loaded for Arc layers.

---

src/os/ui/legend.js
src/os/ui/window.js
views/legend.html

- The legend button in the bottom nav will now toggle the legend on/off.
- Fixed the legend being positioned incorrectly the first time it's opened each session.
- Removed the concept of "widget mode" for the legend. This was used to differentiate between the floating legend (normal case) and the embedded legend that was previously used in Settings > Legend.
- Added an additional window close path to use the scope `closeFlag` on non-traditional windows like the legend.

Toggle legend on/off with the legend button

---

src/os/ui/menu/defaultwindowsmenu.js
src/os/ui/menu/windowsmenu.js

This is the last button remaining that wasn't toggling its window, and handles the case where a button opens a window with a different `id` than the window config.

The Servers button will now toggle the settings window.

---

package.json

This was being automatically changed by either yarn or npm.

Remove extra space in package script.

---

src/plugin/ogc/wfs/wfslayerconfig.js

As far as I can tell, there is not anything in the `GetCapabilities` response (for v1.1.0) which determines if the service supports `application/x-www-form-urlencoded` in the POST payload for `GetFeature` requests. Therefore, I have merely added a config parameter for now.

feat(wfs): add support for KVP-formatted POST payloads

---

externs/os.externs.js
src/os/layer/animatedtile.js
src/os/ui/screenoverlay.js
src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlparser.js
src/plugin/file/kml/kmlsource.js
src/plugin/file/kml/ui/kmlnode.js

Annotations and KML ground/screen overlays will now respect both timeline and tree visibility states.
Summary of changes:
- Refactors overlay parsers to use the `ol.xml` API, and parses additional fields like time.
- Adds an animation state flag to KML nodes, so overlay visibility can be resolved between tree/timeline states.
- Fixes a bug where a `ScreenOverlay` with `visibility = 0` would not be added to the KML tree.
This file has a number of ground/screen overlays with a mix of timeless, time instant, and time range. Rename to `.kmz` to load it.
[Overlays.zip](https://github.com/ngageoint/opensphere/files/2927066/Overlays.zip)

Sync tree/timeline visibility states for KML overlays

---

src/os/ui/menu/menubutton.js

`this.scope['menu']` drives the `active` class within the templates. Therefore, checking for the existence of the class (or any of its derivatives) is superfluous and in some cases incorrect (due to some of them not being synchronously removed).
fixes #385

fix(menu): remove superfluous boolean checks

---

src/os/ui/buffer/bufferdialog.js
src/os/ui/buffer/bufferform.js
src/os/ui/filter/ui/filterexport.js
src/os/ui/state/stateimport.js
src/plugin/area/kmlareaimportui.js
src/plugin/area/shpareaimportui.js
src/plugin/places/ui/saveplaces.js
views/buffer/bufferdialog.html
views/file/anytypeimport.html
views/filter/filterexport.html
views/plugin/kml/kmlarea.html
views/plugin/places/saveplaces.html
views/plugin/shp/shparea.html
views/query/area/userarea.html
views/query/editarea.html
views/query/mergeareas.html
views/query/modifyarea.html
views/windows/browsedata.html

Window content must be a flex container for it to fill the window. This was a mix of the root element in the template not having `d-flex flex-column` and the directive not using `replace: true` which would create another DOM level that was not a flex item.
Resolves #422.

Fix various windows that did not collapse properly.

---

src/os/ui/feature/tab/abstractfeaturetabctrl.js

`updateTab` may rely on initialization that happens in the constructor. Allow all parent constructors to finish executing before updating the tab.

Update tab after all constructors have executed.

---

src/plugin/cesium/cesiumrenderer.js

Scale line updates were throwing errors when the globe was tilted to extreme angles.

Avoid null dereference when canvas coordinate can't be resolved.

---

src/plugin/cesium/sync/featureconverter.js

The OL transform function does not behave the same when given an output array. `transform(coord, output, 3)` is not remotely the same as `transform(coord, undefined, 3)` and does not copy the altitude from the original coordinate like it does in the former call.
fixes #437

fix(cesium): copy height through transform function

---

src/os/ui/feature/featureinfo.js
src/os/ui/feature/tab/abstractfeaturetabctrl.js
views/feature/featureinfo.html
views/feature/multifeatureinfo.html
views/feature/tab/descriptiontab.html
views/feature/tab/propertiestab.html

- Include the name/title field from a feature when present to help identify which feature is active in the window.
- Compute the title on feature change instead of every scope apply.
- Add borders around the feature list and tab pane to isolate scrollable areas, and remove other borders that were inconsistent from tab to tab.

Show feature name/title and tweak overall layout.

---

src/os/net/request.js

Requests that are made frequently (like polling a service) result in log spam that may not be desirable. This allows changing the default log level for non-warning/error logs in `os.net.Request`.

Allow changing the default log level for requests.

---

externs/papaparse-3.1.2.js
src/os/ui/file/csv/abstractcsvparser.js
src/os/ui/file/csv/csv.js

To test, load a CSV in both the debug and compiled app. It should load normally. After loading at least one CSV, `Papa.SCRIPT_PATH` should be set (check in the console).
Fixes #455.

Set path to Papa Parse library.

---

src/os/ui/datetime/wheeldate.js

Fixes #460.
Prevents the exception described in #460 by using a different DOM target for the wheel listener. Wheel date controls should behave exactly as they did before, but Chrome 73+ should no longer log an exception to the console while scrolling the mouse wheel over the page.

Avoid listening to wheel events on the document.

---

externs/Cesium.externs.js
src/plugin/cesium/cesiumcamera.js

Replaces use of Cesium's `Camera.prototype.computeViewRectangle()` because it is inaccurate in several ways. It only uses the corners of the screen as sample points (4 compared to 64 now), and it also gives up and assumes that the rectangle is `Rectangle.MAX_VALUE` if at least 3 of those corners are in space (`Rectangle.MAX_VALUE` is not ever a correct view rectangle because the camera can only see roughly half the globe at once).

fix(cesium): replace use of Cesium's camera.computeViewRectangle

---

src/os/geo/geo.js
test/os/geo/geo.test.js
test/os/im/mapping/latlonmapping.test.js

DMS Changes
- Longitudes with 3 digits must have a 0 or 1 as the first digit.
- Seconds are now required.
DDM Changes
- Longitudes with 3 digits must have a 0 or 1 as the first digit.
- Decimal minutes are now optional. The group isn't captured to avoid changes to parser configs.
Fixes #471.

fix(geo): Enforce DMS/DDM requirements in regexes.

---

scss/fontloader.scss
scss/os/_nganimate.scss
scss/overrides_default/_bootswatch.scss
scss/overrides_slate/_bootswatch.scss

Contributes to #141.
- Font loader double quotes are no longer needed, and must have been from another rendition of that during the Bootstrap 4 upgrade. The output CSS is the same with single/double quotes.
- `mixin-name-format` rules are OBE with the Bootstrap 4 upgrade.
Remaining `sass-lint:disable` lines are more involved and will require deeper investigation if we want to remove them. Several are for browser support and cannot be removed unless we change minimum versions.

style(sass-lint): Remove/fix unnecessary sass-lint:disable lines.

---

src/os/interaction/doubleclickzoominteraction.js
src/os/interaction/mousezoominteraction.js
src/os/mapcontainer.js
src/os/ui/ol/interaction/abstractdrawinteraction.js

This ensures `ol.ViewHint.INTERACTING` is unset correctly in drawing interactions, and also changes zoom interactions to use Command instead of Control as the modifier on Macs.
The interacting issue was caused by unsetting the flag on a delay to prevent the select interaction from also handling the event. The flag was set on each mouse down event, but only unset after a delay which was restarted on each mouse up event. On double click, it was set twice but only unset once.
The delay was intended to prevent selecting features when drawing completed on top of them. This is now done by calling `preventDefault` on the event when drawing ends (preventing further interactions from handling the event).
Fixes #184.

Fix stuck interacting flag.

---

externs/Cesium.externs.js
src/os/map/map.js
src/os/mixin/mixin.js
src/os/mixin/zoomscalemixin.js
src/plugin/cesium/sync/featureconverter.js

[Demo Here](https://schmidtk.github.io/opensphere-zoom-scale/)
This attempts to mimic the behavior of Google Earth, where icons and labels are scaled/hidden when zooming far out. The general goal with this approach was to get the behavior as close as possible, without impacting performance.
* OpenLayers: Mixin the image/label canvas renderers to apply the scale value without modifying OpenLayers style objects. This avoids changing individual styles on features, which we know to be costly. I did not scale label opacity (like Cesium/GE) either, because that would require manipulating color strings on each render. Instead they're hidden (scale = 0) at roughly the same level.
* Cesium: Use Cesium's `NearFarScalar` to scale billboards/labels, and to fade out labels.
There is one potentially …

feat(map): Scale down icons/labels as the map/globe is zoomed out.

---

externs/Cesium.externs.js
src/plugin/cesium/cesiumcamera.js

Cesium's `SceneTransforms.wgs84ToWindowCoordinates()` returns `undefined` for coordinates outside the window. We need it to return the pixel as if it existed. This condition occurs when the camera's position vector is outside the camera frustum.

fix(cesium): fix null pointer in camera extent computation

---

src/os/command/transformvectorscmd.js
src/os/extent.js
src/os/geo/geo.js
src/os/geo/geo2.js
src/os/geo/jsts.js
src/os/interaction/contextmenuinteraction.js
src/os/interaction/drawlineinteraction.js
src/os/interaction/measureinteraction.js
src/os/interpolate.js
src/os/map.js
src/os/mapcontainer.js
src/os/mixin/canvasreplaygroupmixin.js
src/os/mixin/geometrymixin.js
src/os/mixin/rbushmixin.js
src/os/ol/control/mousepositioncontrol.js
src/os/query/areamanager.js
src/os/query/baseareamanager.js
src/os/source/vectorsource.js
src/os/ui/ol/interaction/dragboxinteraction.js
src/os/ui/ol/interaction/dragcircleinteraction.js
src/os/ui/ol/interaction/drawpolygoninteraction.js
src/os/ui/search/place/coordinatesearch.js
src/plugin/ogc/query/ogcspatialformatter.js
src/plugin/pelias/geocoder/search.js
test/os/extent.test.js
test/os/feature/feature.mock.js
test/os/geo/geo2.test.js
test/os/mixin/rbushmixin.test.js
test/plugin/pelias/geocoder/peliasgeocoder.test.js

Mixes in functionality to the OL RBush wrapper that queries for multiple 'worlds' of an extent and
dedupes those results.
Edit:
This now also addresses hit detection over the antimeridian from OpenLayers. A good test file for both of these items is
[KML Test.txt](https://github.com/ngageoint/opensphere/files/3074784/KML.Test.txt)
resolves #468

Fix antimeridian queries via multiple world queries

---

src/os/ex/abstractexporter.js
src/os/ex/iexportmethod.js
src/os/source/source.js
src/os/ui/ex/exportdialog.js
src/plugin/file/csv/csvexporter.js
src/plugin/file/csv/ui/csvexportui.js
test/plugin/file/csv/csvexporter.test.js
views/plugin/csv/csvexport.html

Geometry and time fields were previously always included in exports. This commit adds an option to
keep them out of the export if they're hidden.
BREAKING CHANGE: Even though this defaults to the old behavior I haven't had time to ensure this doesn't break other uses of it
WIP:
* Replaced with `alwaysIncludeLatLonTime` since not all geometry is included with this option
* Adding notes that this is not a stand alone UI

fix(CSVExport): Prevent hidden columns from being included in export

---

.travis.yml

build(cypress): Corrects after_failure script

---

src/os/data/sourcemanager.js
src/plugin/vectortools/joinlayercmd.js
src/plugin/vectortools/joinwindow.js
views/plugin/vectortools/join.html

The previous version indicated to the user that it was more of a "match" while using the logic from "contains". This adds support for both while avoiding repeating logic.

fix(vectortools): add case-insensitive match and contain indexers

---

src/os/fn/fn.js

This allows the function to be run in multiple window contexts.

fix(fn): use duck typing rather than instanceOf

---

src/os/layer/vector.js

This was fixed in `supportsAction`, but not `callAction`. Result was the option being displayed, but not working unless the source was a request source.

fix(vector): Fix detection of vector source refresh support.

---

src/os/ui/column/mapping/mappingexpression.js

Columns of type `integer` should be supported, but were hidden from the column mapping UI.

fix(columnmapping): Allow all numeric column types in column mappings.

---

src/os/source/isource.js
src/os/source/source.js
src/os/source/sourcecolumn.js
src/os/source/vectorsource.js
src/os/ui/buffer/bufferform.js
src/os/ui/data/addcolumnform.js
src/os/ui/featureedit.js
src/os/ui/layer/layers.js
src/plugin/file/kml/kmlnodelayerui.js
src/plugin/file/shp/shpexporter.js
src/plugin/places/ui/saveplaces.js
src/plugin/track/track.js
src/plugin/vectortools/vectortools.js
test/os/source/source.mock.js
test/os/source/source.test.js
test/os/source/vectorsource.test.js

This prefers `getColumnsArray` for performance when the source columns are not being modified. Otherwise use `getColumnsArray` when intentionally modifying columns, and `getColumns` when modifying for local use.
Fixes #548.

Create separate functions to get original columns or a copy.

---

src/os/ui/column/mapping/columnmappingform.js
src/os/ui/column/mapping/mappingexpression.js
src/os/ui/ogc/iogcdescriptor.js
src/os/ui/ogc/ogcdescriptor.js
src/plugin/ogc/ogclayerdescriptor.js

IOGCDescriptor extends IFilterable, so its better to just implement in terms
of the parent API.
Resolves #545.

chore(api): Deprecate IOGCDescriptor::getUrlKey(), use getFilterKey()

---

package.json
src/os/state/v4/timestate.js
test/os.xsd.mock.js
test/os/state/v4/timestate.test.js

Resolves #467.
This will fail until https://github.com/ngageoint/opensphere-state-schema/pull/10 is merged and opensphere-state-schema is released as 2.3.0. I tested locally by modifying the package.json to 2.2.0 and then copying in the required files - the workspace resolver doesn't seem to do the right thing here.

fix(state): Support save / restore of timeline slices.

---

src/os/style/iconstyle.js

Changing values such as scale or rotation after load pollutes the style cache. A style could be already in the cache under a different scale, and changing it on the instance to 1 will make all requests for the original scale pull 1 instead.
Load [scale_bug.txt](https://github.com/ngageoint/opensphere/files/3237829/scale_bug.txt) under both this and master to see the difference.

fix(style): avoid changing values on cached styles

---

src/os/ui/window/confirm.js

`os.ui.window.launchConfirm` was picking an arbitrary default height of 140px. Now that we can auto size windows based on their content, this is a much better default. This fixes display for windows like Saved Places folder removal, and is consistent with the similar `os.ui.window.launchConfirmText` call.

Automatically determine height by default for confirm windows.

---

src/os/file/mime.js

There should be a nastygram if something attempts to add an undefined type or detect function.

feat(mime): log errors if sent undefined type or detect

---

src/os/ui/timeline/currenttimemarker.js

The timeline's current time marker was using `requestAnimationFrame` with an internal limiter to prevent updates from happening more than once per second (usually). The callback was being fired repeatedly and consuming a measurable level of CPU resources in the performance trace. This optimizes callbacks to fire when the time marker would actually be changing.
This class was also calling `requestAnimationFrame` while another request was pending, and replacing the request ID. That was causing the updates to stack, and continue even when the timeline was closed/disposed.

Reduce updates to the current time marker and fix disposal.

---

package.json
src/os/debug/fancierwindow.js

Clear button on log no longer closes window, only clears log in FF60.7.0esr and Chrome.
Test Steps:
Using Fire Fox version 60.7.0esr
1.Top right hand corner click the "support" button
2.Drop down appears
3.Click "View Log"
4.Top right corner select "clear"
5.After selecting "clear" the data should be cleared, and the window should remain open.

Fix-594(Window Closure)

---

externs/Cesium.externs.js
src/os/feature/feature.js
src/os/fn/fn.js
src/os/map/map.js
src/os/mapcontainer.js
src/os/ui/menu/listmenu.js
src/os/ui/menu/timelinemenu.js
src/os/webgl/abstractwebglrenderer.js
src/os/webgl/iwebglrenderer.js
src/plugin/cesium/cesium.js
src/plugin/cesium/cesiumrenderer.js
src/plugin/cesium/command/flytospherecmd.js
src/plugin/cesium/sync/vectorsynchronizer.js
src/plugin/file/kml/kmlmenu.js

FlyTo in 3D was still using the 2D `FlyToExtent`, which does not take altitude into account and could potentially fly the camera too far in to see the feature.
Test:
* Make some places with and without altitude
* Right click each one and select "Go To" in 2D and 3D
* In 3D, tilt the camera before and verify that it keeps the general orientation after flying to the feature(s)
* Place the features in a folder and select "Go To" on the folder in both 2D and 3D

feat: webgl fly to should fly to bounding sphere rather than extent

---

ci-script.sh

The Cypress tests are not currently running with enough consistency (not only in the Travis CI environment but also locally) to be run as part of the `master` build and the failures introduced by it are holding up other development.
The development of those tests should be continued on another branch until we can address the consistency issue.

ci: disable cypress tests

---

src/os/style/style.js
src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlparser.js
test/os/style/style.test.js

This changes the style config merging to allow for a definition of `null` to remove the parent style rather than inheriting it (`undefined`). Additionally, the `readStyle_` parser in `ol.format.KML` was replaced with a custom implementation which returns style configs rather than OpenLayers style objects.
Example: create a style config that removes a stroke rather than inheriting the default stroke:
```
var styleConfig = {
'fill': {
'color': 'rgba(255,0,0,1)',
},
'stroke': null
};
```
Testing:
Compare [PolygonStyles.txt](https://github.com/ngageoint/opensphere/files/3302618/PolygonStyles.txt) to the same file in Google Earth (making labels always on helps with identifying the correct style)
Google Earth result:
resolves #604

fix(style): fix merge to allow fill and outline deletions

---

src/plugin/track/track.js
src/plugin/track/trackmenu.js
test/plugin/track/track.test.js

* Allow passing coordinates directly to `plugin.track.createTrack` instead of features.
* Deprecate `plugin.track.addFeaturesToTrack` in favor of the new `plugin.track.addToTrack`, which allows adding features or coordinates to an existing track.
* Add tests for creating/updating tracks.

Create/update tracks from coordinates.

---

src/os/ui/layer/defaultlayerui.js

fix #630
To get this to happen:
Click on a feature or map layer in the layers menu.
Click on Style to open the style menu (or zoom).
Click on Style again to close it (or zoom).
Now click on a different layer...
Click on the previous zoom or style tab, it will either be closed or left open as you had it before.

fix(LayerUi): fix save of collapse state and add save call to style tab

---

package.json

This uses the same versions as in the other modules. It removes an incorrect peer dependency warning from yarn:
```
opensphere > @semantic-release/changelog@1.1.1" has incorrect peer dependency "semantic-release@>=13.3.0 <15.0.0".
```
I considered just removing the whole semantic release thing, but kept it for possible future use.

chore: Update semantic release deps.

---

src/plugin/file/kml/kml.js

Fixes case where a default style is applied when a `Style` element is empty or only contains
children that don't impact the feature (`BalloonStyle` or `ListStyle`).

fix(kml): Ignore Style elements when nothing is parsed.

---

src/os/geo/geo.js
test/os/geo/geo.test.js

Also adds documentation for optional parameter defaults for
`os.geo.toSexagesimal()` and `os.geo.toDegreesDecimalMinutes()`.
Adds two tests for `os.geo.toDegreesDecimalMinutes()`.
Resolves #679.
Coverage changes from:
Statements   : 54.23% ( 36330/66995 )
Branches     : 30.91% ( 8726/28228 )
Functions    : 37.79% ( 3377/8936 )
Lines        : 54.23% ( 36330/66993 )
to:
Statements   : 54.23% ( 36331/66995 )
Branches     : 30.94% ( 8734/28228 )
Functions    : 37.8% ( 3378/8936 )
Lines        : 54.23% ( 36331/66993 )

test(geo): Add unit tests for os.geo.toSexagesimal()

---

externs/os.externs.js
src/os/annotation/abstractannotationctrl.js
src/os/annotation/annotation.js
src/os/annotation/featureannotation.js
src/os/annotation/featureannotationui.js
src/os/ui/featureedit.js
src/plugin/file/kml/ui/kmlnode.js
src/plugin/file/kml/ui/kmlnodeui.js

- Adds a position property to annotation options for persisting their position. I'm not exactly sure why this wasn't persisted before, but keeping it around fixes a lot of issues with show/hide and refresh positioning for annotations. They should now no longer reset their position on toggling show/hide nor on refresh.
- Fixes losing the show/hide state on refresh when clicking the toggle buttons on both the node UI and the annotation hover controls.
- Fixes the bug where clicking the top right X on the placemark edit window would cause the annotation hover controls to not show up.

fix(annotations): fixes annotation positioning/persistence issues

---

scss/os/_mixins.scss
scss/os/_ngvalidate.scss
scss/os/_overrides_jqueryui.scss
scss/os/_overrides_openlayers.scss
scss/os/_overrides_select2.scss
scss/os/_overrides_tuieditor.scss
scss/os/_timeline.scss
scss/os/_tristate.scss
scss/os/_utils.scss

The sass-lint:disable variant has file scope.
Relates to #141 - this narrows down the scope.

chore(css): Disable sass rules at block scope

---

scss/os/_mixins.scss

Also remove `-moz-grab` and `-moz-grabbing` cursor vendor prefixes, since Firefox supports the standard
forms from v27 (https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Browser_compatibility).
Also remove mythical `-ms-grab` and `-ms-grabbing` cursor prefixes.

fix(ui): Use grab cursor instead of pointer cursor when grabbing

---

src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlparser.js

Fixes #676.
OpenLayers uses the yellow pushpin as the default icon style to match Google Earth's behavior. We prefer the placemark circle, so this replaces their defaults with ours.
To test, load [this file](https://github.com/ngageoint/opensphere/files/3412570/DefaultPointStyle.txt). There should be a single point using the white placemark circle as the icon.
Note the KML node color varies because a `PolyStyle` is defined in the KML, and that color is resolved when the node looks for a color in the style config. This is perhaps a bug since that color doesn't impact the rendered feature, but a separate issue if we want that behavior to change.

fix(kml): Replace the OpenLayers default icon with OpenSphere's.

---

src/os/ui/config/settingscontainer.js
src/os/ui/config/settingswindow.js
src/os/ui/window.js

Fixes an error introduced if the resize handler was called after disposal (`this.element` was no longer defined), and prevents leaking windows due to not removing the event listener.

fix(window): Clean up resize handler and avoid errors if called after dispose.

---

cypress/support/execute-tests.sh

- No longer specifies time format; didn't matter since all log output was suppressed anyhow
- Stops opening browser window on starting the server; wasn't needed
This only affects Cypress startup.  Scripts in package.json unmodified.

test(cypress): Removes options from http-server startup that were not needed

---

externs/os.externs.js
scss/os/_utils.scss
src/os/annotation/abstractannotationctrl.js
src/os/annotation/annotation.js
src/os/annotation/featureannotationui.js
src/plugin/file/kml/ui/kmlnode.js
src/plugin/file/kml/ui/placemarkedit.js
views/annotation/annotationoptions.html

This adds label-like style and text binding to annotations so they can be used as moveable labels.
Known Issue: Using the label controls from the places accordion does not update the annotation text in "label" mode.
fix #535

feat(annotation): Add label-like abilities to annotations

---

karma.conf.js
package.json
src/os/file/file.js
test/init.js

Resolves #709.
Testing should verify zip files load in debug/compiled builds. A minor change was made to `os.file` to avoid setting `zip.workerScriptsPath` (default value `null`) if it was already set. Tests set the value in `test/init.js` which used to load after `os.file`, but the script loader reversed the load order.
WIP:

test(karma): Use test loader to avoid Chrome resource limit errors.

---

src/os/data/configdescriptor.js
src/os/data/data.js
src/os/data/datamanager.js
src/os/state/state.js
src/os/state/statemanager.js
src/os/ui/data/descriptornodeui.js
src/os/ui/file/ui/defaultfilenodeui.js
src/os/ui/ol/olmap.js
src/os/ui/providerimport.js
src/os/ui/servers.js
src/plugin/config/configprovider.js
src/plugin/ogc/ogclayerdescriptor.js
test/os/data/configdescriptor.test.js
test/os/data/osdatamanager.test.js
views/data/descriptornodeui.html
views/file/defaultfilenodeui.html

Adds API's to:
* Create a config provider (`plugin.config.Provider.create`) and save it to settings.
* Add layers to a config provider (`plugin.config.Provider#addLayerGroup`).
Existing config provider/descriptor behavior should be unchanged. Existing config descriptor unit tests should cover old behavior, and additional tests have been added for new behavior.
Other changes:
* Most of `os.ui.file.ui.DefaultFileNodeUICtrl` has been abstracted out to `os.ui.data.DescriptorNodeUICtrl`. The former has been maintained to avoid a breaking change and for a minor adjustment to the removal warning.
* A few places were using `dataManager.getProvider(descriptor.getDescriptorType())` to locate a provider. This method requires the provider ID to match the descriptor type, which is not guaranteed to be …

Create config providers and add layer configs

---

src/os/mixin/zoomscalemixin.js
src/plugin/wmts/mime.js

The previous method was both updating the scale too often (once per point), and prone to timing issues. It would fail to render the updated icon scale if the map container view change event fired after OL had already rendered the current extent/resolution.
This approach updates the scale in a `precompose` handler, if the altitude has changed since the last scale update.

Fix icon zoom scale

---

src/os/data/columndefinition.js

This significantly reduces the footprint of our descriptors in settings by only persisting values that differ from the default for columns. Previously we were persisting dozens of key/value pairs that just wasted time and space.

perf(columns): only persist non-default values for columns

---

src/os/ui/ogc/ogcserver.js
src/plugin/ogc/wfs/wfslayerconfig.js

Trying to integrate with a [MapServer](https://mapserver.org/ogc/wfs_server.html) WFS server uncovered some discrepancies in the way the capabilities metadata was parsed and handled.
MapServer provides the URLs in the operations metadata in the following way:
```xml
<ows:Operation name="GetFeature">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:type="simple" xlink:href="https://osm-wfs-eric.dev.geointservices.io/wfs?"/>
<ows:Post xlink:type="simple" xlink:href="https://osm-wfs-eric.dev.geointservices.io/wfs?"/>
</ows:HTTP>
</ows:DCP>
…
</ows:Operation>
```
This failed to parse correctly in the baseline logic, which assumes the `href` attribute will be the first attribute:
```javascript
// Attr.value is the DOM4 property, while Attr.nodeValue inherited from Node should work on older browsers
var …
```

fix(wfs): tighten up parsing and handling of WFS URLs and output formats

---

cypress/integration/smoke-tests/toolbar-right.spec.js
src/os/ui/ngrightclick.js
vendor/angular-ui/angular-ui.js

Resolves #736.
There are a lot of discussions over `$timeout` vs `$evalAsync`, but it seems the latter is better for avoiding the `$rootScope:inprog` error that we can get calling `$apply` directly.
We could possibly replace the local vendor lib with individual libs (like [`angular-ui-date`](https://www.npmjs.com/package/angular-ui-date) for this one), but that's a much larger task than fixing this bug in our copy of the library.

fix(ng): use $evalAsync instead of $apply to avoid $rootScope:inprog

---

src/os/filter/im/osfilterimport.js
src/os/filter/im/osfilterimporter.js
src/os/ui/filter/im/filterimport.js
src/os/ui/filter/im/filterimporter.js
src/os/ui/filter/im/filterimportmodel.js
src/os/ui/im/action/filteractionimport.js
src/os/ui/im/action/filteractionimporter.js
src/os/ui/layer/layerpicker.js
views/filter/im/filterimport.html
views/filter/im/filterimportmodel.html
views/layer/layerpicker.html

The code used to import filters and feature actions was within the UI controllers, preventing reuse of the code outside those UI's. To allow importing these elsewhere, all import code has been extracted to importers and the UI's now have a `getImporter` function to provide the appropriate importer.
To test, verify filters and feature actions import as they did before.
Additional changes:
* The filter import UI will no longer show the check/X icons until a layer has been selected, or the text explaining the red X. This is intended to avoid potential confusion because the UI previously showed the red X when no layer was selected.
* The layer picker was using the layer/descriptor `getId` function in the Angular template, and those functions are not exported. This prevented the layer function …

Move filter/feature action import code to importers

---

cypress/plugins/index.js
cypress/support/commands.js
cypress/support/execute-tests.sh
package.json

Changes:
- Added support for image comparisons under Windows.  Image comparisons are off by 15 pixels under Windows, and was throwing `Error: Image size (1279x1000) different than saved snapshot size (1264x1000)`.
- Added workaround for a bug with http-server where Cypress was stuck in an endless redirect loop under Windows http-party/http-server#525
- Added a Windows compatible method of detecting running instances of a web server and terminating those instances automatically or on demand (via `yarn stop-server`)
Tests:
Note: There may be failures with the test scripts, those are fixed here: #735 
- Windows: Cypress tests running via GUI (`npm run cypress:test`) AND CLI (any other cypress script; e.g. `npm run cypress:test-spec smoke-tests/smoke-test.spec.js`) do not immediately fail …

Add Cypress Windows Support under Git Bash

---

scss/fontloader.scss

The old setup was only suitable if a project had a symlink from `project/vendor/fonts` to `opensphere/vendor/fonts`. Symlinks do not work in Windows.
Therefore, this change uses a well-defined path to opensphere within the workspace.
Note that I do not believe that this method is compatible with using opensphere as a library within `node_modules`. That will need to be a follow-on for later investigation.

build(windows): fix font path in Windows

---

externs/Cesium.externs.js
src/os/layer/image.js
src/os/layer/layer.js
src/os/ol/image.js
src/os/source/imagestatic.js
src/plugin/cesium/cesium.js
src/plugin/cesium/cesiumplugin.js
src/plugin/cesium/sync/imagestaticsynchronizer.js
src/plugin/cesium/sync/imagesynchronizer.js
src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlmenu.js
src/plugin/file/kml/kmlparser.js
src/plugin/file/kml/ui/kmlnode.js
test/os/ol/image.test.js

This adds image rotation support and then uses it in KML GroundOverlays to address some of our issues with displaying those.
Additionally, if the GroundOverlay contains an unsupported `LatLonQuad` value, then a warning is issued. I can write a ticket for further support of that. It requires non-affine transforms which are not supported in `CanvasRenderingContext2D` but could be done by us since the image would only need to be redrawn once.
I have not decided what warnings to show or not show regarding the lack of projection information for the raster image. Right now it is simply assumed to be in the application projection (probably a bad assumption).
Test Files (test in 2D/3D and in multiple projections):
[GroundOverlays_etna_rotation_compare.txt](https://github.com/ngageoint/opensphere/f …

Add Image Rotation Support

---

package.json

Those deps are now direct dependencies of eslint-config-opensphere and are no longer necessary to include directly.

chore(package): update language_in and remove deps

---

README.md
src/os/geo/geo2.js
src/plugin/arc/arcjsonparser.js
test/os/geo/geo2.test.js
test/plugin/arc/arcjsonparser.test.js

resolves #739
Added functionality to compute the WindingOrder of a polygon and use that to sort internal and external Polygons into MultiPolygons. Updated or added corresponding utests.

fix(arc): fix multipolygon parsing from oriented rings

---

src/os/search/abstractsearchresult.js
src/os/search/isortableresult.js
src/os/search/search.js
src/os/ui/search/place/coordinateresult.js
test/os/search/abstractsearchresult.test.js
test/os/ui/search/place/coordinateresult.test.js

* Adds a new interface to allow search results to provide sort values.
* Fixes a bug in the abstract search result preventing setting the `id` to literal `0`.

Add sortable search result interface

---

src/plugin/file/shp/shpexporter.js
src/plugin/file/shp/shpparser.js

* Add a `.prj` to exported shapefiles.
* DBF export did not handle precision detection for negative numbers.
* Added the language driver ID (ANSI) to the DBF, required by some external applications.
* Avoid errors if the parser is cleaned up during async ZIP reads.

SHP enhancements

---

cypress/support/execute-tests.sh
cypress/support/settings/opensphere-config-tester.json

- default urls on default projection (3857) were incorrect; fixed
- default urls now provided for both 3857 and 4326
- `zoomOffset` previously incorrectly always set for 3857; fixed, now handles 3857 and 4326

test(cypress): adjusts projection handling

---

cypress/integration/smoke-tests/map.spec.js
cypress/support/execute-tests.sh
cypress/support/selectors/opensphere.js
cypress/support/settings/opensphere-config-tester.json

This contains a commit from #772, review the most recent commit: https://github.com/ngageoint/opensphere/pull/774/commits/b95a5bfd4dc6fee2a0a219365b7292c2472de14e
- Recent Cypress updates included fixes for interactions with the map canvas
- Adds tests for navigating via overview map
- Adds test for map context menu
- Adds tests for zoom via double click
Drag and drop operations still not working https://github.com/cypress-io/cypress/issues/857

test(cypress): adds tests for map overview, context menu, zoom

---

cypress/integration/regression-tests/layers-dialog/feature-list.spec.js
cypress/support/execute-tests.sh
cypress/support/selectors/dialogs.js
cypress/support/settings/opensphere-config-tester.json

This contains a commit from #772, review the most recent commit: https://github.com/ngageoint/opensphere/commit/42fe75fea267750b7faed099759402b0c4f8c330
- Adds tests for Show selected only
- Adds tests for Row height slider
- Adds tests for sorting by column header
Resolves https://github.com/ngageoint/opensphere/issues/581
Note: There are several failing tests due to the latest version of Cypress.  These tests have already been fixed in an PR in another environment.  You can run tests with `it.only` to check the new tests in isolation.

test(cypress): adds tests for toolbar, sorting, show selected only

---

src/os/debug/fancierwindow.js
src/os/mainctrl.js

This bug was caused by the fix to another one: [issue 574](https://github.com/ngageoint/opensphere/issues/574)
For testing this ticket, make sure to open the branch in firefox. Then check and make sure that:
• Log window doesn't reopen on its own when closed via the X (current bug).
• Log window doesn't close in Firefox when you click Clear (bug from 574).
• Log window closes when the application is closed (additional bug prior to 574).

fix(logger): the logger in firefox no longer randomly opens GEOVIZ-1

---

docs/guides/plugin_file_type_guide/content_type.rst
docs/guides/plugin_file_type_guide/test/plugin/georss/mime.test.js
src/os/file/mime/xml.js
test/os/file/mime/xml.test.js

The content type tests were not running due to an error:
```
var buffer = new TextEncoder().encode(str).buffer;
^added this
```
They were also causing a subsequent test failure because the test xml has empty root tags and the xml mime detection was not concluding those were xml. This has been fixed.
Additionally, running this from an external plugin requires that the plugin's `karma.conf.js` pull in the necessary dependencies for the mime stack. Those instructions have now been added.

docs(rtd): fix content type tests and add external instructions

---

package.json

Node scripts cannot be invoked directly on Windows because it does not understand `#!/usr/bin/env node`. Explicitly call the script with node to fix running in on Windows.

build(npm): explicitly invoke node for Windows-based builds

---

src/os/net/baseservermodifier.js
src/os/net/request.js
src/os/net/urlmodifier.js
test/os/net/baseservermodifier.test.js

The `uri.setQuery()` method takes an argument for whether or not to decode that was not being used. Because of this fix, `BaseServerModifier` is no longer necessary (although the API for configuring it has been left the same to avoid breaking its usage).
BREAKING CHANGE: `UrlModifier` now avoids doubly encoding the query string. Any steps taken on the receiving end of these requests to code around that bug need to be reviewed and possibly removed.
BREAKING CHANGE: `os.net.BaseServerExpression` was removed because it was not fully featured for parsing out domain names. Please use `new goog.Uri(str).getDomain()` or `new URL(str).hostname` instead.

fix(net): fix double encoding issue

---

src/os/layer/config/abstracttilelayerconfig.js

Use the `baseUrl` setting in tile layers. This can't use `os.net.URLModifier` directly because many tile URLs are template URLs which contain things like `/{z}/{x}/{y}` and we don't want those to be encoded.

feat(tile): use baseUrl in tile layers

---

src/os/ui/featureedit.js
src/os/ui/layer/vectorlayerui.js
src/os/ui/layer/vectorstylecontrols.js
views/layer/vectorstylecontrols.html
views/windows/featureedit.html

This PR cleans up fill management within Places:
- Fixes issue where new polygonal places were initially displayed with a fill opacity of 1 in 3D mode. This was a race condition caused by fill management in `updatePreview`.
- Removed the need to delete (or set to undefined) `fillColor` and `fillOpacity` to hide the Fill control. This is now based off the `isPolygon` function. This change removed/simplified a lot of the fill management, and has the side effect of remembering fill color/opacity when switching between point shapes (ellipse vs non-ellipse).
- Removed unnecessary `showFillStyleControls` functions in vector UI's.
To test:
1. Create polygonal places. Fill should be initialized to white with an opacity of 0. It should be displayed as such in both 2D/3D. Changes to fill controls …

fix(places): clean up fill management

---

src/plugin/cesium/sync/featureconverter.js

Cesium GroundPrimitive is picked when alpha is 0. This is inconsistent with 2D and polygons using Primitive.
Test steps:
- Switch to 3D mode.
- Draw polygons/circles and save them to places.
- Set the altitude mode to Clamp to Ground. Verify the polygon is not picked from the center when it has a fill opacity of 0. It should be picked if the opacity is non-zero.
- Repeat with other altitude modes.
- Load [PolygonStyles.txt](https://github.com/ngageoint/opensphere/files/3880539/PolygonStyles.txt) (rename to `.kml` first).
- Verify all polygons are picked correctly. There is a separate issue causing extruded polygons to flicker at times on hover. That is unrelated to these changes and not being addressed here.

fix(cesium): only pick unfilled polygons from outline

---

src/os/geom/geometryfield.js
src/os/mixin/geometrymixin.js
test/os/mixin/geometrymixin.test.js

Adds double-transform protection to `ol.geom.Geometry` by caching the destination projection code on the geometry and checking it when subsequently transforming again.

feat(mixin): add double-transform protection

---

README.md
docs/getting_started.rst
docs/windows_development.rst

Closure's `depswriter.py` is now used to generate the debug build, making it a requirement to build OpenSphere. This has been updated in the README and RTD docs.

docs(debug): update debug build docs and Python dependency

---

karma.conf.js
package.json
src/os/alert/alert.js
src/os/alert/alertevent.js
src/os/alert/alerteventlevel.js
src/os/alert/alerteventseverity.js
src/os/alert/alerteventtypes.js
src/os/alert/alertmanager.js
src/os/alert/alertmanagerinstance.js
src/os/alert/eventtype.js
src/os/arraybuf.js
src/os/capture/capture.js
src/os/color.js
src/os/debug/fancierwindow.js
src/os/defines.js
src/os/ui/alert/alertpopup.js
src/os/ui/alerts.js
src/os/ui/scaleline.js
src/os/worker.js
src/plugin/heatmap/heatmap.js

This branch is being used to work out any kinks with `goog.module` and determine the preferred approach to converting source files. The intent is to require minimal changes when converting from `goog.module` to ES6 modules, once all code has made the initial transition.
The first commit is required for tests to run with `goog.module`, so it can be separately merged if needed.
These PR's are required for the build to pass. They add `goog.module` handling to our ESLint config.
- https://github.com/ngageoint/eslint-config-opensphere/pull/10
- https://github.com/ngageoint/eslint-plugin-opensphere/pull/6

Investigate refactor to goog.module

---

src/os/alert/alertmanagerinstance.js

This file will eventually be removed in favor of getInstance, and does not need to be a module.

fix(alert): use goog.provide for global instance to allow reassignment

---

src/os/worker.js

`goog.define` was setting the value correctly, but the module loader then called `goog.module.declareLegacyNamespace` which recreated the `os.worker` namespace. Because that file doesn't have exports, `os.worker` was set to `undefined`. Solution is to export defines on the namespace.

fix(define): fix os.worker.DIR in the debug build

---

package.json
src/os/alert/alert.js
src/os/alert/alertevent.js
src/os/alert/alertmanager.js
src/os/color.js
src/os/debug/fancierwindow.js
src/os/ui/scaleline.js
tasks/ci-script.sh

- Use `goog.requireType` for modules that are only used to provide Closure with type information, and remove the `eslint-disable-line` comment. This no longer triggers an error, as of https://github.com/ngageoint/eslint-config-opensphere/pull/12.
- Use implicit `@const` from ES6 `const` keyword.
- Use implicit `@private` for module-scoped properties.
- Use implicit `@extends` for ES6 `class <Child> extends <Parent>`. This is only needed when the `@extends` annotation defines generic types.
- Replace `var` with `const/let` in modules.
- Disable the API doc build in CI. `js-dossier` has several issues with `goog.module` and ES6 modules. Following the transition, we'll have to find a more appropriate API documentation tool.

Cleanup pass for goog.module files

---

scss/os/_overrides_slickgrid.scss

This is to make the header row visually consistent with the rest of the header

refactor(slickgrid): style change to header row for slickgrid

---

package.json

This prevents having remote URL dependencies on transient items we do not even use.

chore(package): add resolutions for squire-rte and raphael

---

docs/guides/angular_module_guide/index.rst
docs/guides/angular_module_guide/src/map.js
docs/guides/angular_module_guide/src/map_shim.js
docs/guides/es6_class_guide/index.rst
docs/guides/es6_class_guide/src/closureclass.js
docs/guides/es6_class_guide/src/es6class.js
docs/guides/es6_transition_guide.rst
docs/guides/goog_module_guide/index.rst
docs/index.rst

Describes our transition process to ES6 and explains new code practices with `goog.module` and ES6 `class`.
Live link: http://elite-cap.surge.sh/guides/es6_transition_guide.html

docs(modules): add documentation on goog.module and es6 classes

---

src/os/ui/util/punyparent.js

Old code was using a forEach that was adding to a variable. Changed it to a reduce to better illustrate the meaning of the code.
Also changed function() to arrow function for the higher order functions.
This should not affect functionality. It produces the same result

refactor(punyparent): changes forEach to reduce for readability

---

docs/getting_started.rst

Node 6 isn't enough.  The `@semantic-release/changelog` dependency wants at least 8.16.
Also add a note about the built-in server, which we mention in the parent README, but
don't have here.

docs: update node version

---

docs/guides/angular_module_guide/index.rst
docs/guides/angular_module_guide/src/map.js
src/os/ui/map.js

- Added a link to the Map UI source for a full example.
- Updated example snippet to match expected style.
- Clarified documentation based on feedback.
- Simplified map directive function definition using an arrow function with a direct return.

docs(es6): expand on ES6 Angular UI guide

---

scss/overrides_slate/_bootswatch.scss

Make button text different than plain text.
"Ghost buttons" btn-outline-primary border-0 are often use to get an affordance of clicking, with hover effects and all, without having a full button style. This change updates the color for primary to remain blue, so it behaves like a clickable hyperlink and not plain text.

chore(button): updated outline button color to appear clickable

---

scripts/whydep.js

This prints out the paths through the dependency tree between two items. Helpful for figuring out why your dependencies exploded.
Usage is in the script: `scripts/whydep.js`

chore(scripts): add why dep script

---

src/plugin/wmts/wmtsserver.js

A user reported problems adding a WMTS server that required `service=WMTS` in the request. Even when providing that in the input URL, `plugin.wmts.Server.prototype.testUrl` was dropping the parameter. This makes a few changes to how WMTS params are formed for the test request:
- Params parsed from the URL are preserved by starting with the `goog.Uri`'s query data.
- Extend the parameters with any configured on the layer.
- Add the `service` parameter if it does not already exist.
I don't have a public WMTS server that replicates the issue, but at minimum please ensure the following server can still be manually added:
https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi?SERVICE=WMTS&request=GetCapabilities

fix(wmts): use params from the URI, ensure service is set

---

docs/guides/es6_class_guide/index.rst
src/os/alert/alertmanager.js

The new singleton instance format used in modules should not create the instance until `getInstance` is called. This more closely mimics the behavior of `goog.addSingletonGetter`.
Updated the example in the docs to reflect this, and the transform will also create `getInstance` calls in this manner.

Don't create alert manager instance until requested

---

src/plugin/places/placesmanager.js
src/plugin/places/placesmenu.js

This adds checks for the sporadic null cases we've seen with saving/loading Places. It also adds another spot where it will loop back and re-initialize if there is an missing places root node.
I also noticed while working on this that the Spatial menu places were under a different menu header and that Quick Add Places was not an available option, so I changed that to be consistent with the Map menu.

Places persistence fixes

---

src/os/mixin/fixinjectorinvoke.js
src/os/ui/abstractmainctrl.js
test/os/mixin/fixinjectorinvoke.test.js

Angular's `isClass()` used in `invoke()` is incorrect in that it does not check `func.hasOwnProperty('$$ngIsClass')`. If an ES6 class extends an older class structure, `isClass()` will report the parent's cached result, which is incorrect and will result in an error.
Example:
```javascript
const OldClass = function() {};
OldClass.$$ngIsClass = false;
class NewClass extends OldClass;
NewClass.$$ngIsClass // false!
```
Therefore, this mixes in a fix for that in `$injector.invoke` just after `os.ui.injector` is set in `AbstractMainCtrl`.

fix(mixin): address ng isClass failures

---

src/plugin/cesium/primitivelayer.js
src/plugin/cesium/tiles/cesium3dtileslayer.js

Adds a general `getExtent` implementation for primitive layers.
This is not comprehensive because the application should really be operating on aggregated bounding volumes specified and implemented by the renderer (extents for OpenLayers and BoundingSpheres for Cesium) rather than always relying on the OL `getExtent()` function.
However, this will at least get the user in the correct vicinity even if it is not precise regarding altitude.
1. Clone https://github.com/AnalyticalGraphicsInc/3d-tiles-samples into your workspace
1. Add `<yourWorkspaceUrl>/3d-tiles-samples/tilesets/TilesetWithDiscreteLOD/tileset.json` to OpenSphere
1. Right-click the new layer
* Verify that "Go To" is an option
1. Select "Go To"
* Verify that it goes to the big 3D dragon

fix(cesium): better goto support for primitive layers

---

externs/Cesium.externs.js
package.json

Updates the Cesium version to 1.65. There was one breaking change that affected the method signature of an extern we have defined. We don't use it anywhere in Opensphere though.
https://github.com/AnalyticalGraphicsInc/cesium/blob/1.65/CHANGES.md references their breaking change.

feat(cesium): updates cesium version to 1.65

---

src/os/ui/file/kml/kml.js
src/plugin/file/kml/kmlplugin.js
test/os/style/iconreader.test.js
test/os/ui/file/kml.test.js

There are some google maps icons which are not available for closed network usage by duplicating them in `images/icons/kml`. Previously, any file referencing those icons failed with a message in the console and did not show the point. This addresses that issue by checking to see if the icon is one of the ones that we enumerate for the Google icon set.
Additionally, the KML plugin now checks if maps.google.com is accessible and sets a flag that informs whether to use the default icon for missing URLs or just use the URL directly.
You can test all of the items in the "Placemarks" folder of https://developers.google.com/kml/documentation/KML_Samples.kml to ensure that they show up.

fix(kml): fix missing google maps icons

---

scss/os/_iconpicker.scss
views/icon/iconpalette.html
views/icon/iconselector.html

The icon picker was using `h-100 w-100` to size icons in the grid. This was causing icons to be stretched vertically because the aspect ratio of the container (button) did not match the aspect ratio of the image. See before and after:
I also reduced the size of the preview icon in the footer because it seemed larger than necessary. I believe this changed with the BS4 upgrade.

fix(icon): preserve icon aspect ratio in picker

---

externs/os.externs.js
src/os/histo/datebinmethod.js
src/os/histo/numericbinmethod.js
src/os/histo/uniquebinmethod.js
src/os/time/time.js
src/os/ui/uiswitch.js
test/os/histo/datebinmethod.test.js
test/os/histo/numericbinmethod.test.js
test/os/histo/uniquebinmethod.test.js
test/os/time/time.test.js

Updated OS backend to support graph views of binned Feature data where there are numerical gaps in the data.
NOTE: Histogram and Bins unused by OpenSphere.  
**Unit Tests**
- time.test.js - Tests the use of a new "step" function, which gets the millisecond difference between a given date and the next Month or Year
- uniquebinmethod.test.js - Now includes "getStatsForBin" function to calculate range and step size based on a config.  Also stores the configuration showing/hiding empty bins after crossfiltering calculations
- numericbinmethod.test.js - Updating accordingly
- datebinmethod.test.js - Updating accordingly
See GEOVIZ-33

feat(bins): Added Empty Bin support

---

src/os/ui/menu/spatialmenu.js

The Search Area menu option should be hidden when there are no search providers registered that support it.

fix(search): hide the Search Area menu option when no geosearches exist

---

src/os/alert/alertmanager.js

There are cases under the module refactor where the singleton getter
implementation wasn't working quite properly. This allows for setting
a specific instance in those cases.

fix(alert-manager): adds instance setter for the alert manager

---

src/plugin/file/gpx/gpxparser.js

When parsing GPX files with a time component but no elevation, OpenSphere produces coordinates in the XYM geometry layout. This causes an error in Cesium, where coordinates are expected to be provided as XYZ.
This file will cause Cesium to error/freeze when loaded:
[XYM Coords.gpx](https://github.com/ngageoint/opensphere/files/4225327/XYM.Coords.txt)
This is the same file with elevation provided, to verify elevation is still correctly parsed with this change.
[XYZM Coords.gpx](https://github.com/ngageoint/opensphere/files/4225328/XYZM.Coords.txt)

fix(gpx): always parse coordinates as XYZ or XYZM

---

package.json
src/os/fields/fields.js
src/os/histo/numericbinmethod.js
src/os/histo/uniquebinmethod.js
src/os/metrics/metrics.js
src/os/ui/datetime/anydate.js
src/os/ui/layers.js
src/os/ui/timeline/brush.js
src/plugin/track/trackmanager.js

The `eslint-plugin-jsdoc` update found additional comment indentation errors. All errors were fixed with `eslint --fix`.

refactor(eslint): update eslint-config-opensphere and fix lint errors

---

src/os/ui/ui.js

~~This will not allow `os.ui.apply` to apply the scope more often than 5 times a second.~~
~~Open to changing the value for `os.ui.TIME_BETWEEN_SCOPE_UPDATES`.~~
EDIT: This is no longer the approach

feat(scope): don't allow os.ui.apply to apply too often

---

src/os/layer/preset/preset.js

Creating a true "default" set of options for a layer is unfortunately tricky, because the original options may be modified when changes are made to the layer. This provides a minimal fix to a bug where applying the Default preset would remove a layer from the timeline.

fix(preset): enable animation/visibility in default preset

---

externs/slick.grid.externs.js
src/os/ui/slick/slickgrid.js

There was duplicate code that was copy-pasted, including explaining
comments. The code adds the real column definitions to the sort columns
returned by `slick.grid.getSortColumns()` to speed up the sorting
functions. That's been extracted to a function, preserving the
explaining comments.
Also defined a typedef to accurately define the type of the elements in
the sort column array returned by `slick.grid.getSortColumns()` and
given to the sorting functions. This definition includes the column
definitions added by the extracted function described above.

refactor(slickgrid): extract function for sort prep

---

src/os/ui/file/kml/kml.js
test/os/ui/file/kml.test.js

This should prevent the test URL for Google Maps from unnecessarily going through the proxy, in addition to supporting Google Maps icon URLs with both `http` and `https` schemes.

fix(kml): use scheme-relative URL for Google Maps

---

src/os/ui/ui.js

#877 caused unwanted side effects and doesn't seem to be a safe replacement for `$apply`. Code that needs to asynchronously apply an Angular scope should use `os.ui.applyAsync`.

Add function to async apply an Angular scope

---

package.json

This adds the `-a localhost` to http-server. This will default the link to localhost:8282 on server start

chore(http-server): defaults address to localhost

---

src/os/data/histo/sourcehistogram.js

Updated histogram to avoid throwing the CASCADE_CHANGE event in one typical case; which saves a lot of re-rendering.

fix(histogram): added small optimization to histogram updates

---

vendor-min.js

Dependencies of `tui-editor` updated their dependency on `tui-code-snippet`. This broke our vendor minification because `tui-code-snippet.min.js` does not exist in the new version. This PR resolves that module relative to `tui-editor`, so the direct dependency version will be found.
I also switched to using `opensphere-build-closure-helper` for the build to simplify the script a bit.

refactor(vendor-min): resolve tui-code-snippet relative to tui-editor

---

src/plugin/file/kml/kmlmodel.js
src/plugin/file/kml/kmlparser.js

- Provide model defaults from the KML spec (0 for heading/tilt/roll, 1 for scale values).
- Create `KMLModel` typedef so dot notation can be used and enforce compiler type checks.
- Replace `KMLModelParser` class with direct `parseModel` function.

refactor(kml): provide KML model defaults from spec

---

src/os/im/action/importaction.js
src/os/ui/filter/im/filterimporter.js
src/os/ui/im/action/filteractionimport.js
src/os/ui/im/action/filteractionimporter.js

Before when you would use import from feature actions, it wouldn't find any layers to re import.

fix(feature actions): using import button on filter actions works

---

src/os/ui/slick/slickgrid.js

Provide  os.ui.slickGridDirective  to match the exact name of the directive function. Leaving the old provide alone, since that will be addressed with the goog modules -> ES6 transition.

refactor: updated goog provides in slickgrid

---

src/os/ui/window.js

This ticket does two things:
1. Fix a bug where if the window was not resizable, the double-click action on the header would not work...and generate a console error
2.  Add ability to position a window by the bottom of the window. It now allows the 'bottom' scope variable. This will ignore the 'y' scope variable if both are passed in.
There is currently no way to test the bottom positioning in opensphere itself since no components use it to launch. You can test that it doesn't break any existing windows, however, by launching windows and verifying they behave as they did before.

position a window by 'bottom'

---

src/os/command/transformvectorscmd.js

Refactored this a bit to be a little cleaner when adding new items.
The original geometry is used by interpolation, and even though it is not directly referenced by a geometry function, should still be transformed along with everything else.
resolves #743
Test Steps: see #743

fix: transform should be run on original geometry

---

scripts/electron/preload.js

Notify the main process when the client cert handler has been registered. This is used by https://github.com/ngageoint/opensphere-electron/pull/20 to select a client cert on auto update.

feat(electron): notify main process on cert handler registration

---

src/os/ui/menu/listmenu.js

Added some null checks and utilized more streamlined methods of selection in some menus.  Part of a cleanup effort.
Test Steps:
1. [opensphere](http://glorious-soccerball.surge.sh/opensphere/)
2. Load some data, Click on a few dots to select them
3. Right click on the Features layer in the Layers modal > Click "Clear Selection" > Verify all selected dots become unselected
4. Shift+Click and drag a box over some loaded dots > Click "Select" in the popup menu > Verify the appropriate dots become selected
5. Right click on the Map > Click "Clear Selection" > Verify all selected dots become unselected

fix(selection): cleanup related to feature selection

---

externs/electron.externs.js
scripts/electron/preload.js
src/plugin/electron/electronplugin.js

Electron does not natively support `document.cookie`. It has its own [Cookies API](https://www.electronjs.org/docs/api/cookies) to store cookies on a Session object. Closure's `goog.net.Cookies` class and the debug loader both use `document.cookie`, so it would be ideal to override that to interface with Electron's API.
https://github.com/ngageoint/opensphere-electron/pull/22

feat(cookie): override document.cookie in Electron

---

src/os/ui/filter/op/islikeop.js
src/os/ui/filter/op/likelistop.js
test/os/ui/filter/op/islikeop.test.js
test/os/ui/filter/op/likelistop.test.js
test/os/ui/filter/op/notlikeop.test.js

The `is like` and `is like list` operations only worked on single line strings. Added the `m` flag to also match the pattern in multi-line strings.

fix(filter): support multi-line strings for local is like (list) ops

---

scss/opensphere.scss
scss/os/_menu.scss

Using CSS overflow to handle when right-click menus are too large for the page; which addresses the immediate concern so all menu options are available, even in very small browser windows.
Test Steps:
1. Opensphere|http://terrific-parent.surge.sh/opensphere/
2. Shrink the window to an unreasonably small size
3. Right click the map or a Feature layer
4. Verify you can scroll all the way to the top and bottom of the menu

fix(menu): added CSS to handle too-large menus

---

src/os/fn/fn.js

Added an empty function to the `os.fn` namespace for common use.

feat(noop): added an empty function for common use

---

src/os/ui/layer/layerpicker.js

Having issues with LayerPicker updating whenever a higher-level directive modifies the two-way binding scope of "layer(s)". AngularJS needs to watch for changes to it's layer(s) on scope and update the Select2 component to reflect the new scope.

fix(layerpicker): fixed select2 val not updating with scope layer(s)

---

package.json

npm/yarn automatically calls `preX` and `postX` for every call to `npm run X`

chore(package): remove superfluous script call

---

src/os/filter/filterentry.js
src/os/ui/query/queryhandler.js

Replaces the instance of check on FilterEntry with our internal implementation for cases where instance of is not sufficient

feat(filterinstance): register filter class for use with os.instanceOf

---

src/os/defines.js

This fixes instances where this file is being listed before os.js

fix: add os require

---

src/os/ui/dragdrop/dragdrop.js

Using ng-attr-drag-drop="{{someCondition || undefined}}" does prevent the dragDrop directive from being rendered
It would be nice to be able to dynamically disable dragdrop without having to duplicate all of the content.
For example, instead of
```
<div ng-if="ctrl.canRead" drag-drop ...>
....
</div>
<div ng-if="!ctrl.canRead">
....
</div>
```
you could use
```
<div ng-attr-drag-drop="{{ctrl.canRead ? '' : undefined}}" ...>
....
</div>
```
if you check the dragDrop attr in the directive link function.
The drag-drop attribute without a value will be an empty string. Anything not undefined will be rendered.
UUOM-787

feat(dragdrop): allow disabling dragDrop directive with ng-attr

---

docs/guides/plugin_server_guide/src/plugin/tileserver/tileserver.js-parsing

The current server guide code doesn't compile.
This is a bit speculative as a fix though. The `fullId` is what its called in the OGC and WMTS plugins, but the same concept appears to be called `id` here.

docs(server guide): fix configuration

---

src/os/ui/menu/layermenu.js

WIP!
Found this issue when importing a csv that had an ellipse at altitude. When the ellipse was styled as such, go to seemed to work fine. When it was just the center point it went straight to the ground below based on the xy extent.
Test Steps:
Load several layers of different types
Ensure that "Go To" from the context menu works on all of them and any combination of them

feat(goto): use newer flyto for feature layers

---

src/os/ui/slick/slickgrid.js

There was an issue discovered where the wrapper for SlickGrid was using an external HTML ID for the positioning of context menus. That works fine as long as that ID starts at the top left corner of the view port.

improvement(slickgrid): context menu position not rely on external ids

---

src/os/geo/geo.js
test/os/geo/geo.test.js

Only do the Decimal Degrees shortcut if the number of digits is <= 3 for lon and <= 2 for lat.

fix(geo): remove incorrect shortcut in parseLon and parseLat

---

addlayer.js
views/forms/multiurl.html
views/forms/singleurl.html
views/plugin/ogc/ui/ogcserverimport.html

Cleans up some places that were using outdated css for error messages
Here's some before/after examples:

feat(error_class): update use of error class to bootstrap 4 equivalent

---

src/os/object/object.js
test/os/object/object.test.js

Previously, if the key to delete was not in the object, instead of removing it (aka: do nothing), it would go through the add path and the value would become `"__delete__"`. Not good when you really just wanted to ensure that the default was used.

fix(object): merge delete should always delete

---

src/os/source/vectorsource.js
test/os/source/vectorsource.test.js

Previously this would blow up if something attempted feature removal multiple times. Since it is cheap to check if it is been done since we have multiple indices by key/id, we'll do that before removing.

fix(source): better multi-remove protection

---

src/os/source/vectorsource.js
test/os/source/vectorsource.test.js

The option useSpatialIndex=false uses a feature collection rather than an r-tree. Feature removal needs to support that case.

fix(source): fix remove when not using spatial

---

config/settings.json
src/os/config/displaysettings.js
src/os/mapcontainer.js
src/os/webgl/abstractwebglrenderer.js
src/os/webgl/iwebglrenderer.js
src/plugin/cesium/cesiumplugin.js
src/plugin/cesium/cesiumrenderer.js
views/config/displaysettings.html

In the event that more than one webgl renderer is present: 
allow the associated plugin to register it with the mapContainer
allow users to choose one from the display settings

feat(renderer): add display settings hook up for multiple renderers

---

views/badge.html

Putting ng-if on the root element prevents it from linking to the controller. This was changed when fixing `html-validate` errors because we previously had a `div` inside a `span`, which is not allowed.

fix(alert): fix alert badge not displaying

---

src/os/ui/timeline/currenttimemarker.js

Resolved condition where some Date ISO String formats weren't being displayed in "current time" on timeline
Testing Steps:
1. Surge | [http://crabby-level.surge.sh/opensphere/](http://crabby-level.surge.sh/opensphere/)
2. Click the orange "Clock" icon to open the Timeline
3. Verify the current time is shown above the yellow line
4. Verify the current time updates regularly (roughly every second depending on how busy the JS is)
5. Verify clicking the current time, then clicking that area again, hides then shows the time

fix(timeline): showing current date

---

scss/opensphere.scss
scss/os/_propertiestab.scss
src/os/ui/feature/tab/propertiestab.js
views/feature/tab/propertiestab.html

Features with sparsely populated columns do not present well in the Feature Info dialog, if the user does not care about the empty columns. This is common with layers whose metadata fields vary by feature type, like OSM.
This PR adds a toggle button to show/hide empty columns in Feature Info. This preference defaults to showing empty (current behavior) and is saved to settings so the value persists through app refresh.
I also did some cleanup/rework on the Feature Info properties tab:
- Table header is now fixed so scrolling only impacts data rows. This makes it easy to toggle sort and the new show/hide even when scrolled.
- Changing the displayed properties for any reason (new feature, toggling show/hide empty, etc) will now apply the sort so properties are still displayed in the order …

feat(featureinfo): toggle hide empty columns in feature info properties

---

src/os/ui/feature/tab/propertiestab.js

The properties tab doesn't clean up its source listener, causing the controller to be leaked and an error to throw if the source columns change.

fix(feature): clean up source listener in properties tab

---

src/os/ui/screenoverlay.js
src/plugin/file/kml/kml.js
src/plugin/file/kml/kmlparser.js
test/plugin/file/kml/kml.test.js
test/plugin/file/kml/kmlparser.test.js

This PR covers a case where KMZs sometimes contain URIs to relative assets with backslashes instead of forward slashes. This is technically invalid according to the KML spec, but happens often enough in our experience that it's worth having a low-risk workaround to cover it.

fix(kml): fixes resolution of URIs to relative ZIP assets

---

src/os/mapcontainer.js

The image layer group was being added last in the list of default layer groups. This causes OpenLayers to render it on top of the feature/reference group, so features are hidden beneath KML Ground Overlays or other image layers.
This PR adds the image group immediately after the tile group in the default group list, and sets the priority to -1 so it's considered between the tile/feature groups when new groups are added.
Note: This does not impact the Cesium renderer because Cesium renders all tile/image layers first, then Billboards (features) on top of that.

fix(image): order image layers between tile/feature layers in 2D

---

src/os/geo/geo.js
test/os/geo/geo.test.js

This was to fix an edge case in which values such as `10° 30' 36" S` were being rejected by `parseLat` and `parseLon` because the direction regex was not included when `opt_format` is specified.

fix(geo): lat lon parse direction with opt_format

---

src/plugin/file/gpx/gpxparser.js

As mentioned in the comment, OpenLayers parses GPX coordinates as XYZM and adjusts later in `ol.format.GPX.applyLayoutOptions_`. If `flatCoordinates` isn't in XYZM, that function will either botch the coordinates or fail outright when it tries to iterate over the coordinates in groups of 4 values. This happens for GPX data that does not have a time component.

fix(gpx): fix parse error with timeless gpx data

---

src/os/ui/file/filexthandler.js

Utilize the ImportEvent config payload to enable initializing metadata such as name or classification
UUOM-64

feat(xt): pass data payload as ImportEvent config

---

src/os/igroupable.js
src/os/layer/tile.js

Adds the ability to pass a custom layer group ID/label to a tile layer via its layer config. This change can be adapted in the future to other layer types if we need to add custom grouping functionality to them.

feat(layer-grouping): adds setters to IGroupable interface

---

src/os/ui/search/place/coordinateresult.js
src/os/ui/search/place/coordinatesearch.js
src/os/ui/search/place/place.js

Cleans up an improper declaration to allow for proper module requires.

refactor(search): moves property/function to module

---

src/os/source/requestsource.js

Removes the `const` annotation from the RequestSource name. This allows extending ES6 classes to define their own names to register with `os.registerClass`.

fix(request-source): remove const from request source name

---

src/os/data/datamanager.js
test/os/data/datamanager.test.js
test/os/data/osdatamanager.test.js

I was seeing a case where the style of incoming features was causing rapid saves to settings. Specifically:
`os.data.LayerSyncDescriptor.prototype.onLayerChange` would call `this.onStyleChange()` and that event would trigger persisting the descriptors hundreds of times as data streamed in. Hopefully this check will tone down the number of settings calls.
This was causing problems with our custom setting storage option.

fix(settings): add delay to descriptor persistence

---

.github/workflows/release-to-master.yml

Adds an action to automate merging changes from release to master. The action is based on/using https://github.com/marketplace/actions/nightly-merge, slightly adapted to our branch names and to do it on push to release rather than from a cron running nightly. 
I tested a dummy version of the script on some branches on my fork: 
https://github.com/jsalankey/opensphere/actions
https://github.com/jsalankey/opensphere/tree/actions-source-branch
https://github.com/jsalankey/opensphere/tree/actions-target-branch
It's pretty straightforward, but nice to see. The merge commit is created automatically by the `actions-user`. According to the action page, it will fail on a merge conflict and we'll have to fix it manually, as we'd expect.

chore: adds github action for merging release to master on push

---

src/os/mapcontainer.js
src/os/proj/projswitch.js
src/os/query/query.js
src/os/query/queryutils.js
src/plugin/cesium/cesium.js
test/os/query/query.test.js

- Consolidate `os.query` and `os.query.utils` by migrating `isWorldQuery` and related functions / constants
- Update `os.query.utils` to be a module
- Update callers
Breaking change for plugins that utilize `os.query.isWorldQuery`.

chore(query): replace os.query.isWorldQuery into os.query.utils

---

src/os/ui/geo/geo.js
src/os/ui/geo/mgrs.js
src/os/ui/geo/position.js
src/os/ui/search/place/coordinatesearch.js

`CoordinateSearch` strips whitespace, uppercases, and checks a regexp before sending the value off to `osasm`. Now the `position` field does that too.

fix(position): fix whitespace and case before mgrs parse

---

src/os/color.js
src/os/layer/ilayer.js
src/os/layer/layer.js
src/os/layer/layergroup.js
src/os/layer/tile.js
src/os/mixin/layerbasemixin.js
src/os/tile/tile.js
src/os/ui/layer/defaultlayerui.js
views/layer/tile.html
views/plugin/basemap/basemaplayerui.html

Adds a sharpness control to Tile and Base Map layers. Access the control from Layers > (Tile/Base Map Layer) > Style.
Sharpness is adjusted using the convolution filter here: https://www.html5rocks.com/en/tutorials/canvas/imagefilters/
Tests will fail until ngageoint/opensphere-state-schema/pull/18 is merged to add the property to the state schema.

feat(tile): add tile layer sharpness control

---

src/os/data/filedescriptor.js
src/os/parse/baseparserconfig.js
src/os/ui/data/descriptornodeui.js
src/plugin/file/geojson/geojsonimporthandler.js
src/plugin/file/geojson/geojsonmixin.js

Adds support for creating an arbitrary layer backed by GeoJSON data. The GeoJSON import handler will simply run our automapping functionality on the parser file data then add a GeoJSON descriptor backed layer that is persisted and restored.
Includes other specific changes to support a use case for internally creating and persisting a layer as GeoJSON.

feat(geojson): adds handler for importing geojson-backed layers

---

src/os/source/vectorsource.js

Delays garbage collection for features in `VectorSource`.
Removing a CSV layer with 1,000,000 point geometries forces an unreasonably long time where no action can be taken.
Profiling led to the line featured in this PR, which makes some sense as removing event listeners [deletes](https://github.com/openlayers/openlayers/blob/246aded8192391bbeb9034dbf260e84e0f9d58a3/src/ol/events/Target.js#L179) the keys and forces immediate garbage collection. (though via testing with a mixin replacement, it seems `Array.splice` accounts for about half of the deletion time)
[setupChangeEvents_](https://github.com/ngageoint/opensphere/blob/master/src/os/source/vectorsource.js#L530) attaches the `handleFeatureChange_` function as a listener to the …

feat(vector): speed up processing of feature removal

---

externs/Cesium.externs.js
src/plugin/cesium/sync/point.js
test/plugin/cesium/sync/pointconverter.test.js

`Cesium.Resource.createIfNeeded` will always create a new Resource if passed a string. This means we're creating a new Resource/Promise for every icon, whether we have loaded that icon already or not.
This change caches icons by `src`, so Promises will be reused when requesting an icon that has already been loaded.

fix(cesium): reuse icon resources in point converter

---

src/os/data/layernode.js

Adds support for a flag to allow layers to not show the enable/disable checkbox. This is desirable for layers that only exist in memory as they are currently lost when unchecked.

fix(layers): adds check for a layer option for disable checkbox

---

src/os/ui/text/tuieditor.js

We're running a scope apply in the middle of destroying one of the forms that uses the tuieditor.

fix(tuiedit): don't try to access scope after destroy

---

externs/os.externs.js
src/os/config/displaysettings.js
src/os/map/terrain.js
src/os/ui/menu/mapmenu.js
src/os/webgl/abstractwebglrenderer.js
src/plugin/basemap/basemapprovider.js
src/plugin/basemap/terraindescriptor.js
src/plugin/cesium/cesium.js
src/plugin/cesium/cesiumrenderer.js
src/plugin/cesium/tiles/cesium3dtilesdescriptor.js
src/plugin/cesium/tiles/cesium3dtileslayer.js
test/plugin/basemap/basemapprovider.test.js
views/config/displaysettings.html
views/window/confirmtext.html

OpenSphere is currently limited to a single terrain provider, which is determined by the last config loaded from settings. As a user, it would be useful to switch between available providers and also configure custom terrain. This PR addresses the first of those concerns, exposing all configured (and supported) terrain providers through Settings > Map > Display.
**Testing Notes**
[OpenSphere](https://merciful-yarn.surge.sh/)
- In Settings > Map > Display, there should now be a list of supported terrain providers under the Enable Terrain checkbox. This is only displayed if multiple unique (by `id`) terrain layers have been configured.
- Changing the terrain provider should update the active provider in settings. If terrain is enabled, it should update the provider currently used by the …

Support multiple terrain providers

---

src/os/ogc/ogc.js
src/plugin/ogc/wfs/wfslayerconfig.js
test/plugin/ogc/wfs/wfslayerconfig.test.js

Adds the ability to register parser config/type detection for requesting and parsing different WFS formats.

refactor(wfs): adds plugin support for different WFS types

---

src/plugin/file/geojson/geojsonlayerconfig.js
src/plugin/file/gml/gmllayerconfig.js
src/plugin/file/shp/shplayerconfig.js

use mappings adjusted during import wizard instead of retrying the autodetects

feat(import): use manual mapping configs directly

---

webpack.config.js

Adjusts [Webpack performance hints](https://webpack.js.org/configuration/performance/#performancehints) to allow larger assets. This may be further addressed in the future by chunking output, but that is not currently supported.

build(webpack): adjust performance hints for larger assets

---

src/os/layer/tile.js

OL's `obj.set(property, value)` fires a `change:${property}` event automatically. However, the OpenLayers event does not put the new value on the event. Only the old value. Therefore, it is expected that a listener for that event should be able to call the getter for that property (in this case `getSharpness` or `getBrightness`, but also more generically `get(property)`) and return the correct new value.
resolves #1046

fix: fire event only after overridden getter ready

---

src/os/search/searchtermfacet.js
test/os/search/searchtermfacet.test.js

This addresses a few issues in `os.search.SearchTermFacet`.
- Quoted terms did not work properly because terms were simply split on spaces.
- Searching for `*` freezes the app because of an infinite loop in `getScore`.
**Testing**
[OpenSphere (branch)](https://marvelous-quiver.surge.sh/)
[OpenSphere (master)](https://master-branch-opensphere-ngageoint.surge.sh/)
Try whatever terms come to mind. Here are some examples that isolate fixes in this PR.
- `street map` should return results matching `street` or `map`.
- `"street map"` should return results matching `street map`.
- `*` should return all layers. This previously froze the app in an infinite loop.

feat(search): match quoted terms and fix infinite loop without capture

---

karma.conf.js
package.json
src/os/ui/menu/menubutton.js
test/os/os.mock.js
test/os/ui/settingsbutton.test.js
test/os/ui/window/confirm.test.js

Unit testing directives was not fully functional for a few reasons:
- Directives using `templateUrl` cannot be loaded in tests because the URL will not be correct in Karma. [It is recommended](https://docs.angularjs.org/guide/unit-testing#testing-directives-with-external-templates) to use [a Karma preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor) to preload templates and add them to the `$templateCache`. This preprocessor has been added/configured.
- The `os.ui` module could not be loaded because dependent modules `ui.directives` and `ngAnimate` were not available in Karma. Fixed by loading those libraries in the Karma config.
- `os.mock.js` was calling `inject` in `beforeEach`, which prevents tests from loading modules/templates in their own `beforeEach`, …

test(ng): preprocess angular templates so directives may be tested

---

test/os/os.mock.js

Moves the injector assignment out of the `setTimeout`. There were cases where it wasn't registered in time for when it was needed, causing tests to fail.

fix(test): fixes issue where injector is assigned too late

---

test/os/os.mock.js

The global injector instance is added with `angular.mock.inject`, which must be called after all calls to `angular.mock.module` for the current test suite. This currently doesn't cause problems when running all tests, because we only call `inject` if the global injector isn't set yet. So long as the first test that runs does not use `angular.mock.module`, future tests will be fine.
This becomes a problem when using `ddescribe` or `iit` in a UI test, because only that test will run and the `inject` call in `os.mock.js` will precede the `module` calls in the UI test. This PR offers a solution to that by providing a test suite that can also be included via `ddescribe` to ensure the UI test runs normally.
While this is a bit of a workaround, it does work with existing tests. A more complete …

test(init): add test suite to verify globals are initialized

---

src/os/im/mapping/renamemapping.js
test/os/im/mapping/renamemapping.test.js

The rename mapping will not be executed with falsey values like `false`, `0`, and an empty string. I believe this was only intended to handle the null/undefined case.

fix(mapping): execute rename mapping on falsey values

---

karma.conf.js
src/os/ui/window/confirm.js
test/os/ui/settingsbutton.test.js
test/os/ui/window/confirm.test.js

The current [`karma-ng-html2js-preprocessor`](https://github.com/karma-runner/karma-ng-html2js-preprocessor) configuration registers templates by their file path, which requires loading them in tests with `beforeEach(module(<path>))`. This change registers them with the `app` module, so tests only need to call `beforeEach(module('app'))` to load all available templates.
Tests were added/updated to verify templates are being compiled/linked appropriately, including using the `$onDestroy` lifecycle hook in the `confirm` directive instead of listening to the scope `$destroy` event. The old listener was private, so this is a non-breaking change.
**Note for other projects:**
This configuration assumes all loaded directives have the `../opensphere/` prefix in their `templateUrl`, which is true …

test(ng): simplify angular template load in tests

---

src/os/net/urlmodifier.js
test/os/net/urlmodifier.test.js

The config here is called multiple times because the `baseUrl` stuff runs a separate config from `urlReplace`. Do not reset the replacement config so that all of those configs can be added.

fix: fix url modifier with multiple configs

---

src/plugin/file/kml/abstractkmlmanager.js
src/plugin/places/abstractkmlmanager.js
src/plugin/places/placesmanager.js

In the event one might wish to create a managed KML layer similar to Saved Places, I've gone ahead and extracted most of the generic code out to an abstract class.

feat(places): extract code to an abstract manager class

---

src/os/layer/tile.js

The multiplier was causing the Sharpness slider to be extremely sensitive. This should make the slider more useful across the entire range.

fix(tile): reduce the sharpness multiplier

---

package.json

I was personally having an issue with Windows/npm/git-bash where running the copy commands in parallel just crashed out of xargs. There seems to be a common, albeit random, problem where high process/service counts can cause this to happen. Using `npm-run-all` in sequential mode fixes it, though it might slow the build a little.

chore(package): use npm-run-all for copy

---

src/os/mapcontainer.js

`addFeatures` returns the features added to the map rather than the ones passed into the function the same way `addFeature` works.

fix(mapcontainer): add features returns correct features

---

src/os/ui/search/featureresultcard.js
test/os/ui/search/featureresultcard.test.js

The feature result card did not handle the `SelectionType.CHANGED` event, which is fired when `setSelectedItems` is called on a vector source. This PR adds support for that event, as well as simplifying the source event handler behavior.
As part of this update, I added functions to set the select/highlight state of the card so extending classes may contribute their own behavior. I also added a `highlightConfig` property to the class, so extending classes may change how their result is highlighted on the map.

feat(search): update feature result card behavior and extension points

---

src/plugin/cesium/cesiumrenderer.js

When disabling Cesium, the camera move listener was removed without fixing the view hint. This moves management of the `cesiumMoving_` flag to a function that protects against setting the hint by more than +/- 1, and calls the function when Cesium is disabled to reset the hint if needed.
Fixes #1081.

fix(cesium): ensure viewhint is reset when disabling cesium

---

externs/os.externs.js
src/os/track.js
src/os/ui/window/confirm.js
src/os/ui/window/confirmtext.js
src/plugin/track/track.js
src/plugin/track/trackevent.js
src/plugin/track/trackmenu.js
test/os/ui/window/confirm.test.js
views/window/confirm.html

This PR addresses a few things with tracks:
- The Create Track option in the layer menu did not support including original metadata in the resulting track. This is now possible via checkbox in the UI prompt (defaults to false per existing behavior).
- The Add to Track now automatically includes metadata if previously included on the target track. This is intended to avoid gaps in metadata when features are added to the track.
- When including metadata in tracks, the additional fields are not added as columns to the track source (Saved Places currently). This prevented the fields from showing up in UI's that are based on source columns (Feature Info, Show Features, etc).
- The Create/Add To track options in the layer menu have confused some because they use selected data if available, all …

feat(track): prompt to include metadata in tracks

---

src/os/mapcontainer.js

Rotation is currently always 0 in 2D because the canvas renderer is less performant when rotation is applied. There are cases where rotation is desirable, such as orienting imagery to the up angle. This PR enables 2D rotation via the `MapContainer#flyTo` function, so it can be programmatically set by plugins in the 2D view.

feat(map): support rotation in 2D flyTo

---

src/os/metrics/metricskeys.js
src/plugin/places/placesmenu.js

We previously supported this on the Layer view, but not in Places.
Implementation is closely modeled off Layer approach, but uses a different metric key.

feat: support Show Features in Places tab

---

src/os/layer/preset/layerpresetmanager.js
src/os/ui/im/action/filteractiontreesearch.js
src/os/ui/layer/vectorlayerui.js
src/plugin/featureaction/featureactionmanager.js
src/plugin/featureaction/ui/featureactionsui.js

Fixed minor issues with Feature Action searches and filters in edge cases.
Used more robust layerpresetmanager.getPresets() to load all feature actions when adding a source instead of only the embedded loadDefaults().

feat(presets): support sharing presets among matching layerFilterKeys

---

src/os/config/displaysettings.js
src/os/control/rotatecontrol.js
src/os/interaction/interaction.js
src/os/interaction/keyboardtiltrotateinteraction.js
src/os/interaction/mouserotateinteraction.js
src/os/map/mapinteractions.js
src/os/mapcontainer.js
views/config/displaysettings.html

Rotation was disabled in 2D and reset when switching from 3D to 2D for performance reasons. This was largely due to inefficient tile rendering in Chrome, which has since been fixed. The canvas renderer still goes down a less efficient path, but works perfectly fine in many situations. It seems the preferred behavior is to maintain rotation when switching between 3D/2D, so the current view is maintained between the two.
This PR makes the following changes:
- Rotation is no longer reset when switching from 3D to 2D.
- The above can be toggled in Settings > Display if the old behavior is preferred.
- 3D rotation controls now work in 2D. This includes the keyboard (Shift + Left/Right Arrow) and mouse (Right/Middle Click + Drag) interactions.
- The above controls are documented in the Controls …

feat(map): allow rotation in 2d and don't reset when switching to 2d

---

src/plugin/places/placesmanager.js
src/plugin/places/ui/saveplaces.js

There was an issue where `PlacesManager` would be reset (source was null) in the main window context if `getInstance` was called in a separate window, even though dev tools claimed it wasn't.
`launchSavePlaces` is also now `provide`d so that it can be used more easily when updating other files for `goog.module`.

fix(places): instance not initialized across different window contexts

---

src/os/ui/featureedit.js

Dynamic features manage their own rotation/bearing using source data from the track. When editing a track, these values should not be modified. Previously, showing rotation was disabled if you opened feature edit for a track, preventing rotation from being displayed.

fix: don't modify rotation/bearing on dynamic features

---

externs/os.externs.js
src/os/ui/feature/featureinfo.js
src/os/ui/feature/simpleproperties.js
src/os/ui/feature/simplepropertiesui.js
views/feature/featureinfo.html

For data-dense Features, you can now configure the `<simple-properties>` Directive to additionally show the desired field(s) above the alphabetically-sorted Fields table. Configs allow for a per-field exact match and/or regex match(es). "Default" text is optional per-field as well.

feat(featureinfo): Added a new SimpleProperties Directive

---

docs/cookbook/metrics/src/cookbook-metrics.js
docs/cookbook/submenu/index.rst
docs/cookbook/submenu/src/cookbook-submenu.js
src/os/bearing/bearing.js
src/os/data/areanode.js
src/os/data/drawingfeaturenode.js
src/os/filter/filterentry.js
src/os/mainctrl.js
src/os/map/mapinteractions.js
src/os/track.js
src/os/ui/areas.js
src/os/ui/menu/buffermenu.js
src/os/ui/menu/mapmenu.js
src/os/ui/menu/spatialmenu.js
src/plugin/file/kml/kmlfield.js
src/plugin/places/placesmenu.js
src/plugin/position/positionplugin.js
src/plugin/suncalc/suncalcplugin.js
src/plugin/track/trackmenu.js
src/plugin/weather/weatherplugin.js

- `os.ui.menu.spatial` and `os.ui.menu.map` now have `.MENU`, similar to `os.ui.menu.list` etc.
- The old `os.ui.menu.SPATIAL` and `os.ui.menu.MAP` still exist, but have been tagged as deprecated. (is this OK?)
- Some typedefs and enums that are used globally, but have not been provided, now are

chore: update provides for easier es6 transition

---

package.json

Layer sharpness was added in
https://github.com/ngageoint/opensphere-state-schema/commit/ae311e16464c767f3643773e32f14dd88c5f1a3d
and is required for tests to pass. Likely important for users.
Resolves #1098.

chore: bump opensphere-state-schema dependency to 2.10.0

---

src/plugin/arc/arc.js
src/plugin/arc/mime.js
test/plugin/arc/mime.test.js
test/resources/arc/arcgis/wms-130.xml
test/resources/arc/arcgis/wmsserver/wms-130.xml

ArcGIS supports serving content via WMS, which is incorrectly being detected as an Arc server if `arcgis` is in the URL. This ignores those matches if the URL contains `/WMSServer` or `service=WMS`, so the content may be detected by the OGC plugin.
Example URL: https://nowcoast.noaa.gov/arcgis/services/nowcoast/analysis_ocean_sfc_sst_time/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0

fix(arc): don't detect wms url's from an arc server

---

src/os/ui/menu/mapmenu.js
src/os/ui/menu/spatialmenu.js

Minor documentation to provide guidance for external plugins.

docs: add jsdoc for deprecated menu references

---

src/os/ui/dragdrop/urldragdrop.js

run a trim() on text dragged in from the end of the row, because it has a newline in it

feat(urldragdrop): fix mis-interpretation of URL

---

docs/guides/settings_guide.rst

Existing documentation suggested just the URL, which (to me) looked like it would have to be some kind of template (e.g. as we have for the other map providers, using XYZ style). Hopefully this makes it a bit clearer as to what goes where.

docs: expand WMS terrain provider documentation

---

src/os/ui/feature/featureinfocell.js
src/os/ui/slick/slickgrid.js
views/feature/featureinfocell.html

- Ensures that there's always a double click handler that does something in the feature info window.
- Trims copy text in slickgrids.
- Linkifies the "Show Description" text used for opening the description tab in the feature info window.

fix(grid): fixes behavior of copying data in grids, code cleanup

---

package.json

The `dev` script will fail if vendor scripts have not yet been compiled, because generated dependencies will not exist.
Example:
```
There was an error resolving
Error: Resource resolver unable to find vendor/os-minified/os-toastui-editor.min.js. Please ensure it exists or check your template config.
at getDebugPath (node_modules/opensphere-build-resolver/plugins/resources/index.js:128:17)
```

build: compile vendor scripts in dev

---

docs/guides/settings_guide.rst
src/os/ui/feature/featureinfocell.js

I was looking at `featureinfocell.js` and trying to figure out how column actions worked, and didn't see that there was any documentation available.

docs: add columnActions documentation

---

src/os/ui/featurelist.js

The `featurelist` directive did not watch for the scope `$destroy` event and wasn't being disposed. I refactored it to our current best practice pattern of using the `$onDestroy` lifecycle hook instead of `goog.Disposable`.

fix(featurelist): destroy featurelist directive when closed

---

.htmlvalidate.json

This is a new recommended rule in [`html-validate@4.3.0`](https://gitlab.com/html-validate/html-validate/-/releases/v4.3.0), which should have been a breaking change/major release.
https://html-validate.org/rules/text-content.html

build(lint): disable the text-content rule

---

src/os/action/eventtype.js
src/os/interaction/interaction.js
src/os/interaction/modifyinteraction.js
src/os/mixin/mixin.js
src/os/source/imodifiablesource.js
src/os/source/vectorsource.js
src/os/ui/help/controlblock.js
src/os/ui/help/controls.js
src/os/ui/menu/spatialmenu.js
src/plugin/cesium/interaction/cesiuminteraction.js
src/plugin/cesium/sync/converter.js
src/plugin/cesium/sync/dynamiclinestring.js
src/plugin/cesium/sync/dynamicmultipolygonconverter.js
src/plugin/cesium/sync/dynamicpolygonconverter.js
src/plugin/cesium/sync/linestring.js
src/plugin/cesium/sync/multidynamiclinestringconverter.js
src/plugin/cesium/sync/polygon.js
src/plugin/places/placessource.js
test/plugin/cesium/sync/converter.test.js
test/plugin/cesium/sync/dynamicmultipolygonconverter.test.js
test/plugin/cesium/sync/dynamicpolygonconverter.test.js
views/help/controlblock.html
views/help/controls.html

Adds an adapted version of the Modify Interaction provided by Openlayers. This interaction allows for dynamically updating geometries on the map with clicking and dragging. The 3D sync of the interaction is accomplished through the Drawing Layer and new dynamic synchronizers rather than the traditional method used for other pointer interactions (which set update/cleanup functions). This pattern should be cleaner and generally more easily adaptable to other use cases.
There are a few little quirks I still need to iron out:
- The vertex feature gets stuck sometimes in 2D.
- The alt-click interaction is a little funky and doesn't seem to work sometimes when it should. Might be an OL issue.
- Interpolated geometries don't modify as expected due to the intermediate coordinates. This is an …

Modify interaction

---

config/settings.json

The functionality is already in OS, this just makes it more discoverable.

feat: add map units to config

---

src/os/feature/feature.js
src/os/ui/file/kml/abstractkmlexporter.js
src/plugin/file/kml/kmlexporter.js
src/plugin/file/kml/kmltreeexporter.js

Resolves #798.
One way to test is to import a KML file with a non-standard width (say 5) into Places, then export it, and verify the export has the expected (round-tripped) width.
Sample:
```
<?xml version="1.0"?>
<kml xmlns="http://www.opengis.net/kml/2.2"
xmlns:gx="http://www.google.com/kml/ext/2.2"
xmlns:os="http://opensphere.io/kml/ext/1.0">
<Document>
<name>temp area 1</name>
<visibility>1</visibility>
<Placemark id="area_z8biobqpdtxi">
<name>temp area 1</name>
<styleUrl>#default-ffffffff-00ffffff-ffffffff</styleUrl>
<visibility>1</visibility>
<Polygon>
<outerBoundaryIs>
<LinearRing>
<coordinates>147.46239577961353,-27.46437091023244,0 147.46239577961353,-25.727198308700153,0 150.500308352867,-25.727198308700153,0 150.500308352867,-27.46437091023244,0 …
```

fix: use style-specified line width in kml export

---

src/os/layer/preset/layerpresetmanager.js

Makes sure that the default presets get the correct color rather than loading in with a white fill.

fix(presets): default colors correctly set

---

src/os/ui/file/exportdialog.js
src/plugin/file/kml/ui/kmltreeexportui.js
views/file/exportdialog.html
views/plugin/kml/kmltreeexport.html

The UI will no longer state that there are no items when attempting to export a heatmap.
The additional export options directive will no longer be loaded if there are no additional options.

fix: heatmap export items no longer removed from scope

---

externs/electron.externs.js
scripts/electron/preload.js
src/plugin/electron/electron.js
src/plugin/electron/electronplugin.js

Request `latest.yml` from the Electron release URL, if configured. This will ensure the update file exists prior to checking for updates, and will also authenticate with the URL using the selected client certificate so appropriate session cookies will be saved. These cookies are used by ngageoint/opensphere-electron/pull/36 to ensure authentication works properly when checking for updates.

feat(electron): test release url to authenticate and set cookies

---

src/plugin/electron/electron.js
src/plugin/electron/electronplugin.js

The release channel for Electron is determined by the `publish.channel` value in the `electron-builder` config. It defaults to `latest`, but may be set to the branch in CI builds. This PR allows the channel to be configured within OpenSphere, so the Electron process and OpenSphere will use the same value.

feat(electron): make release channel configurable

---

externs/Cesium.externs.js
src/os/layer/image.js
src/os/mixin/imagesourcemixin.js
src/os/mixin/mixin.js
src/plugin/arc/arc.js
src/plugin/arc/arcloader.js
src/plugin/arc/arcplugin.js
src/plugin/arc/layer/arcimagelayerconfig.js
src/plugin/arc/layer/arclayerdescriptor.js
src/plugin/arc/node/arcservicenode.js
src/plugin/cesium/mixin/cesiummixin.js
src/plugin/cesium/sync/imagesynchronizer.js
src/plugin/cesium/sync/polygon.js
test/plugin/arc/node/arcservicenode.test.js

This PR includes updates to allow for loading an Arc FeatureServer that has no corresponding MapServer as well as adding support for the Arc ImageServer service. This works very easily in 2D mode through Openlayers' included `ImageArcGISRest` source, but had some hitches in 3D, some of which still need addressing. I have been unable to solve these two issues:
1. The images sometimes get clipped by the globe.
2. There is occasional flickering when swapping out the primitive with a new one on a fresh image loading.

Add support for Arc ImageServer and better FeatureServer support

---

externs/electron.externs.js
scss/opensphere.scss
scss/os/_electron.scss
src/plugin/electron/electronconfirmcert.js
views/plugin/electron/electronconfirmcert.html

The existing Electron certificate selection UI lacks in a few areas:
- If the default cert isn't the one you want, it takes three clicks to change it (open dropdown, select cert, OK).
- The dropdown doesn't show enough information about the cert until opened, and questionably not then either.
To address these issues, each certificate is now displayed as a card with clearly displayed cert details.
Old UI:
New UI:

refactor(electron): rework certificate selection ui

---

src/os/mixin/imagesourcemixin.js

Had the call in there wrong creating a loop and call stack overflow. Fixed to call the parent class one correctly.

fix(image): properly call parent class dispose

---

src/plugin/file/shp/shpparser.js

Two issues have been identified/fixed with the SHP parser:
- The Table Field Descriptor defines the field type at byte 11, not 12.
- If an empty field was encountered, the read position would not be advanced by the field length. This causes all further fields to be incorrectly read.
The following file illustrates the issue. The feature with an empty `FIELD_B` has an incorrect value read for `FIELD_C`.
[Empty FIELD_B.zip](https://github.com/ngageoint/opensphere/files/5905335/Empty.FIELD_B.zip)

fix(shp): advance position on empty field and fix type offset

---

package.json
src/os/ol/olext.js
src/os/ol/typedefs.js
src/os/os.js

GCC assumes `ol` already exists due to including `typedefs.js` as an externs file. It also never creates the `ol.ext` namespace, presumably due to how those files are included in the compilation which results in Closure not replacing their
`goog.provide` statements properly.

fix(ol): fix errors with gcc's compilation of ol namespaces

---

docs/guides/es6_transition_guide.rst
docs/guides/goog_module_to_es6_guide/index.rst
docs/guides/goog_module_to_es6_guide/src/os/index.js
docs/guides/goog_module_to_es6_guide/src/os/myclass.js
docs/guides/settings_guide.rst
src/plugin/cesium/primitive.js
src/plugin/cesium/sync/baseconverter.js
src/plugin/cesium/sync/baseconverter.shim.js
src/plugin/cesium/sync/iconverter.js
src/plugin/cesium/sync/iconverter.shim.js
src/plugin/cesium/sync/runconverter.js

This PR is intended as an example to show how `goog.module` files can be converted to ES6 modules. The approach to default exports is described in Closure's documentation here:
[Migrating from goog.modules to ES6 modules](https://github.com/google/closure-compiler/wiki/Migrating-from-goog.modules-to-ES6-modules)
In short, if you `goog.require` an ES6 module with `goog.declareModuleId` and a default export, the returned object will have a `default` property for the default export. To maintain backward compatibility, we will create temporary shim files that expose the original namespace by re-exporting the temporary ES6 module namespace. As files referencing the dependency are converted to ES6, they can `import` the original file and eventually the shim can be deleted.

refactor(cesium): convert goog.module to es6 modules

---

src/os/ui/capture/timelinerenderer.js
src/plugin/capture/captureplugin.js

Resolves #1063.
Testing will require generating and viewing the GIF recording with a couple of different themes to verify correct rendering.

fix(capture): avoid hard coding timeline fill

---

package.json
src/os/ui/file/kml/abstractkmlexporter.js
src/os/ui/file/kml/kml.js
src/plugin/file/kml/kmlplugin.js
src/plugin/file/kml/ui/kmlexportui.js
tasks/symlink.sh

When the primary Google icon source is unavailable, KMLExport will switch the icon source to either 
1) the fully-Location-resolved internal `/images/icons/kml` folder (e.g. https://my.url/images/icons/kml/...), or
2) a mirror website, as configured in `settings.json`.

feat(kml): utilizes mirror for kml icon exports

---

src/plugin/file/shp/ui/shpfilesstep.js

Currently is if user tried to import a shapefile within electron the shapefile import dialog would pop up asking for the other file dbf or shp.  The user would be allowed to browse for a file and select it but it would never populate the import dialog and never allow the user to import a shapefile.  This fix now allows the user to import the shapefile.

fix(shapefile): fix shapefile import dialog in electron

---

src/os/ui/menu/menu.js
src/os/ui/scaleline.js

The report (#746) says Units doesn't close. It looks like it doesn't, but what is really happening
is the menu closes (on "click outside" processing), and then opens again (in response the click).
There is existing logic in the menu code to properly handle toggle actions, but it only works for
buttons (based on nodeName like 'button' or 'btn-group' in the classes). Changing that could have
unintended consequences outside of OpenSphere, so the approach is the allow subclasses to specify
that they can be toggled.

fix(scaleline): ensure menu closes on toggle action

---

package.json

I develop on Windows & the missing configurations meant I could no longer build.

fix: symlink script added for non-linux builds

---

src/os/source/vectorsource.js
src/os/ui/menu/spatialmenu.js
src/plugin/places/placessource.js

The modify functions for the modify interaction were not updating the original geometry on the feature, causing subsequent modify operations to use the wrong geometry. This fixes the issue, and changes the modify menu option name/icon to distinguish it more from Modify Area. In the future, those two menu options will likely be combined to further ease confusion.

Fix issues with source modify functions

---

scss/standard/_bootswatch.scss
src/os/ui/alert/alertlinkfilter.js

The `.btn-link` override causes any button with this class to differ in size from other buttons. This causes unwanted UI layout issues, so it is being removed. Instead, local style overrides should be used when things like border/padding need to be removed.

style(btn): remove btn-link override in place of ad-hoc adjustments

---

src/plugin/file/shp/shpexporter.js
test/plugin/file/shp/shpexporter.test.js

Files are marked as UTF-8.
Also fixes a problem where non-ASCII values would be corrupted on export. 
Adds a new test file for shapefile export.
Resolves #767

feat(shp): add codepage sidecar file to shapefile export

---

src/os/ui/nodetoggle.js
src/os/ui/slick/slickgrid.js
src/os/ui/slick/slicktree.js
src/os/ui/slick/slicktreenode.js

Needed for a client ticket adding Object Type Counts to all Object Type Trees.
- Improve interface for styling SlickTree for typesTree in bits-internal.
- Adds extension to slicktreenode for Object Type Tree nodes. Most of the style interface changes are made in slicktreenode for accessibility to other instances but can be moved to the new objecttypenode.js.

feat(slicktreestyle): improve interface for styling slickTree

---

src/os/ui/ogc/ogcserver.js

WMS Folders with no WMS Layers no longer throw null JS error

fix(folder): prevent error for empty wms folders

---

src/os/im/action/filteractionentry.js
src/os/im/action/importaction.js
src/os/im/action/importactionmanager.js
src/os/layer/animatedtile.js
src/os/os.js
src/os/webgl/abstractrootsynchronizer.js
src/os/webgl/abstractwebglrenderer.js
src/os/webgl/synchronizermanager.js

Added several `goog.requireType` statements for types referenced in JSDoc only.

refactor: add requireType for types in jsdoc

---

src/os/ui/ogc/ogcserver.js

In #1180 I tried to avoid creating a `DescriptorNode` if it was going to later be swapped for a `SlickTreeNode` due to the "layer" actually being a folder. This broke something in an app based on OpenSphere, so I'm reverting that change.

Revert WMS layer parsing behavior

---

scss/os/_utils.scss
scss/overrides_slate/_bootswatch.scss

Cleans up tab styling in flyout to match windows. Removes the .95 opacity from the flyout background as well as it doesn't seem to serve much purpose, and can look a little weird in some cases.

fix(tabs): include flyouts in the tab styling special case

---

scss/os/_overrides_bootstrap.scss
src/os/data/registry.js
src/os/data/registryproperychange.js
src/os/im/action/importactionmanager.js
src/os/layer/preset/layerpresetmanager.js
src/os/layer/preset/preset.js
src/os/layer/preset/presetmenubutton.js
src/os/ui/layer/vectorlayerui.js
views/layer/vector.html
views/layer/vectorstylecontrols.html

"Presets" dropdown now follows the selected value instead of being simply a list from which Presets can be chosen/applied.
When the current style does not match the previously set Preset (or default), then the dropdown will be replaced with "Customized" and a link-button to view the dropdown and return to a Preset style.

feat(styles): preset dropdown follows selection

---

src/os/ui/config/abstractsettings.js
src/os/ui/windowui.js

If the Settings window is quickly opened/closed, these timeout callbacks will fail due to the window being disposed and referenced properties being null.
I looked at replacing the window timeout with `$onInit`, but that does get called earlier than a timeout and may impact existing handlers of the `OPEN` event.

fix(window): add checks to avoid errors if window is disposed

---

src/os/interaction/interaction.js

Features that are omitted from the drawing layer tree are typically preview features for operations like geometry modification, buffering, etc. We avoid hit detecting these features because they're considered temporary. However the `DRAWING_LAYER_NODE` flag is more broadly useful for features added by non-vector layers, which may use the drawing layer to render these features. Such features are typically also given the `INTERACTIVE` flag, which enables hit detecting them in the hover interaction. This flag should also enable hit detection in interactions like the context menu, so options relevant to the hit feature can be displayed.

fix(draw): hit detect drawing features flagged as interactive

---

scss/os/_closetab.scss

We've had some commentary that the close flyout tab button was a little too small. This ups the size to make it a bit more prominent and easier to see.

fix(style): enlarges close tab style, css cleanup for positioning

---

src/os/ui/draw/basedrawcontrols.js
src/os/ui/draw/drawcontrols.js

`hidesExtraControls` is accessed in `initControlMenu` called from the constructor. For any es6 subclasses, where `this` may not be called before `super()`, extra controls will always be visible even if that is not desired.
`supportsLines` was also being assigned to itself which is probably not the correct behavior.

fix(drawcontrols): missing config assignments in base draw controls

---

src/os/source/vectorsource.js
src/os/style/styletype.js

feat(vector): add custom select color
Add CUSTOM_SELECT `styletype.js` and changed` vectorSource.js` to check for a set custom select style and apply it it, or use the default select style type if it was not set. This allows a feature item to have a custom color style set for the Select option and to avoid conflicts with set feature colors. 
Not tickets or breaking issues attached to this commit.

feat(vector): add custom select color

---

src/os/ui/windowui.js

If multiple modal windows are open, they currently do not update their z-index when clicked. This prevents bringing the clicked modal to the front of others on screen, which is not the desired behavior.
This happens because modal windows are ignored in `updateZIndex_` for window stacking. `os.ui.window.stack` correctly handles stacking modal windows against one another, so we do not need to ignore them.
I noticed this while testing #1199, which has a modal Add Server dialog that can open another modal with server URL formatting help. The same behavior can also be observed by importing a CSV and opening the Format Help dialog in the Geometry/Time steps.

fix(window): update modal window zindex when clicked

---

src/os/ui/windowui.js

If the `onWindowReady` handler is called after the window is disposed, the `constrainWindow_` call will fail because the scope/element have been set to null. This adds a sanity check to ensure the window has not been disposed before proceeding.

fix(window): check if window is disposed in ready handler

---

views/window/dockedwindow.html

`html-validate` added a new rule in their latest release, [aria-label-misuse](https://html-validate.org/rules/aria-label-misuse.html), that does not allow the `aria-label` attribute in non-interactive elements. To resolve this, the elements were changed to `button` instead of `span`.
Using `<span role="button">` would also indicate the elements are interactive and resolve the error, but would create two new warnings because `button` is preferred by the `prefer-native-element` rule.

fix(window): add button role to indicate the element is interactive

---

src/plugin/file/kml/kmlnodelayerui.js

Features with multiple geometries (such as an ellipse that consists of a center point and a ring) will now show fill as an option in the layers menu, and will no longer auto-fill when the color is changed.

feat(formulas): disable input when no cell is selected

---

externs/Cesium.externs.js
package.json
src/plugin/cesium/primitive.js
test/plugin/cesium/primitive.test.js

I upgraded Cesium to start looking into using their [GlobeTranslucency API](https://cesium.com/docs/cesiumjs-ref-doc/GlobeTranslucency.html) to display subsurface/bathymetric data. That will require further investigation, but I did want to pick up bug fixes/performance improvements from their last year of releases.
There were no breaking changes that impacted OpenSphere, but I updated our primitive visibility management to use the new `show` flag on collections. OpenSphere now supports toggling visibility at the collection level, instead of individually toggling primitives within the collection.
Full change log here:
https://github.com/CesiumGS/cesium/blob/master/CHANGES.md

feat(cesium): upgrade cesium to 1.79.1

---

src/os/ui/ol/interaction/contextmenuinteraction.js

`os.ui.ol.ContextMenuOptions` is missing a require, this fixes that.

fix(interaction): add require for ContextMenuOptions

---

externs/os.externs.js
src/os/data/foldernode.js
src/os/data/layertreesearch.js
src/os/data/zorder.js
src/os/layer/folder.js
src/os/layer/foldermanager.js
src/os/layer/foldermenu.js
src/os/mainctrl.js
src/os/ui/layer/vectorlayerui.js
src/os/ui/layers.js
src/os/ui/layertree.js
src/os/ui/node/foldernodeui.js
src/os/ui/slick/abstractgroupbytreesearch.js
test/os/data/foldernode.test.js
test/os/data/zorder.test.js
test/os/layer/folder.test.js
test/os/layer/foldermanager.test.js
views/layers.html

This PR adds the ability for the user to create their own persistent folders to the layers window. The folder management itself is made to be as decoupled from the layers/z-order management as possible so as to cause no impacts to the way that the layers window works currently if the user doesn't want to create their own folders. It is not currently toggleable as a feature, but it should be totally possible to disable it if it is not desired and for everything to behave exactly like it used to.
- Root level folders are parented to particular groupings in the current group by and only transfer between group bys in the case that there are identical parents available.
- Child folders have standard tree behavior.
- Layers respect z-ordering for their sorting and can be dragged and dropped …

Adds user-created folders to the layers window

---

src/os/layer/preset/layerpresetmanager.js
src/os/layer/preset/preset.js

- Fix: Registry entries (`LayerPresetManager.presets_`) can probably return `null` and should be checked
- Fix: Presets setting their fill color to the layer's base color makes fill be 1.0 instead of what it probably should be

Fix: Preset fill & null registry check

---

.jscodeshift.json
test/plugin/cesium/primitive.test.js
test/plugin/cesium/scene.mock.js
test/plugin/cesium/sync/converter.test.js
test/plugin/cesium/sync/dynamiclinestring.mock.js
test/plugin/cesium/sync/dynamiclinestringconverter.test.js
test/plugin/cesium/sync/dynamicmultipolygonconverter.test.js
test/plugin/cesium/sync/dynamicpolygonconverter.test.js
test/plugin/cesium/sync/ellipseconverter.test.js
test/plugin/cesium/sync/ellipsoidconverter.test.js
test/plugin/cesium/sync/featureconverter.test.js
test/plugin/cesium/sync/geometrycollectionconverter.test.js
test/plugin/cesium/sync/gettransformfunction.test.js
test/plugin/cesium/sync/heightreference.test.js
test/plugin/cesium/sync/labelconverter.test.js
test/plugin/cesium/sync/linestring.mock.js
test/plugin/cesium/sync/linestringconverter.test.js
test/plugin/cesium/sync/multidynamiclinestringconverter.test.js
test/plugin/cesium/sync/multilinestringconverter.test.js
test/plugin/cesium/sync/pointconverter.test.js
test/plugin/cesium/sync/polygon.mock.js
test/plugin/cesium/sync/polygonconverter.test.js
test/plugin/cesium/sync/runconverter.test.js
test/plugin/cesium/sync/style.test.js
test/plugin/cesium/vectorcontext.test.js

I added a new transform to [opensphere-jscodeshift](https://github.com/schmidtk/opensphere-jscodeshift) that finds/replaces global references in sources/tests. For source files, the transform simply adds a legacy `goog.require` then replaces it because the replace call already updates refs. For test files, a `goog.module.get` call is either found or added for each detected reference. The call is added directly to the root `describe()` call containing the reference, so subsequent references may reuse it.
To generate the changes in this PR, the transform was executed with:
```
yarn run shift -t src/transforms/es6/replaceglobals.js /path/to/opensphere/test/plugin/cesium
```
Global reference replacement is config driven by new config in `.jscodeshift.json`. The config defines the root …

test(cesium): replace global refs in tests

---

scss/os/_datepanel.scss
scss/os/_overrides_bootstrap_variables.scss
scss/os/_searchresults.scss
src/os/ui/list.js
src/os/ui/nav/navbaroptions.js
src/os/ui/util/punyparent.js
views/datepanel.html
views/osnavtop.html
views/plugin/ogc/ui/ogcserverhelp.html

The top nav had a few issues with its collapse behavior, namely:
1. The collapsed state did not initialize properly, so items would overlap when first loading OpenSphere.
2. The left/right/center were allocated a fixed size, which caused button collapse to happen earlier than needed.
3. The time UI was shifted down to a new row too late, so it would sometimes overlap other elements.
4. Changing the size of the time UI (for example, setting duration to `custom`) would not cause buttons to collapse and could result in overlap.
Changes to address the above:
- The `punyparent` directive now detects when children are added/removed from the element and recomputes the max size needed for the expanded state, then updates the expanded state. (Fixes 1)
- The `osnavtop` template was updated so the …

Iterate on nav bar collapse behavior

---

src/plugin/cesium/cesium.js
src/plugin/cesium/tiles/cesium3dtileslayer.js

Feedback was received that the Cesium Ion access token prompt could be more descriptive. To resolve that, the dialog was reworded as well as adding a link to Ion that more completely describes the service.
It was also determined that cancelling the access token prompt should also remove the layer, so that was also added.

feat(cesium): provide more ion info and remove layer if canceled

---

src/os/ui/providerimport.js
src/plugin/arc/arcserverimport.js
src/plugin/ogc/ui/geoserverimport.js
src/plugin/ogc/ui/ogcserverimport.js
views/file/addserver.html
views/forms/multiurl.html
views/forms/singleurlform.html
views/plugin/ogc/ui/ogcserverimportform.html

The forms used to import servers had inconsistent validation logic, and also were no longer disabling the Save button appropriately when the form was invalid. I fixed the Save button for both the new Add Server UI and the Import Data route, and made validation consistent across all forms.
I also added some context-sensitive text to the forms and help UI's to make them a little less generic.

fix: use consistent validation across all import forms

---

src/os/ui/file/addserver.js

The icon came from the Import Data dialog, but this dialog is more specific and should be consistent with other server UI's.

fix(addserver): match icon to other server ui's

---

src/plugin/cesium/sync/imagesynchronizer.js

Image layers are getting clipped by the globe above certain zoom levels. To reproduce, add this Arc layer and pan the globe to the US.
https://services.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer
At zoom ~5.2 a partial image renders, but it's clipped by a diagonal line. This may have been caused by our last Cesium upgrade because they made a lot of changes with how things are rendered with respect to the globe when implementing globe translucency.
Changing the geometry to a rectangle instead of a polygon fixes the issue. We have noticed that rectangles render better at large scales, and it seems they also work better with GroundPrimitive and an image material. I did have to normalize the longitudes for the rectangle coords, because Cesium expects all rectangle coords …

fix(cesium): fix clipping issues in image layers

---

src/plugin/cesium/sync/imagesynchronizer.js

This should resolve the remaining issues list in #1235.
- Image layers should now display properly when a pole is in view. This was caused by Cesium's internal determination of Rectangle east/west and north/south coords being the same if within a particular threshold.
- Image layers should display properly on initial load, particularly when the app is first loaded and the image request may take longer. The rendering issue was caused by trying to render the image in Cesium before it had finished loading.

Fix Cesium rendering issues with image layers

---

src/plugin/cesium/command/flytospherecmd.js
src/plugin/cesium/interaction/cesiuminteraction.js
src/plugin/cesium/tiles/cesium3dtileslayer.js

The value of `os.map.PROJECTION` may change, so we shouldn't destructure the value when importing. Destructuring will get the _current_ value, and the reference will not update if the original changes.
Values like this will eventually need to be refactored because ES module exports cannot be reassigned, so we will need a getter/setter. For now, assign the exported object and reference the current `PROJECTION` value from there.

fix(cesium): don't destructure PROJECTION because it may change

---

src/plugin/cesium/command/flytospherecmd.js
src/plugin/cesium/interaction/cesiuminteraction.js
src/plugin/cesium/sync/imagesynchronizer.js
src/plugin/cesium/tiles/cesium3dtileslayer.js

Image layers only display properly when using EPSG:4326. This resolves the issue by requesting the image in the supported projection and reprojecting the image to display properly on the Cesium globe.
This PR includes the fix from #1241, so there will be an extra commit displayed until that is merged.

Fix display of image layers in 3D when using alternate projections

---

src/os/source/vectorsource.js

Point and MultiPoint are not interpolated, which was firing the feature change event for other geometries. This ensures a change event will always be fired on a modified feature.

fix(vector): notify feature changed in modify function

---

src/os/ui/nav/navbaroptions.js
src/os/ui/util/punyparent.js

If an element using `punyparent` had a direct child that wasn't an `Element`, the resize listener would fail because `appendElement` is only supported by Elements. This may happen if the direct child has an `ng-if`, which will replace the element with a comment when the condition is false.
I also fixed incorrect HTML in some nav elements. I had a partial fix previously to change the `li` to a `div`, because the list we're adding to already wraps elements in an `li` and that nesting was invalid. Fixed the closing element to also use `div`.

fix(puny): only watch resize on Element children

---

src/os/interaction/modifyinteraction.js
src/os/mainctrl.js
src/os/ui/animationsettings.js
src/os/ui/column/columnmanager.js
src/os/ui/datetime/wheeldate.js
src/os/ui/descriptioninfo.js
src/os/ui/draw/drawpicker.js
src/os/ui/featureedit.js
src/os/ui/im/filesupport.js
src/os/ui/ol/interaction/abstractdrawinteraction.js
src/os/ui/ol/interaction/drawpolygoninteraction.js
src/os/ui/propertyinfo.js
src/os/ui/query/area/userarea.js
src/os/ui/slick/asyncrenderer.js
src/os/ui/textprompt.js
src/os/ui/timeline/abstracttimelinectrl.js
src/os/ui/timelinesettings.js
src/os/ui/window/confirm.js
src/os/ui/windowui.js
src/plugin/position/copyposition.js

This fixes remaining deprecation warnings with the exception of:
- `goog.inherits`: These will be resolved as we migrate to modules.
- `goog.iter.Iterator`: We're extending `goog.storage.mechanism.IterableMechanism` which has not been deprecated, and still requires defining a function that returns a `goog.iter.Iterator`. I don't think we can resolve this one without a more significant refactor, and presumably Closure will have a better solution before they remove the deprecated class.

Fix remaining Closure library deprecations

---

.htmlvalidate.json
scss/opensphere.scss
scss/os/_ringoptions.scss
views/color/colorpalette.html
views/column/mapping/columnmappingexport.html
views/data/addcolumn.html
views/feature/featureinfocell.html
views/file/importdialog.html
views/forms/multiurl.html
views/forms/singleurl.html
views/forms/singleurlform.html
views/geo/ringoptions.html
views/plugin/ogc/ui/ogcserverimport.html
views/plugin/ogc/ui/ogcserverimportform.html
views/query/editarea.html
views/query/mergeareas.html
views/window/stateimportexport.html

- Replaced inline `style` with CSS classes.
- Allowed `ng-style`. This directive is useful for dynamically changing styles based on scope/controller values.
- Replaced `<input type="submit" hidden>` with `<button type="submit" hidden></button>` per `htmlvalidate` suggestion. I also fixed some cases where Enter was not submitting a form, such as the generic import dialog and server import UI's.
- Updated `htmlvalidate` config to error on checks that have been resolved.

Fix html lint warnings

---

src/plugin/electron/electronplugin.js
src/plugin/electron/net/electronhandler.js

Created a new electron request handler at the same priority level as ext/same-domain in order to prevent any proxying from occurring in opensphere-desktop.
(Fixes an issue where `os.net.ProxyHandler` always handles "proxyable" requests even without configuration).

fix(net): electron domain handler to prevent uri modification

---

src/os/file/mime/text.js

Fix for character detection where the `Unit8Array` variable was created but not used.

fix: chardetng-wasm proper variable type

---

src/os/geo/jsts.js
src/os/interaction/drawpolygoninteraction.js
src/os/ogc/filter/ogcspatialformatter.js
src/os/ui/ol/interaction/drawpolygoninteraction.js
src/plugin/ogc/query/ogcspatialformatter.js

The line/polygon draw tools were not working in projections other than EPSG:4326 because the geometry was always normalized using that projection, instead of the current map/geometry projection.
We previously normalized the geometry using `x = 0` instead of the default (first geometry coordinate), which was causing rendering issues across the antimeridian. I believe this was intended to resolve issues with servers not accepting the coordinates in the geometry we send, so that solution will need to be reviewed.
[Test Deployment](https://os-fix-polygon-normalization.surge.sh/)
- Drawing lines/polygons across the antimeridian should work in both 2D and 3D, in both EPSG:4326 and EPSG:3857.
- Drawing large polygons (spanning more than half the world) should both display properly and query …

fix(draw): normalize polygons/lines in current projection

---

src/plugin/vectortools/vectortools.js

Adds actual configuration for the support created in !1034

fix(vectortools): hide the disable checkbox for merge/join layers

---

src/os/ui/query/modifyarea.js

This is causing issues due to internal tight dependency couplings that must be resolved properly at some point, but for now, this keeps it consistent with the original way the class functioned.

fix(area-modify): do not require area manager just yet

---

src/os/structs/tristatetreenode.js
src/os/ui/data/layercheckbox.js
src/os/ui/search/facetnode.js
src/os/ui/slick/loadingnode.js
src/os/ui/tristatecheckbox.js

Adds a new checkbox UI for layer providers/folders that allows for turning on full sets of layers. This UI will prompt the user to confirm when turning on more than a predefined number of layers with a single click for safety. This is currently only employed by the Geopackage plugin provider from opensphere-plugin-geopackage, but can be adapted to any provider we like.

feat(add-data): adds support for turning on full providers from add data

---

src/os/data/registry.js
src/os/ogc/registry.js
test/os/data/registry.test.js

Include the full entry instead of just the key when firing add, update, remove, and clear events
BREAKING CHANGE: Callbacks for registry event handlers now must accept the full entry, not just the
key; and in the case of remove/clear, the entry() and get() functions will not return a value
anymore

improvement(registry): improve EventTarget events

---

src/os/ui/data/descriptornodeui.js
views/data/descriptornodeui.html

`views/data/descriptornodeui.html` was deleted because it was no longer referenced and the HTML within was converted into a string in the last place that it was referenced

fix: trash icon now appears consistently in the Add Data window

---

index.js
old-template.html
package.json
scss/os/_mixins.scss
scss/os/_overrides_slickgrid.scss
src/os/ui/layer/layervisibility.js
src/os/ui/layersbutton.js
src/os/ui/measurebutton.js
src/os/ui/menu/defaultwindowsmenu.js
src/os/ui/menu/spatialmenu.js
yarn.lock

This PR upgrades the Font Awesome library to the free version of v5. It includes the v4 shim for full backward compatibility, so apps using OpenSphere as a library may upgrade at their own leisure.
[OpenSphere](https://os-fontawesome-5.surge.sh/)
1. Poke around the application and verify icons display correctly.
2. The Layers window/button icon was updated as well as the Measure button. Verify the new icons are acceptable over the old ones, and feel free to suggest others. I considered the ruler for measure, but the drafting compass seemed more precise for measuring distance/angle between points on a map.
- The FA5 eye/eye-slash icons were not the same width, so the layer visibility toggle now has `fa-fw` to avoid width changes on toggle.
- Changed the Layers icon to `fa-layer-group` on …

Upgrade Font Awesome to v5

---

src/os/ui/file/kml/abstractkmlexporter.js

The `plugin.file.kml` module is referenced but not required.

fix(kml): add missing require

---

src/plugin/file/csv/csvplugin.js
src/plugin/file/geojson/geojsonplugin.js
src/plugin/file/gpx/gpxplugin.js
src/plugin/file/shp/shpplugin.js
src/plugin/file/zip/zipplugin.js

I got a little overzealous moving constants to the module scope, which impacted external projects. File plugin `ID` and `TYPE` have been moved back to a class constant to un-break the change.

refactor(file): move constants back to the class object

---

views/config/servers.html

Some icons in the Servers UI did not display properly because they only have a solid icon in the free Font Awesome icon set. Those icons use font weight 800, and the `btn` class uses font weight 400. That prevented the icon from being displayed.
The use of `<i class="btn">` is not recommended (they should not be a click handler), so to resolve the issue I switched the UI to use `button` elements. I did not find any other UI's in OpenSphere that were doing this.

fix(servers): use actual buttons to fix FA icon display issue

---

src/os/data/histo/timelinehistmanager.js
src/os/hist/hist.js
src/os/ianimationsupport.js
src/os/layer/animatedtile.js
src/os/source/vectorsource.js
src/os/ui/timelinepanel.js

Currently only `os.layer.AnimatedTile` and `os.source.Vector` support toggling the "timeline open" state via `setAnimationEnabled`. This would be useful for other layers/sources that need to behave differently depending on the state of the timeline. This PR makes a few changes to expand support for animation:
- Any layer/source may implement the new `os.IAnimationSupport` interface to have their animation state toggled when the timeline is opened or closed.
- Any layer/source may implement the existing `os.hist.IHistogramProvider` interface to provide a histogram to be rendered on the timeline.

Animation support for arbitrary layers/sources

---

src/plugin/basemap/basemap.js
src/plugin/basemap/basemapconfig.js
src/plugin/basemap/basemapdescriptor.js
src/plugin/basemap/basemapgroup.js
src/plugin/basemap/basemapplugin.js
src/plugin/basemap/basemapprovider.js
src/plugin/basemap/layer/basemaplayer.js
src/plugin/basemap/terraindescriptor.js
src/plugin/basemap/terrainlayernodeui.js
src/plugin/basemap/terrainlayernodeui_shim.js
src/plugin/basemap/ui/basemaplayerui.js
src/plugin/basemap/ui/basemaplayerui_shim.js
src/plugin/basemap/v2/basemapstate.js
src/plugin/basemap/v2/basemaptag.js
src/plugin/basemap/v3/basemapstate.js
src/plugin/basemap/v3/basemaptag.js
src/plugin/basemap/v4/basemapstate.js
src/plugin/basemap/v4/basemaptag.js
src/plugin/cesium/terrainlayer.js
test/plugin/basemap/basemapdescriptor.test.js
test/plugin/basemap/basemapprovider.test.js
test/plugin/basemap/v4/basemapstate.test.js

This transform was straightforward, no additional refactors necessary.
I did notice a bug preventing `minZoom` and `maxZoom` from being saved to state files for basemaps. The layer config did not have `minResolution` or `maxResolution` keys, which we were depending on to be converted to zoom levels. To resolve this, the first zoom or resolution key encountered for min/max zoom will be converted to XML and the other key ignored if present. These values should be equivalent if both are present.

Transform basemap plugin to goog.module

---

src/plugin/heatmap/heatmap.js

The export options did not define a persistence method so it was going down the local storage path. I added the `FilePersistence` method so the heatmap will be saved to a file. I also cleaned up some global references in `heatmap.js`. Those are in a separate commit to help review the actual change here.

Fix heatmap export

---

scss/os/_overrides_tuieditor.scss
src/os/annotation/annotation.js

- Updated the annotation edit minimum height so the OK/Cancel buttons are visible again.
- Fixed the unicode string for the TUI editor Task button icon. The `fa-check-square-o` icon from FA4 is now `fa-check-square` with the regular font weight.

fix(annotation): update annotation edit height and fix tui task icon

---

src/os/command/nonqueryclearcmd.js
src/os/command/queryclearcmd.js
src/os/data/areatreesearch.js
src/os/layer/vector.js
src/plugin/arc/layer/arcfeaturelayerconfig.js
src/plugin/descriptor/facet/areafacet.js
src/plugin/ogc/wfs/querywfslayerconfig.js

Replaces hard dependencies on area/query managers with the instance API's. This is not exhaustive of all references, but resolves dependency issues in external projects. Remaining references will be replaced as files are transformed to modules.

refactor(query): use query instance api for managers

---

.htmlvalidate.json
src/os/auth.js
src/os/mainctrl.js
src/os/mixin/urltilemixin.js
src/os/ui/data/baseprovider.js
src/os/ui/server/abstractloadingserver.js
src/os/ui/servers.js
test/os/auth.test.js
views/config/servers.html

Adds an API for registering servers that support additional authentication methodologies besides PKI/basic auth. It supports registration of a pattern to match servers as well as ways to link out and message to the user that they are connecting to a server that may provide more data than it appears on the surface.

feat(auth): adds basic api/hooks for servers with special auth support

---

src/os/command/abstractlayerstylecmd.js
src/os/command/abstractstylecmd.js
src/os/command/abstractvectorstylecmd.js
src/os/command/feature/featurecentershapecmd.js
src/os/command/feature/featurecolorcmd.js
src/os/command/feature/featureiconcmd.js
src/os/command/feature/featurelabelcmd.js
src/os/command/feature/featurelabelcolorcmd.js
src/os/command/feature/featurelabelsizecmd.js
src/os/command/feature/featurelinedashcmd.js
src/os/command/feature/featureopacitycmd.js
src/os/command/feature/featureshapecmd.js
src/os/command/feature/featureshowlabelcmd.js
src/os/command/feature/featuresizecmd.js
src/os/command/layerstylecmd.js
src/os/command/vectorlayercolorcmd.js
src/plugin/heatmap/cmd/gradientcmd.js
src/plugin/heatmap/cmd/intensitycmd.js
src/plugin/heatmap/cmd/sizecmd.js

Noticed that attempting to edit the style of a Place (or other KML feature) would throw a console error if done via the Layers window rather than the Feature Edit window. Seems like, due to the es6 updates to commands, the `getOldValue()` call in `AbstractStyle.prototype.constructor` was throwing (as `AbstractFeatureStyle.prototype.featureId` can't be set until after it executes).
Tried a couple things, but this seemed like the safest method.

fix(style): feature style commands no longer error

---

src/os/style/iconreader.js
src/os/ui/file/kml/kml.js

It seems like if Google URIs are replaced with an internal hosted path to the icon, we might want to replace those to the default icon path when importing KML back into the application.
Not doing this has potential to cause issues with the versioned build folders. Openlayers 2D mode falls back to a default icon if it 404s (missing symlink with the default mirror path etc.) but Cesium doesn't render anything at all.

fix(kml): deconstruct mirrored icons back to local copies on import

---

package.json
yarn.lock

This should fix our new errors on the nightly build: 
`error  Attribute "multiple" is not allowed on <input type="hidden">  input-attributes`
and
`error  Attribute "required" is not allowed on <input type="hidden">  input-attributes`
This appears to fail on `ng-require` attributes

chore(html-validate): limit html-validate version to 4.13

---

src/os/layer/config/abstracttilelayerconfig.js
src/os/state/v4/baselayerstate.js
src/plugin/basemap/v4/basemapstate.js

Basemaps now save with a group ID that is unique to the statefile. Grouping will now only occur within layers from the state rather than between state and non-state layers. Cross origin behavior will now respect the value saved in the statefile for basemaps. Basemaps already often override the value set in settings, so this PR prefers the value saved to the state.

fix(basemaps): fixes basemap group id and crossorigin in states

---

src/os/layer/foldermenu.js
src/os/ui/layertree.js

Fixes issues with layer drag and drop not working properly with Places and with reparenting in certain cases. Also fixes an issue with the menu showing the Create Folder option on non-layer nodes in the tree.

fix(layers): cleans up layer drag/drop behavior

---

scss/opensphere.scss
scss/os/_layercompare.scss
src/os/layer/tile.js
src/os/ui/layer/compare/layercompareui.js
src/os/ui/layers.js
src/os/ui/menu/defaultwindowsmenu.js
src/os/ui/menu/layermenu.js
views/layer/compare/layercompare.html
views/layers.html

This adds a new UI that compares two layers side-by-side with a slider control in the middle. To get to the UI, select two layers in the Layers window, right-click (or hit the new Selected Actions button), and choose Compare Layers.
- Changed the default width of the Layers window to avoid collapsing the new/updated buttons by default. Layers window defaults can also be configured via the `os.layers.defaults` settings key.
- The Toggle Tiles button now correctly sets the enabled state (checkbox) instead of the layer visibility state (eye icon, which isn't displayed on tile layers).

Add UI to directly compare layers

---

src/os/im/importer.js

This reverts deduplication added for ellipse mappings in #1318, because it does not work with all mapping types (`toField` is specific to `RenameMapping`). This causes mappings like LAT/LON to replace one another. We will need to consider a different approach for the ellipse mapping issue.

fix(importer): revert mapping comparison

---

src/os/map/imapcontainer.js
src/os/mapcontainer.js
src/os/ui/ol/olmap.js
src/os/ui/query/area/userarea.js

`flyToExtent` was implemented on both `OLMap` and `MapContainer`, but was not present on the `IMapContainer` interface. This caused a compile error when transforming map classes, which was incorrectly fixed in `os.ui.query.area.UserAreaCtrl#setArea` by using `getMapContainer`.

fix(query): use IMapContainer instance and add flyToExtent to interface

---

package.json
scripts/electron/preload.js
yarn.lock

Changes to support upgrading Electron to the latest (currently 13.1.6).
This PR supplements ngageoint/opensphere-electron/pull/42.
- Loads maximum memory config in the preload script.
- Electron 13.x limits types that can be passed across the context bridge, and numbers are not allowed. Converted the memory value to a string before sending to the main process.

fix(electron): set maximum memory in preload script and fix type

---

src/plugin/featureaction/featureactionnodemenu.js

Right now if you open up feature actions and right click on one or more selected FAs, the right click context menu will not show up.

fix(featureactions): fix missing right click menu on feature actions

---

src/os/ui/providerimport.js

This controller is used both as an embedded form (in Add Server), and as the complete window content (on import auto detect or edit). In the second case, the `modal-body` element is a child of the controller's root element. This wasn't being resolved properly, and the `container[0]` reference was undefined causing an error.

fix(provider): ensure modal body is located before scrolling

---

src/os/interpolate.js
src/os/ui/featureedit.js
src/plugin/file/kml/kmltreeexporter.js
src/plugin/places/places.js
src/plugin/places/placesmenu.js
src/plugin/places/ui/quickaddplaces.js

Places can now be modified properly based on their originally drawn geometries rather than their interpolated ones. This should not affect exports of KML geometries in other contexts, only when we write them to Places.

fix(places): places now save their uninterpolated geometries

---

src/os/im/featureimporter.js
src/plugin/file/kml/kmlparser.js

ID columns will now no longer replace or lose their columns on importing exported data. KMLs no longer show a phantom visibility column.

fix(file): cleans up issues with id/visibility columns

---

package.json
src/os/ol/ext.js
src/os/ol/typedefs.js

The `ol.ext` compiler issue is dependent on application load order. This provides a new module that will create the namespace, that can be loaded as the first application `entry_point`. If any plugins are in use, this needs to be added to their `entry_point` configuration as well. The resolver will dedupe these, but `ol.ext` needs to be required first in the generated `.build/index.js`.

build(ol): fix compiled error with missing ol.ext namespace

---

src/os/mixin/mixin.js
src/plugin/overview/overviewmapcontrol.js

The new layer compare feature does not work well when the main map is in 3D and the camera rotated.
This is caused by a mixin we added to prevent some unwanted behavior with the overview map, where small changes in rotation would cause the overview map to jump to a new zoom level that was 0.5-1 from the current zoom. When using mouse rotate in 3D, this causes the overview map to flicker as it zooms in/out rapidly as you rotate the camera.
To resolve this behavior, the resolution constraint has been simplified for the overview map's view to only constrain resolution within the min/max values.

fix(overview): simplify resolution constraint on the overview map

---

src/os/ui/filter/coltypecheckvalidation.js
src/os/ui/filter/filterpatterns.js
src/os/ui/filter/ui/groupnodeui.js

The `<select>` element wasn't being terminated correctly, causing the rest of the HTML to be dropped in rendering. I also encountered an issue with SHP columns being typed as "text" and "real", which caused us to be unable to create feature action filters on them.

fix(filter): fixes filter remove select, validation type bug

---

package.json
src/os/source/source.js
src/os/style/label.js
src/os/style/style.js
src/os/style/stylemanager.js
src/plugin/cesium/mixin/cesiummixin.js
src/plugin/electron/customizesettingsui.js
src/plugin/electron/customizesettingswindow.js
src/plugin/electron/settingsimportmanager.js
src/plugin/electron/settingsimportui.js
yarn.lock

- Imports that are not locally referenced (typically Angular modules and mixins) now use a bare import, so we don't need to disable eslint.
- Relative parent imports (using `../`) have been replaced with module-relative imports.
- Import statements have been sorted by group (external -> internal -> relative sibling) and alphabetically by path within each group.
Module-relative imports resolve the package from `node_modules`. This broke the GitHub build which does not use a Yarn workspace, so I had to add an alias to the webpack config (build/test and a new eslint config to set the eslint resolver to use webpack). In a Yarn workspace, the `opensphere` project will always be linked in the root `node_modules`.

Update imports to follow latest eslint rules

---

src/os/data/datamanager.js
src/os/state/v2/basefilterstate.js
src/os/ui/state/stateprovider.js

In `DataManager#createProvider` we check for a `setInstance` function on the provider class. This works if the class uses `addSingletonGetter` to add the call, but not with a `static getInstance` function. The latter will be compiled to a different symbol, which prevents the data manager from detecting its presence.
Static functions do not work well with interfaces, so instead of implementing an interface and checking that in the data manager, this uses `@export` to prevent renaming the function so the data manager can look for `clazz['getInstance']`.
This also fixes a bug caused by replacing `ol.array.find` with `Array#find`, on something that isn't an array. In this situation, the object is a `NodeList`.

Fix state provider instance and filter load bug

---

src/os/ui/ogc/ogcserver.js

Certain Geoserver WMS resource URLs had trailing &'s, which the goog URI code was parsing into empty parameters. These were causing states containing those layers to fail to write. This prevents that issue at the source of the problem and anything else that may have misbehaved from an empty KVP.
fixes #1372

fix(wms): remove empty wms parameters

---

src/os/geo/geo.js
src/os/mixin/imagesourcemixin.js
src/plugin/file/kml/kml.js
test/os/geo/geo.test.js
test/plugin/file/kml/kml.test.js

- Fixed the high level issue that values beyond `lon, lat` in a `LatLonQuad` should be ignored.
- `isSameCoordinate`'s length check was not working because the `!` was misplaced which converted the length to a boolean. Those expressions would have always evaluated to false, so those checks effectively did nothing. I changed the checks to verify the coordinate has at least 2 values to avoid breaking cases where an altitude (or potentially time) is present.

fix(kml): ignore altitude in LatLonQuad coordinates

---

src/os/classregistry.js
src/os/instanceof.js

`registerClass` should never be called with a duplicate name. If this happens, we will now throw an assertion error in the development build.
I also moved the `os.instanceOf` export to the `os.classRegistry` module because the `os.instanceOf` module is for legacy purposes and will eventually be deprecated/removed.

fix(os): throw assertion error when registering a duplicate class

---

src/os/interaction/hoverinteraction.js
src/os/source/vectorsource.js
src/os/style/style.js
src/os/ui/search/featureresultcard.js

Vector sources check a custom highlight field on features when setting the highlight style. This is currently expected to be an object, but this PR allows it to be a function that returns the config object. This is similar to how OpenLayers handles styles, and allows the highlight to be dynamic if needed.
I also changed the hover interaction so the highlighted feature will be cleared on view change. This is in support of changing highlight styles based on the current map view, for example filling polygons until they take up too much of the view. The highlight clear does not immediately happen in 2D because OpenLayers only replays existing canvas draw instructions while interacting for performance reasons. Once interaction stops, features will be redrawn without the highlight. In 3D the …

feat(vector): allow using a function for custom highlight

---

src/os/state/v2/basefilterstate.js

This was another overzealous replacement (on my part) for a `forEach` convenience method on something that's not an array (`NodeList`). Switched back to the convenience method that works on array-like objects.

fix(state): fix issue loading states with filters

---

src/os/state/v2/basefilterstate.js

In the ESM transition, `this.sources` was initialized as an empty array. This fixed a compiler error (class properties must be defined in the constructor) but caused a bug with applications expecting the sources to be null/undefined if `setSources` was never called. This change represents the original behavior, which will process filters in `saveInternal` if the sources array is not defined.

fix(state): allow filter sources to be null

---

src/os/ui/featureedit.js

This is an adjustment to [this change](https://github.com/ngageoint/opensphere/commit/4d5009c8b2fa7d8293fd85721e70b82fcdd3f479#diff-4d3b504b078016ec0674f86dbe54918b5224d8cd98ada9f0a6d801c1d26d74ee) which was intended to correct the preview not appearing in 3D when creating a new place from the Places tab. The geometry was not being synchronized if the feature initially had no geometry, so re-adding the feature resolved the issue. However we _only_ want to add the feature to the map container if it's a temporary preview feature (ie, during Create not Edit).

fix(places): only add temp preview feature to map container

---

src/os/ui/layer/compare/layercompareui.js
src/os/ui/menu/layermenu.js
views/layer/compare/layercompare.html

Makes the following improvements to the layer compare window:
- Adds the ability to zoom to layers in it with the right click menu.
- Allows adding the same layer to both sides of the compare for better comparisons against static data.
- Fixes issues with having the same layer on the same side more than once.
- Handles layers that are removed from the main map and disposed.

Feat layer compare improvements

---

src/os/ui/capture/htmlrenderer.js
src/plugin/capture/annotationtailrenderer.js

- The map canvas was being passed to `html2canvas` as the target canvas. This is incorrect, as we expect to draw the annotation to its own canvas then draw that to the overall screenshot canvas using the computed offset. This was breaking the map canvas in 2D (the library was resizing it and drawing to it), and making capture fail in 3D (`html2canvas` expects a 2D canvas).
- In 3D, the tail for annotations currently outside the map view were being drawn in the top/left corner of the screenshot. This was due to not testing if the SVG element was visible prior to adding it to the screenshot.
Fixes #738.

Fix issues with annotations in screen capture

---

scss/os/_mixins.scss
scss/os/_ngvalidate.scss
scss/os/_overrides_bootstrap.scss
scss/os/_overrides_jqueryui.scss
scss/os/_overrides_openlayers.scss
scss/os/_overrides_select2.scss
scss/os/_overrides_tuieditor.scss
scss/os/_timeline.scss
scss/os/_tristate.scss

We have a number of `stylelint-disable` lines in our SCSS. I revisited these to either replace them with compliant SCSS or document why they're still needed.
Below is a summary of the changes, in order of the commits in this PR.
1. Removed `cursor: -webkit-(grab|grabbing)` because these are automatically added by our sass build. The font smoothing vendor prefixes are allowed, and improve the look of Font Awesome icons on MacOS. Because vendor prefixes are dropped for the sort, these are expected to be sorted as `font-smoothing`.
2. We enforce a max nesting depth and had one violation that wasn't caught by the old `sass-lint` rules, but was easily fixed by combining selectors without intermediate styles.
3. We had a number of `<style>: initial` properties that were directed at Chrome < 41, …

Replace/document stylelint-disable usage

---

src/os/state/state.js
src/os/state/v4/baselayerstate.js
src/os/url/url.js
test/os/state/state.test.js
test/os/url/url.test.js

State files previously included any layer that didn't use a `local://` or `file://` scheme in their URL, or any layer that didn't define our canned set of properties (`url` and `url2`). This was causing layers added from a [GeoPackage](https://github.com/ngageoint/opensphere-plugin-geopackage) to be included because GPKG feature layers use the `gpkg://` scheme and GPKG tile layers do not have a URL.
We will now determine if a layer should be included by:
- Gathering defined URLs from layer options using `url`, `url2` (used by file plugins like SHP), and `urls` (used by tile layers).
- Checking if _at least_ one URL is defined.
- All defined URL's must be a remote URL, which currently tests if the string starts with an http, https, or ftp scheme. Please comment if we should support other …

fix(state): only include remote layers in state files

---

src/os/mixin/rbushmixin.js
src/os/parse/baseparserconfig.js
src/os/parse/csv/csvparserconfig.js
src/os/ui/im/fileimportwizard.js

- When importing a file, the preview features used to display data in the import wizard were not being removed from the parser config. They are now cleaned up when import finishes (complete or cancel).
- The RBush mixin was holding references to features in the module-scoped `featureSets` array. That array is recreated on each call, and references are no longer needed when the call completes. The array is now cleared once the result set has been determined to avoid retaining features in memory.
Fixes #1039.

Fix feature memory leaks in file import and RBush mixin

---

src/plugin/file/shp/shp.js
src/plugin/file/shp/shpexporter.js
src/plugin/file/shp/shpparser.js
test/plugin/file/shp/shp.test.js

The SHP exporter previously split both `MultiPoint` and `MultiPolygon` geometries into individual geometries. The SHP specification supports both of these via the `MultiPoint/MultiPointZ` shape and `Polygon/PolygonZ` with `parts` for each polygon/ring. This support was implemented in the exporter. I also consolidated and documented some of the logic that was duplicated between allocating space for a geometry and appending the geometry to the buffer.
The SHP parser did not implement support for `MultiPoint` shapes. This is now implemented so OpenSphere can import these geometries.
Resolves #433.

feat(shp): add multipoint and multipolygon import/export support

---

src/os/ui/featureedit.js
src/plugin/places/places.js

This fixes a couple of issues with fields displayed for Saved Places:
- The `TIME` column was being used for time, which doesn't exist until the place is exported/imported (the KML exporter saves the field). Instead, the internal `recordTime` column is now used by the source. This fixes time not displaying in Feature Info for new places.
- Altitude will now be displayed in Feature Info for places.
- Ellipse fields (semi major/minor and orientation) were not displaying for newly created places, but would display after app refresh. This is due to mappings being detected/executed by the KML importer on refresh. This was fixed by detecting/executing mappings when a place is created/edited, so fields should always be accurately displayed in Feature Info.
Fixes #1080.

Fix issues with Saved Places field display

---

src/os/style/stylereader.js
src/os/style/textreader.js
src/plugin/file/kml/kml.js
test/os/style/textreader.test.js

Implemented the `toConfig` method in `TextReader`. This is used by the KML parser to convert the parsed OpenLayers style into an OpenSphere style config object, which will accurately portray the label as defined in the KML.
Resolves #1194.

feat(style): add toConfig support to text reader

---

src/plugin/file/kml/kmlparser.js
src/plugin/file/kml/kmlsource.js
src/plugin/file/kml/ui/kmlnode.js

When a KML layer is hidden, annotations and overlays associated with the layer are currently not being hidden. This updates `KMLNode` to manage visibility for these map items based on the node checkbox, animation state, and layer visibility.

fix(kml): show/hide annotations/overlays with layer

---

src/os/extent.js
src/os/layer/image.js
src/os/layer/tile.js
src/os/layer/vectortile.js
src/os/mapcontainer.js
src/plugin/arc/arc.js
src/plugin/arc/layer/arcimagelayerconfig.js
src/plugin/arc/layer/arclayerdescriptor.js
src/plugin/arc/node/arcservicenode.js
test/plugin/arc/layer/arclayerdescriptor.test.js
test/plugin/arc/node/arcservicenode.test.js

This fixes/changes Go To behavior for Image, Tile, and VectorTile layers.
- Image layers were not setting the layer extent, so Go To would not work.
- Tile and VectorTile layers would not show Go To if the extent was 80% of the current projection's extent. This behavior has been removed, so the option will display as long as the extent is not empty.
- Arc layers were not handling the extent projection. The extent will now be parsed into an appropriate projection, if the extent's source projection is supported by OpenSphere.
- When zooming to a large extent, the 50% buffer that was applied would sometimes exceed the world extent, which would cause the 2D view to zoom a world over. This has been fixed.
Other Changes
- Fixed test JSON for Arc, which put `wkid` directly under `extent`. This …

Fix issues with Go To

---

src/os/ui/layer/vectorlayerui.js

The icon rotation controls are dependent on having columns to choose from, and should not be displayed in the absence of columns. This also fixes an issue where selecting multiple vector layers will clear the rotation column, because no columns are present and the column selection is changed to an empty string.

fix(layer): don't show rotation controls if columns aren't present

---

src/plugin/cesium/sync/linestring.js
src/plugin/file/kml/kmlparser.js

This fixes a couple issues identified in #907. Namely:
- I don't think we are properly defaulting altitudeMode to clampToGround
- I don't think we are properly reading tessellate, which should correspond to os.interpolate.Method.NONE if 0
The first is true of all geometries. The KML specification states altitude mode should default to `clampToGround` for all geometry types. The KML parser will now do this if `altitudeMode` is not set on the parsed geometry.
For the second item, if `tessellate` is disabled (0 or false) we will disable interpolation on the geometry. I also updated the Cesium converter to use `Cesium.ArcType.NONE` when interpolation is disabled. This will render geometries as defined by the KML spec.

KML default altitude mode and line tessellate support

---

src/os/state/v2/layerstate.js
src/os/state/v3/layerstate.js
src/os/state/v4/baselayerstate.js

This is another regression from the ESM transition. I reviewed all `forEach` calls in our state code since this has come up a few times there. All remaining calls are on arrays.

fix(state): use os.array.forEach on NodeList

---

src/os/ui/layer/compare/layercompareui.js
views/layer/compare/layercompare.html

Adds a button to toggle back and forth between an overlapping and side by side layout, and updates the screenshot function to work with both.

feat(compare): adds side-by-side layout support

---

src/plugin/arc/arc.js
src/plugin/arc/layer/arcfeaturelayerconfig.js
src/plugin/arc/layer/arclayerdescriptor.js
src/plugin/arc/source/arcrequestsource.js
test/plugin/arc/layer/arclayerdescriptor.test.js
test/plugin/arc/state/v4/arclayerstate.test.js

- ArcGIS tile layers use the color from the service metadata's `drawingInfo.renderer`, but feature layers do not. That object defines how features should be rendered to the map, so feature layers should use this color as well.
- FeatureServer service metadata also defines a `maxRecordCount`, which is the maximum number of records that will be returned by a request. The Arc request source was chunking requests by the default value of 1000, when it should be getting this number from the service metadata. Doing so will reduce the number of requests made to load features when an Arc service supports requesting more than the default number of records.

Fixes for ArcGIS feature layers

---

package.json

+ update `core-js-bundle` to resolve issue: `core-js-bundle@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues.`

fix(dep): update core-js-bundle
